#!/usr/bin/env node
const fs = require('fs'), path = require('path');

const D = [
  // STARTERS
  ['st-sl-001','/ˈbæd.mɪn.tən/','I play badminton with my friends.','Tôi chơi cầu lông cùng với bạn bè.','cầu lông'],
  ['st-sl-002','/bɔːl/','He threw the ball over the wall.','Anh ấy ném quả bóng qua bức tường.','quả bóng'],
  ['st-sl-003','/ˈbeɪs.bɔːl/','Baseball is a popular sport in America.','Bóng chày là một môn thể thao phổ biến ở Mỹ.','bóng chày'],
  ['st-sl-004','/ˈbɑː.skɪt.bɔːl/','He is very tall and good at basketball.','Anh ấy rất cao và chơi bóng rổ giỏi.','bóng rổ'],
  ['st-sl-005','/bæt/','He hit the ball with a wooden bat.','Anh ấy đánh quả bóng bằng chiếc gậy gỗ.','gậy đánh bóng'],
  ['st-sl-006','/biːtʃ/','We went to the beach to swim.','Chúng tôi đi đến bãi biển để bơi.','bãi biển'],
  ['st-sl-007','/baɪk/','She rides her bike to school every day.','Cô ấy đạp xe đến trường mỗi ngày.','xe đạp'],
  ['st-sl-008','/bəʊt/','We rented a small boat to go on the lake.','Chúng tôi thuê một chiếc thuyền nhỏ để đi trên hồ.','con thuyền'],
  ['st-sl-009','/bʊk/','I am reading a very interesting book.','Tôi đang đọc một cuốn sách rất thú vị.','cuốn sách'],
  ['st-sl-010','/baʊns/','The children like to bounce on the bed.','Bọn trẻ thích nhảy tưng tưng trên giường.','nảy / tung lên'],
  ['st-sl-011','/ˈkæm.rə/','I used my camera to take photos of the animals.','Tôi dùng máy ảnh để chụp hình các con vật.','máy ảnh'],
  ['st-sl-012','/kætʃ/','Try to catch the ball when I throw it.','Hãy cố gắng bắt lấy quả bóng khi tôi ném nó.','bắt lấy'],
  ['st-sl-013','/dɒl/','The little girl is playing with her doll.','Bé gái đang chơi với búp bê của mình.','búp bê'],
  ['st-sl-014','/drɔː/','Can you draw a picture of a house?','Bạn có thể vẽ một bức tranh về ngôi nhà không?','vẽ'],
  ['st-sl-015','/ˈdrɔː.ɪŋ/','She is very good at drawing animals.','Cô ấy rất giỏi vẽ các con vật.','bức vẽ / việc vẽ'],
  ['st-sl-016','/draɪv/','My father drives me to school in his car.','Bố lái xe đưa tôi đến trường.','lái xe'],
  ['st-sl-017','/ɪnˈdʒɔɪ/','I really enjoy playing tennis with my brother.','Tôi rất thích chơi quần vợt với anh trai.','thích thú / tận hưởng'],
  ['st-sl-018','/ˈfeɪ.vər.ɪt/','What is your favourite sport?','Môn thể thao yêu thích của bạn là gì?','yêu thích'],
  ['st-sl-019','/ˈfɪʃ.ɪŋ/','My grandfather loves going fishing on Sundays.','Ông tôi thích đi câu cá vào các ngày Chủ nhật.','câu cá'],
  ['st-sl-020','/flaɪ/','We like to fly our kite in the park.','Chúng tôi thích thả diều trong công viên.','bay / thả (diều)'],
  ['st-sl-021','/ˈfʊt.bɔːl/','The boys are playing football in the field.','Các cậu bé đang chơi bóng đá trên sân.','bóng đá'],
  ['st-sl-022','/ɡeɪm/','Let’s play a board game together.','Hãy cùng nhau chơi một trò chơi bàn cờ.','trò chơi'],
  ['st-sl-023','/ɡɪˈtɑːr/','He is learning to play the guitar.','Anh ấy đang học chơi đàn ghi-ta.','đàn ghi-ta'],
  ['st-sl-024','/ˈhɒb.i/','My favourite hobby is reading comic books.','Sở thích của tôi là đọc truyện tranh.','sở thích'],
  ['st-sl-025','/ˈhɒk.i/','They play hockey on the ice in winter.','Họ chơi khúc côn cầu trên băng vào mùa đông.','khúc côn cầu'],
  ['st-sl-026','/dʒʌmp/','The frog can jump very high.','Con ếch có thể nhảy rất cao.','nhảy'],
  ['st-sl-027','/kɪk/','Kick the ball into the net to score a goal.','Đá quả bóng vào lưới để ghi bàn.','đá'],
  ['st-sl-028','/kaɪt/','It is a windy day, perfect to fly a kite.','Hôm nay trời có gió, rất hợp để thả diều.','con diều'],
  ['st-sl-029','/ˈlɪs.ən/','I like to listen to pop music in my free time.','Tôi thích nghe nhạc pop vào thời gian rảnh.','nghe'],
  ['st-sl-030','/ˈmjuː.zɪk/','She loves listening to classical music.','Cô ấy thích nghe nhạc cổ điển.','âm nhạc'],
  ['st-sl-031','/ˈfəʊ.təʊ/','Can you take a photo of us, please?','Bạn có thể chụp cho chúng tôi một bức ảnh được không?','bức ảnh'],
  ['st-sl-032','/piˈæn.əʊ/','My sister plays the piano beautifully.','Chị gái tôi chơi đàn piano rất hay.','đàn piano'],
  ['st-sl-033','/ˈpɪk.tʃər/','There is a beautiful picture on the wall.','Có một bức tranh đẹp trên tường.','bức tranh / bức ảnh'],
  ['st-sl-034','/pleɪ/','Let’s go out and play in the garden.','Chúng ta hãy ra ngoài và chơi trong vườn.','chơi'],
  ['st-sl-035','/ˈreɪ.di.əʊ/','My grandfather listens to the news on the radio.','Ông tôi nghe tin tức trên đài phát thanh.','đài phát thanh'],
  ['st-sl-036','/riːd/','I like to read a story before going to sleep.','Tôi thích đọc một câu chuyện trước khi đi ngủ.','đọc'],
  ['st-sl-037','/raɪd/','I am learning to ride a horse.','Tôi đang học cưỡi ngựa.','cưỡi / đi (xe đạp)'],
  ['st-sl-038','/rʌn/','The dog loves to run in the park.','Con chó thích chạy trong công viên.','chạy'],
  ['st-sl-039','/sɪŋ/','She has a beautiful voice and loves to sing.','Cô ấy có giọng hát hay và thích hát.','hát'],
  ['st-sl-040','/ˈskeɪt.bɔːd/','He got a new skateboard for his birthday.','Anh ấy được tặng một chiếc ván trượt mới dịp sinh nhật.','ván trượt'],
  ['st-sl-041','/ˈskeɪtˌbɔː.dɪŋ/','Skateboarding is a very popular sport among teenagers.','Trượt ván là một môn thể thao rất phổ biến với thanh thiếu niên.','môn trượt ván'],
  ['st-sl-042','/ˈsɒk.ər/','They play soccer in the stadium every Saturday.','Họ chơi bóng đá ở sân vận động mỗi thứ Bảy.','bóng đá (Mỹ)'],
  ['st-sl-043','/sɒŋ/','This is my favourite song on the radio.','Đây là bài hát yêu thích của tôi trên đài.','bài hát'],
  ['st-sl-044','/spɔːt/','Swimming is a very healthy sport.','Bơi lội là một môn thể thao rất tốt cho sức khỏe.','môn thể thao'],
  ['st-sl-045','/ˈstɔː.ri/','My mother tells me a story every night.','Mẹ tôi kể cho tôi một câu chuyện mỗi tối.','câu chuyện'],
  ['st-sl-046','/swɪm/','I go to the pool to swim on weekends.','Tôi đến hồ bơi để bơi vào cuối tuần.','bơi'],
  ['st-sl-047','/ˈteɪ.bəl ˌten.ɪs/','We have a table tennis table in our garage.','Chúng tôi có một bàn bóng bàn trong ga-ra.','bóng bàn'],
  ['st-sl-048','/teɪk ə ˈfəʊ.təʊ/','Don’t forget to take a photo of the beautiful view.','Đừng quên chụp một bức ảnh cảnh đẹp nhé.','chụp ảnh'],
  ['st-sl-049','/ˈtel.ɪ.vɪʒ.ən/','We watch a film on television every Friday.','Chúng tôi xem một bộ phim trên tivi mỗi thứ Sáu.','tivi'],
  ['st-sl-050','/ˈten.ɪs/','You need a racket and a ball to play tennis.','Bạn cần một cây vợt và một quả bóng để chơi quần vợt.','quần vợt'],
  ['st-sl-051','/ˈten.ɪs ˌræk.ɪt/','I bought a new tennis racket for the tournament.','Tôi đã mua một cây vợt tennis mới cho giải đấu.','vợt tennis'],
  ['st-sl-052','/θrəʊ/','Throw the ball to me!','Ném quả bóng cho tôi!','ném'],
  ['st-sl-053','/tɔɪ/','The baby is playing with a plastic toy.','Em bé đang chơi với một món đồ chơi bằng nhựa.','đồ chơi'],
  ['st-sl-054','/ˌtiːˈviː/','Turn off the TV and do your homework.','Tắt tivi đi và làm bài tập về nhà.','tivi (viết tắt)'],
  ['st-sl-055','/wɔːk/','We go for a walk in the forest every Sunday.','Chúng tôi đi dạo trong rừng mỗi Chủ nhật.','đi bộ / đi dạo'],
  ['st-sl-056','/wɒtʃ/','I like to watch cartoons on Sunday morning.','Tôi thích xem phim hoạt hình vào sáng Chủ nhật.','xem'],

  // MOVERS
  ['mv-sl-001','/bænd/','My brother plays the guitar in a rock band.','Anh trai tôi chơi guitar trong một ban nhạc rock.','ban nhạc'],
  ['mv-sl-002','/ˌsiːˈdiː/','I bought a new CD of my favourite singer.','Tôi đã mua một đĩa CD mới của ca sĩ tôi yêu thích.','đĩa CD'],
  ['mv-sl-003','/ˈsɪn.ə.mə/','We are going to the cinema to watch a movie.','Chúng tôi đang đi đến rạp chiếu phim để xem phim.','rạp chiếu phim'],
  ['mv-sl-004','/ˈkɒm.ɪk/','He is reading a funny comic.','Cậu ấy đang đọc một cuốn truyện tranh hài hước.','truyện tranh'],
  ['mv-sl-005','/ˈkɒm.ɪk bʊk/','I have a large collection of comic books.','Tôi có một bộ sưu tập truyện tranh lớn.','cuốn truyện tranh'],
  ['mv-sl-006','/dɑːns/','They like to dance at parties.','Họ thích khiêu vũ tại các bữa tiệc.','nhảy múa / khiêu vũ'],
  ['mv-sl-007','/ˌdiː.viːˈdiː/','We rented a DVD to watch at home tonight.','Chúng tôi đã thuê một đĩa DVD để xem ở nhà tối nay.','đĩa DVD'],
  ['mv-sl-008','/ˈiː.meɪl/','I will send you an email with the photos.','Tôi sẽ gửi cho bạn một email kèm theo các bức ảnh.','thư điện tử'],
  ['mv-sl-009','/fɪlm/','That was the best film I have ever seen!','Đó là bộ phim hay nhất mà tôi từng xem!','bộ phim'],
  ['mv-sl-010','/ɡəʊ ˈʃɒp.ɪŋ/','My mother and I go shopping every Saturday.','Mẹ tôi và tôi đi mua sắm mỗi thứ Bảy.','đi mua sắm'],
  ['mv-sl-011','/ɡəʊl/','He scored a fantastic goal in the final minute.','Anh ấy đã ghi một bàn thắng tuyệt vời ở phút cuối.','bàn thắng / khung thành'],
  ['mv-sl-012','/ˈhɒl.ə.deɪ/','We are going to Spain for our summer holiday.','Chúng tôi sẽ đến Tây Ban Nha cho kỳ nghỉ hè.','kỳ nghỉ'],
  ['mv-sl-013','/hɒp/','The rabbit can hop across the grass.','Con thỏ có thể nhảy lò cò qua bãi cỏ.','nhảy lò cò'],
  ['mv-sl-014','/aɪs skeɪts/','She needs a new pair of ice skates for the winter.','Cô ấy cần một đôi giày trượt băng mới cho mùa đông.','giày trượt băng'],
  ['mv-sl-015','/ˈaɪs ˌskeɪ.tɪŋ/','We went ice skating on the frozen lake.','Chúng tôi đã đi trượt băng trên mặt hồ đóng băng.','môn trượt băng'],
  ['mv-sl-016','/kɪk/','He gave the ball a hard kick.','Anh ấy đã đá mạnh vào quả bóng.','cú đá / đá'],
  ['mv-sl-017','/ˈmuː.vi/','Do you want to go out and see a movie?','Bạn có muốn ra ngoài và xem một bộ phim không?','bộ phim'],
  ['mv-sl-018','/net/','The ball went straight into the back of the net.','Quả bóng bay thẳng vào phía sau lưới.','lưới'],
  ['mv-sl-019','/ˈpɑː.ti/','We are having a birthday party for my sister.','Chúng tôi đang tổ chức tiệc sinh nhật cho em gái tôi.','bữa tiệc'],
  ['mv-sl-020','/ˈpleɪ.ər/','He is the best football player in the team.','Anh ấy là cầu thủ bóng đá xuất sắc nhất trong đội.','người chơi / cầu thủ'],
  ['mv-sl-021','/puːl/','Let’s go for a swim in the swimming pool.','Chúng ta hãy đi bơi ở hồ bơi.','hồ bơi'],
  ['mv-sl-022','/ˈpræk.tɪs/','It takes a lot of practice to play the piano well.','Cần rất nhiều sự luyện tập để chơi đàn piano giỏi.','sự luyện tập'],
  ['mv-sl-023','/ˈpræk.tɪs/','You need to practise more if you want to win.','Bạn cần thực hành nhiều hơn nếu muốn chiến thắng.','thực hành / luyện tập'],
  ['mv-sl-024','/ˈprez.ənt/','I bought a present for my friend’s birthday.','Tôi đã mua một món quà cho sinh nhật của bạn tôi.','món quà'],
  ['mv-sl-025','/raɪd/','We went for a ride on our bikes.','Chúng tôi đã đi dạo một vòng bằng xe đạp.','chuyến đi (xe) / cưỡi'],
  ['mv-sl-026','/ˈrəʊ.lə skeɪts/','He put on his roller skates and went to the park.','Anh ấy mang giày trượt patin vào và đi đến công viên.','giày trượt patin'],
  ['mv-sl-027','/ˈrəʊ.lə ˌskeɪ.tɪŋ/','Roller skating is my favourite weekend activity.','Trượt patin là hoạt động cuối tuần yêu thích của tôi.','môn trượt patin'],
  ['mv-sl-028','/seɪl/','We learn how to sail a boat on the lake.','Chúng tôi học cách chèo thuyền trên hồ.','chèo thuyền / ra khơi'],
  ['mv-sl-029','/skɔːr/','What was the final score of the football match?','Tỉ số chung cuộc của trận bóng đá là bao nhiêu?','tỉ số / ghi bàn'],
  ['mv-sl-030','/skeɪt/','The lake is frozen, so we can skate on it.','Hồ đã đóng băng nên chúng ta có thể trượt băng trên đó.','trượt (băng / patin)'],
  ['mv-sl-031','/skɪp/','The girls like to skip rope in the playground.','Các bé gái thích nhảy dây trong sân chơi.','nhảy dây / bỏ qua'],
  ['mv-sl-032','/ˈspɔːts ˌsen.tər/','I go to the sports centre every evening to exercise.','Tôi đến trung tâm thể thao mỗi tối để tập thể dục.','trung tâm thể thao'],
  ['mv-sl-033','/swɪm/','I had a long swim in the sea this morning.','Tôi đã có một chuyến bơi dài trên biển sáng nay.','bơi lội'],
  ['mv-sl-034','/tekst/','I will send you a text message when I arrive.','Tôi sẽ gửi cho bạn một tin nhắn văn bản khi tôi đến.','tin nhắn / nhắn tin'],
  ['mv-sl-035','/taʊəl/','Please dry your hands with this clean towel.','Làm ơn lau khô tay bằng chiếc khăn sạch này.','khăn tắm'],
  ['mv-sl-036','/ˈvɪd.i.əʊ/','We watched a funny video on the internet.','Chúng tôi đã xem một video hài hước trên mạng.','đoạn phim / video'],
  ['mv-sl-037','/wɔːk/','The walk to the beach takes about twenty minutes.','Chuyến đi bộ đến bãi biển mất khoảng hai mươi phút.','cuộc đi bộ'],

  // FLYERS
  ['fl-sl-001','/ˈbæk.pæk/','I packed my clothes in my backpack for the trip.','Tôi nhét quần áo vào ba lô cho chuyến đi.','ba lô'],
  ['fl-sl-002','/kɑːˈtuːn/','My brother watches a cartoon on TV every morning.','Em trai tôi xem phim hoạt hình trên TV mỗi sáng.','phim hoạt hình'],
  ['fl-sl-003','/ˈtʃæn.əl/','Can you change the channel? I don’t like this show.','Bạn có thể chuyển kênh không? Tôi không thích chương trình này.','kênh (TV)'],
  ['fl-sl-004','/tʃes/','Playing chess helps you think more clearly.','Chơi cờ vua giúp bạn suy nghĩ rõ ràng hơn.','cờ vua'],
  ['fl-sl-005','/kəˈlekt/','Some people like to collect stamps or old coins.','Vài người thích sưu tầm tem hoặc đồng xu cổ.','sưu tầm'],
  ['fl-sl-006','/ˈkɒn.sət/','We went to a rock concert and it was very loud.','Chúng tôi đã đến một buổi hòa nhạc rock và nó rất ồn.','buổi hòa nhạc'],
  ['fl-sl-007','/ˈdaɪə.ri/','She writes in her diary every night before bed.','Cô ấy viết nhật ký mỗi tối trước khi ngủ.','nhật ký'],
  ['fl-sl-008','/drʌm/','He beats the drum very loudly in the band.','Anh ấy đánh trống rất to trong ban nhạc.','cái trống'],
  ['fl-sl-009','/ˈfes.tɪ.vəl/','There is a big music festival in our town every summer.','Có một lễ hội âm nhạc lớn ở thị trấn chúng tôi vào mỗi mùa hè.','lễ hội'],
  ['fl-sl-010','/ˈflæʃ.laɪt/','We need a flashlight because it is very dark outside.','Chúng ta cần đèn pin vì bên ngoài rất tối.','đèn pin'],
  ['fl-sl-011','/ɡɒlf/','My grandfather plays golf with his friends on Sundays.','Ông tôi chơi gôn với bạn bè vào các ngày Chủ nhật.','môn đánh gôn'],
  ['fl-sl-012','/həʊˈtel/','We stayed in a lovely hotel near the beach.','Chúng tôi đã ở trong một khách sạn đáng yêu gần bãi biển.','khách sạn'],
  ['fl-sl-013','/ˈɪn.strə.mənt/','Which musical instrument would you like to learn to play?','Bạn muốn học chơi nhạc cụ nào?','nhạc cụ'],
  ['fl-sl-014','/ˌɪn.vɪˈteɪ.ʃən/','I received an invitation to her birthday party.','Tôi đã nhận được lời mời đến dự tiệc sinh nhật của cô ấy.','lời mời'],
  ['fl-sl-015','/dʒɔɪn/','Do you want to join our football team?','Bạn có muốn tham gia đội bóng đá của chúng tôi không?','tham gia'],
  ['fl-sl-016','/ˌmæɡ.əˈziːn/','I bought a fashion magazine to read on the train.','Tôi đã mua một tạp chí thời trang để đọc trên tàu.','tạp chí'],
  ['fl-sl-017','/mætʃ/','We watched a great football match on TV last night.','Chúng tôi đã xem một trận đấu bóng đá tuyệt hay trên TV tối qua.','trận đấu'],
  ['fl-sl-018','/miːt/','Let’s meet at the park at three o’clock.','Hãy gặp nhau ở công viên lúc ba giờ nhé.','gặp gỡ'],
  ['fl-sl-019','/ˈmem.bər/','He is a member of the school swimming club.','Anh ấy là thành viên của câu lạc bộ bơi lội trường.','thành viên'],
  ['fl-sl-020','/ˈɒn.laɪn/','I usually play games online with my friends.','Tôi thường chơi game trực tuyến với bạn bè.','trực tuyến'],
  ['fl-sl-021','/ˈpɒp ˌmjuː.zɪk/','My sister loves listening to Korean pop music.','Chị gái tôi rất thích nghe nhạc pop Hàn Quốc.','nhạc pop'],
  ['fl-sl-022','/praɪz/','She won first prize in the singing competition.','Cô ấy đã giành giải nhất trong cuộc thi hát.','giải thưởng'],
  ['fl-sl-023','/ˈprəʊ.ɡræm/','What is your favourite television programme?','Chương trình truyền hình yêu thích của bạn là gì?','chương trình'],
  ['fl-sl-024','/ˈpʌz.əl/','We spent the whole afternoon doing a jigsaw puzzle.','Chúng tôi đã dành trọn buổi chiều để xếp hình.','câu đố / trò xếp hình'],
  ['fl-sl-025','/ˈpɪr.ə.mɪd/','We saw the great pyramid when we visited Egypt.','Chúng tôi đã thấy kim tự tháp lớn khi đến thăm Ai Cập.','kim tự tháp'],
  ['fl-sl-026','/kwɪz/','The teacher gave us a quick vocabulary quiz today.','Hôm nay giáo viên đã cho chúng tôi làm một bài kiểm tra từ vựng nhanh.','câu đố / bài kiểm tra'],
  ['fl-sl-027','/reɪs/','Who do you think will win the running race?','Bạn nghĩ ai sẽ thắng cuộc đua chạy?','cuộc đua'],
  ['fl-sl-028','/ˈrɒk ˌmjuː.zɪk/','My dad used to play rock music in a band.','Bố tôi từng chơi nhạc rock trong một ban nhạc.','nhạc rock'],
  ['fl-sl-029','/ˈrʌk.sæk/','He put his lunch and books in his rucksack.','Anh ấy để bữa trưa và sách vở vào trong chiếc ba lô.','ba lô'],
  ['fl-sl-030','/skɔːr/','He needs to score one more point to win the game.','Anh ấy cần ghi thêm một điểm nữa để thắng trò chơi.','ghi điểm'],
  ['fl-sl-031','/skiː/','They go to the mountains to ski every winter.','Họ đến vùng núi để trượt tuyết mỗi mùa đông.','trượt tuyết'],
  ['fl-sl-032','/sledʒ/','The children pulled the sledge up the snowy hill.','Bọn trẻ kéo xe trượt tuyết lên ngọn đồi đầy tuyết.','xe trượt tuyết'],
  ['fl-sl-033','/ˈsnəʊ.bɔːl/','He threw a snowball at his brother.','Cậu ấy ném một quả bóng tuyết vào anh trai mình.','bóng tuyết'],
  ['fl-sl-034','/ˈsnəʊ.bɔːd/','She bought a new snowboard for her winter trip.','Cô ấy đã mua một tấm ván trượt tuyết mới cho chuyến đi mùa đông.','ván trượt tuyết'],
  ['fl-sl-035','/ˈsnəʊˌbɔː.dɪŋ/','Snowboarding is harder than skiing for beginners.','Trượt ván trên tuyết thì khó hơn trượt tuyết bằng gậy đối với người mới.','môn trượt ván tuyết'],
  ['fl-sl-036','/ˈsnəʊ.mæn/','We built a big snowman in the garden.','Chúng tôi đã đắp một người tuyết lớn trong vườn.','người tuyết'],
  ['fl-sl-037','/steɪdʒ/','The actors walked onto the stage to start the play.','Các diễn viên bước lên sân khấu để bắt đầu vở kịch.','sân khấu'],
  ['fl-sl-038','/ˈsuːt.keɪs/','Pack your suitcase tonight so we can leave early.','Hãy sắp xếp vali tối nay để chúng ta có thể đi sớm.','vali'],
  ['fl-sl-039','/swɪŋ/','The little girl is playing on the swing in the park.','Bé gái đang chơi xích đu trong công viên.','xích đu'],
  ['fl-sl-040','/tiːm/','Our basketball team won the championship this year.','Đội bóng rổ của chúng tôi đã giành chức vô địch năm nay.','đội'],
  ['fl-sl-041','/tent/','We slept in a tent when we went camping.','Chúng tôi đã ngủ trong lều khi đi cắm trại.','cái lều'],
  ['fl-sl-042','/tɔːtʃ/','Use a torch to see in the dark outside.','Hãy dùng đèn pin để nhìn trong bóng tối bên ngoài.','đèn pin'],
  ['fl-sl-043','/tʃuːn/','She hummed a happy tune while she was working.','Cô ấy ngân nga một giai điệu vui vẻ trong lúc làm việc.','giai điệu'],
  ['fl-sl-044','/taɪər/','My bicycle has a flat tyre, so I cannot ride it.','Xe đạp của tôi bị xẹp lốp nên tôi không thể đi được.','lốp xe'],
  ['fl-sl-045','/ʌmˈbrel.ə/','Take an umbrella with you because it might rain.','Hãy mang theo ô vì trời có thể mưa.','cái ô / cái dù'],
  ['fl-sl-046','/ˌvaɪəˈlɪn/','She has been learning to play the violin for three years.','Cô ấy đã học chơi vĩ cầm được ba năm rồi.','đàn vĩ cầm / vi-ô-lông'],
  ['fl-sl-047','/ˈvɒl.i.bɔːl/','We played volleyball on the beach all afternoon.','Chúng tôi đã chơi bóng chuyền trên bãi biển cả buổi chiều.','bóng chuyền'],
  ['fl-sl-048','/ˈwɪn.ər/','The winner of the race got a gold medal.','Người chiến thắng cuộc đua đã nhận được huy chương vàng.','người chiến thắng']
];

let sql = `-- 0022a: Fix ipa+examples+translations — sports_leisure (141 words)\n-- Generated: ${new Date().toISOString()}\n\n`;
for(const [id, ipa, en, vi, trans] of D) {
  sql += `UPDATE vocabulary_bank SET ipa='${ipa.replace(/'/g, "''")}', example_en='${en.replace(/'/g, "''")}', example_vi='${vi.replace(/'/g, "''")}', translation_vi='${trans.replace(/'/g, "''")}' WHERE id='${id}';\n`;
}
sql += `\n-- Total: ${D.length} rows\n`;

const out = path.join(__dirname, 'src/worker/migrations/0022a_fix_sports_leisure.sql');
fs.writeFileSync(out, sql);
console.log(`✅ ${out}\n📊 ${D.length} rows`);
