const fs=require('fs'),path=require('path');
const D=[
['st-sc-001','/ˈæl.fə.bet/','The teacher wrote the alphabet on the board.','Giáo viên viết bảng chữ cái lên bảng.'],
['st-sc-002','/ˈɑːn.sə/','Write your answer in the box below the question.','Viết câu trả lời của bạn vào ô bên dưới câu hỏi.'],
['st-sc-003','/ɑːsk/','She asked the teacher a question about the homework.','Cô ấy hỏi giáo viên một câu hỏi về bài tập về nhà.'],
['st-sc-004','/bɔːd/','The teacher wrote the new words on the board.','Giáo viên viết những từ mới lên bảng.'],
['st-sc-005','/bʊk/','Read pages ten to fifteen in your textbook tonight.','Đọc trang mười đến mười lăm trong sách giáo khoa tối nay.'],
['st-sc-006','/ˈbʊk.keɪs/','Put the dictionaries back on the bookcase after you use them.','Đặt lại từ điển vào tủ sách sau khi dùng xong.'],
['st-sc-007','/klɑːs/','Our class has twenty-four students this year.','Lớp học của chúng tôi có hai mươi bốn học sinh năm nay.'],
['st-sc-008','/ˈklɑːs.ruːm/','The classroom has large windows and lots of natural light.','Phòng học có những cửa sổ lớn và nhiều ánh sáng tự nhiên.'],
['st-sc-009','/kləʊz/','Close your books and listen carefully to the teacher.','Đóng sách lại và lắng nghe giáo viên cẩn thận.'],
['st-sc-010','/ˈkʌl.ə/','What colour is your favourite pen?','Màu bút yêu thích của bạn là gì?'],
['st-sc-011','/kəmˈpjuː.tə/','We use the school computers to do research online.','Chúng tôi dùng máy tính của trường để nghiên cứu trực tuyến.'],
['st-sc-012','/kəˈrekt/','All of your answers are correct — well done!','Tất cả câu trả lời của bạn đều đúng — giỏi lắm!'],
['st-sc-013','/ˈkreɪ.ɒn/','She drew a rainbow using coloured crayons.','Cô ấy vẽ một cầu vồng bằng bút màu sáp.'],
['st-sc-014','/krɒs/','Put a cross next to the wrong answer.','Đặt dấu chéo bên cạnh câu trả lời sai.'],
['st-sc-015','/ˈkʌb.əd/','The art supplies are kept in the cupboard at the back of the room.','Dụng cụ mỹ thuật được giữ trong tủ ở phía sau phòng.'],
['st-sc-016','/desk/','Sit down at your desk and open your exercise books.','Hãy ngồi xuống bàn học và mở vở bài tập ra.'],
['st-sc-017','/dɔː/','Could someone open the door? It is very hot in here.','Có ai mở cửa ra không? Trong này rất nóng.'],
['st-sc-018','/drɔː/','Draw a picture of your favourite animal in the space below.','Hãy vẽ một bức tranh về con vật yêu thích của bạn vào chỗ trống bên dưới.'],
['st-sc-019','/ˈɪŋ.ɡlɪʃ/','We have English class every morning from eight to nine.','Chúng tôi có lớp tiếng Anh mỗi sáng từ tám đến chín giờ.'],
['st-sc-020','/ɪˈreɪ.zə/','Use an eraser to rub out the mistake.','Dùng cục tẩy để xóa lỗi sai.'],
['st-sc-021','/ɪɡˈzɑːm.pəl/','Look at the example before you do the exercise.','Nhìn vào ví dụ trước khi bạn làm bài tập.'],
['st-sc-022','/faɪnd/','Can you find the word on page thirty-two?','Bạn có thể tìm thấy từ đó ở trang ba mươi hai không?'],
['st-sc-023','/flɔː/','The teacher asked us to sit on the floor in a circle.','Giáo viên yêu cầu chúng tôi ngồi trên sàn thành một vòng tròn.'],
['st-sc-024','/ˈkiː.bɔːd/','She types very fast on the computer keyboard.','Cô ấy gõ phím rất nhanh trên bàn phím máy tính.'],
['st-sc-025','/lɜːn/','We learn ten new vocabulary words every week.','Chúng tôi học mười từ vựng mới mỗi tuần.'],
['st-sc-026','/ˈles.ən/','We have a science lesson every Thursday afternoon.','Chúng tôi có tiết học khoa học mỗi chiều thứ Năm.'],
['st-sc-027','/ˈlet.ə/','The word starts with the letter G.','Từ đó bắt đầu bằng chữ cái G.'],
['st-sc-028','/laɪn/','Draw a straight line under each sentence.','Vẽ một đường thẳng dưới mỗi câu.'],
['st-sc-029','/ˈlɪs.ən/','Listen carefully and then repeat what you hear.','Hãy lắng nghe cẩn thận rồi nhắc lại những gì bạn nghe thấy.'],
['st-sc-030','/lʊk/','Look at the picture and describe what you can see.','Hãy nhìn vào bức tranh và mô tả những gì bạn thấy.'],
['st-sc-031','/maʊs/','Move the mouse to the right and click on the icon.','Di chuyển chuột sang phải và nhấp vào biểu tượng.'],
['st-sc-032','/ˈmjuː.zɪk/','We have music lessons on Wednesday mornings.','Chúng tôi có tiết học âm nhạc vào sáng thứ Tư.'],
['st-sc-033','/ˈnʌm.bə/','Write the correct number in each box.','Viết số đúng vào mỗi ô.'],
['st-sc-034','/ˈəʊ.pən/','Open your workbooks to page forty-five.','Mở vở bài tập ra trang bốn mươi lăm.'],
['st-sc-035','/peɪdʒ/','Turn to page twelve and read the first paragraph.','Lật đến trang mười hai và đọc đoạn văn đầu tiên.'],
['st-sc-036','/ˈpeɪnt.ɪŋ/','There is a beautiful painting of the seaside on the classroom wall.','Có một bức tranh sơn đẹp về bãi biển trên tường phòng học.'],
['st-sc-037','/ˈpeɪ.pə/','Tear out a piece of paper and write your name at the top.','Xé một tờ giấy ra và viết tên bạn ở trên cùng.'],
['st-sc-038','/pɑːt/','Read the first part of the story for homework.','Đọc phần đầu của câu chuyện làm bài tập về nhà.'],
['st-sc-039','/pen/','Please write in pen, not pencil, for the test.','Hãy viết bằng bút bi, không dùng bút chì, trong bài kiểm tra.'],
['st-sc-040','/ˈpen.səl/','She sharpened her pencil before starting the drawing.','Cô ấy gọt bút chì trước khi bắt đầu vẽ.'],
['st-sc-041','/ˈpɪk.tʃə/','Look at the picture and answer the questions below.','Hãy nhìn vào bức tranh và trả lời các câu hỏi bên dưới.'],
['st-sc-042','/ˈpleɪ.ɡraʊnd/','The children run around the playground during their break.','Bọn trẻ chạy vòng quanh sân chơi trong giờ giải lao.'],
['st-sc-043','/ˈpəʊ.stə/','They made a poster about endangered animals for the science fair.','Họ làm một tờ áp phích về các loài động vật có nguy cơ tuyệt chủng cho hội chợ khoa học.'],
['st-sc-044','/ˈkwes.tʃən/','Ask the teacher if you do not understand the question.','Hỏi giáo viên nếu bạn không hiểu câu hỏi.'],
['st-sc-045','/riːd/','Read the passage carefully before answering the questions.','Đọc đoạn văn cẩn thận trước khi trả lời câu hỏi.'],
['st-sc-046','/raɪt/','Tick the right answer and cross out the wrong ones.','Đánh dấu câu trả lời đúng và gạch bỏ những câu sai.'],
['st-sc-047','/ˈrʌb.ə/','He used a rubber to erase the pencil marks.','Anh ấy dùng cục tẩy để xóa các nét bút chì.'],
['st-sc-048','/ˈruː.lə/','Use a ruler to draw a straight line.','Dùng thước kẻ để vẽ một đường thẳng.'],
['st-sc-049','/skuːl/','School starts at half past eight every morning.','Trường bắt đầu lúc tám giờ rưỡi mỗi sáng.'],
['st-sc-050','/ˈsen.təns/','Write a sentence using each of the new words.','Hãy viết một câu sử dụng mỗi từ mới.'],
['st-sc-051','/sɪt/','Sit down quietly and wait for the lesson to begin.','Ngồi xuống yên lặng và chờ tiết học bắt đầu.'],
['st-sc-052','/spel/','Can you spell your surname for me, please?','Bạn có thể đánh vần họ của bạn cho tôi không?'],
['st-sc-053','/stænd/','Please stand up when the headteacher enters the room.','Hãy đứng dậy khi hiệu trưởng bước vào phòng.'],
['st-sc-054','/ˈstɔː.ri/','The teacher told us a funny story to start the lesson.','Giáo viên kể cho chúng tôi một câu chuyện vui để bắt đầu tiết học.'],
['st-sc-055','/ˈtiː.tʃə/','Our maths teacher explains everything very clearly.','Giáo viên toán của chúng tôi giải thích mọi thứ rất rõ ràng.'],
['st-sc-056','/tel/','Tell me what happened at school today.','Kể cho tôi nghe chuyện gì đã xảy ra ở trường hôm nay.'],
['st-sc-057','/tɪk/','Put a tick next to the correct answer.','Đặt dấu tích bên cạnh câu trả lời đúng.'],
['st-sc-058','/ˌʌn.dəˈstænd/','Do you understand the instructions for this exercise?','Bạn có hiểu hướng dẫn cho bài tập này không?'],
['st-sc-059','/wɔːl/','There are maps and posters on every wall of the classroom.','Có bản đồ và áp phích trên mọi bức tường của phòng học.'],
['st-sc-060','/ˈwɪn.dəʊ/','She sat by the window and looked out at the garden.','Cô ấy ngồi bên cửa sổ và nhìn ra khu vườn.'],
['st-sc-061','/wɜːd/','Look up the meaning of this word in your dictionary.','Tra nghĩa của từ này trong từ điển của bạn.'],
['st-sc-062','/raɪt/','Write your name and the date at the top of the page.','Viết tên và ngày tháng lên đầu trang giấy.'],
['mv-sc-001','/breɪk/','We play outside during the morning break.','Chúng tôi chơi ngoài trời trong giờ giải lao buổi sáng.'],
['mv-sc-002','/ˈhəʊm.wɜːk/','She finished all her homework before dinner.','Cô ấy hoàn thành toàn bộ bài tập về nhà trước bữa tối.'],
['mv-sc-003','/mɪˈsteɪk/','Everyone makes mistakes when they are learning something new.','Ai cũng mắc lỗi khi đang học điều gì đó mới.'],
['mv-sc-004','/tiːtʃ/','She wants to teach English to young children when she grows up.','Cô ấy muốn dạy tiếng Anh cho trẻ nhỏ khi lớn lên.'],
['mv-sc-005','/tekst/','Read the text on page eighteen and answer the questions.','Đọc văn bản ở trang mười tám và trả lời các câu hỏi.'],
['mv-sc-006','/ˈweb.saɪt/','Check the school website for information about the trip.','Kiểm tra trang web của trường để biết thông tin về chuyến đi.'],
['fl-sc-001','/ɑːt/','She is very good at art and loves painting landscapes.','Cô ấy rất giỏi mỹ thuật và thích vẽ phong cảnh.'],
['fl-sc-002','/ˈbæk.pæk/','He packed his backpack the night before the school trip.','Anh ấy đóng gói ba lô vào tối hôm trước chuyến đi học.'],
['fl-sc-003','/bɪn/','Throw your rubbish in the bin, not on the floor.','Hãy bỏ rác vào thùng rác, không bỏ xuống sàn.'],
['fl-sc-004','/klʌb/','She is the president of the school debating club.','Cô ấy là chủ tịch câu lạc bộ tranh luận của trường.'],
['fl-sc-005','/ˈkɒl.ɪdʒ/','He is studying business at a college in the city.','Anh ấy đang học kinh doanh tại một trường cao đẳng trong thành phố.'],
['fl-sc-006','/ˌkɒm.pɪˈtɪʃ.ən/','She won first place in the national spelling competition.','Cô ấy giành giải nhất trong cuộc thi đánh vần toàn quốc.'],
['fl-sc-007','/ˈdɪk.ʃən.ər.i/','Use your dictionary to check the spelling of difficult words.','Dùng từ điển để kiểm tra chính tả của những từ khó.'],
['fl-sc-008','/flæɡ/','Each country has its own national flag with different colours.','Mỗi quốc gia có lá cờ riêng với màu sắc khác nhau.'],
['fl-sc-009','/dʒiˈɒɡ.rə.fi/','We are studying the geography of South-East Asia this term.','Chúng tôi đang học địa lý của Đông Nam Á kỳ này.'],
['fl-sc-010','/ɡluː/','Use glue to stick the pictures onto your poster.','Dùng keo để dán tranh lên áp phích của bạn.'],
['fl-sc-011','/ɡruːp/','Work in groups of four to complete the project.','Làm việc theo nhóm bốn người để hoàn thành dự án.'],
['fl-sc-012','/dʒɪm/','We have gym class every Tuesday and do gymnastics.','Chúng tôi có tiết thể dục mỗi thứ Ba và tập thể dục dụng cụ.'],
['fl-sc-013','/ˈhɪs.tər.i/','In history class we are learning about the Second World War.','Trong lớp lịch sử chúng tôi đang học về Chiến tranh Thế giới thứ Hai.'],
['fl-sc-014','/ˈlæŋ.ɡwɪdʒ/','She speaks three languages fluently: French, Spanish and English.','Cô ấy nói thành thạo ba ngôn ngữ: Pháp, Tây Ban Nha và tiếng Anh.'],
['fl-sc-015','/mæθs/','Maths is my favourite subject because I love solving problems.','Toán là môn học yêu thích của tôi vì tôi thích giải các bài toán.'],
['fl-sc-016','/ˈɒn.laɪn/','The school offers many online lessons for students at home.','Trường cung cấp nhiều bài học trực tuyến cho học sinh ở nhà.'],
['fl-sc-017','/ˈprɒdʒ.ekt/','Our science project is about renewable energy sources.','Dự án khoa học của chúng tôi nói về các nguồn năng lượng tái tạo.'],
['fl-sc-018','/ˈrʌk.sæk/','She carried all her school books in her rucksack.','Cô ấy mang tất cả sách vở trong ba lô đến trường.'],
['fl-sc-019','/ˈsaɪ.əns/','In science we are doing experiments about light and colour.','Trong tiết khoa học chúng tôi đang làm thí nghiệm về ánh sáng và màu sắc.'],
['fl-sc-020','/ˈsɪz.əz/','Be careful when you use scissors — they are very sharp.','Hãy cẩn thận khi dùng kéo — chúng rất sắc.'],
['fl-sc-021','/skriːn/','The teacher showed a video on the large screen at the front.','Giáo viên chiếu một đoạn video trên màn hình lớn ở phía trước.'],
['fl-sc-022','/ʃelf/','Return all reference books to the shelf when you finish.','Hãy trả lại tất cả sách tham khảo vào kệ khi bạn xong.'],
['fl-sc-023','/ˈstjuː.dənt/','Every student in the class passed the end-of-year exam.','Mỗi học sinh trong lớp đều vượt qua kỳ thi cuối năm.'],
['fl-sc-024','/ˈstʌd.i/','She needs to study hard to prepare for the entrance exam.','Cô ấy cần học chăm chỉ để chuẩn bị cho kỳ thi đầu vào.'],
['fl-sc-025','/ˈsʌb.dʒɪkt/','Which subject do you enjoy most: art or music?','Bạn thích môn học nào nhất: mỹ thuật hay âm nhạc?'],
['fl-sc-026','/ˈtaɪm.teɪ.bəl/','Check the timetable to see when your next lesson is.','Kiểm tra thời khóa biểu để xem tiết học tiếp theo của bạn khi nào.'],
['fl-sc-027','/ˌjuː.nɪˈvɜː.sɪ.ti/','She got a scholarship to study medicine at university.','Cô ấy nhận được học bổng để học y khoa tại trường đại học.'],
];
let sql=`-- 0021c: Fix ipa+examples — school (95 words)\n-- Generated: ${new Date().toISOString()}\n\n`;
for(const[id,ipa,en,vi]of D){
  sql+=`UPDATE vocabulary_bank SET ipa='${ipa.replace(/'/g,"''")}', example_en='${en.replace(/'/g,"''")}', example_vi='${vi.replace(/'/g,"''")}' WHERE id='${id}';\n`;
}
sql+=`\n-- Total: ${D.length} rows\n`;
const out=path.join(__dirname,'src/worker/migrations/0021c_fix_ipa_examples_school.sql');
fs.writeFileSync(out,sql);
console.log(`✅ ${out}\n📊 ${D.length} rows`);
