#!/usr/bin/env node
const fs = require('fs'), path = require('path');

const D = [
  // WEATHER
  ['st-we-001','/sʌn/','The sun is shining brightly today.','Mặt trời đang chiếu sáng rực rỡ hôm nay.','mặt trời'],
  ['mv-we-001','/klaʊd/','There is a big grey cloud in the sky.','Có một đám mây xám lớn trên bầu trời.','đám mây'],
  ['mv-we-002','/ˈklaʊ.di/','It is a cloudy day, so it might rain.','Trời nhiều mây, vì vậy có thể sẽ mưa.','nhiều mây'],
  ['mv-we-003','/aɪs/','Would you like some ice in your drink?','Bạn có muốn thêm đá vào đồ uống không?','đá (nước đá)'],
  ['mv-we-004','/reɪn/','We stayed inside because of the heavy rain.','Chúng tôi ở trong nhà vì trời mưa to.','cơn mưa / mưa'],
  ['mv-we-005','/ˈreɪn.bəʊ/','We saw a beautiful rainbow after the rain stopped.','Chúng tôi thấy một cầu vồng đẹp sau khi cơn mưa tạnh.','cầu vồng'],
  ['mv-we-006','/skaɪ/','Look at the beautiful blue sky!','Hãy nhìn bầu trời xanh đẹp đẽ kia!','bầu trời'],
  ['mv-we-007','/snəʊ/','The children love playing in the snow.','Bọn trẻ thích chơi đùa trong tuyết.','tuyết'],
  ['mv-we-008','/ˈsʌn.i/','It is a sunny morning, perfect for a walk.','Đó là một buổi sáng nắng ráo, hoàn hảo để đi dạo.','có nắng'],
  ['mv-we-009','/ˈweð.ər/','The weather is very warm and pleasant today.','Thời tiết hôm nay rất ấm áp và dễ chịu.','thời tiết'],
  ['mv-we-010','/wɪnd/','The strong wind blew my hat away.','Cơn gió mạnh đã thổi bay chiếc mũ của tôi.','cơn gió'],
  ['mv-we-011','/ˈwɪn.di/','It is too windy to use an umbrella today.','Hôm nay trời quá nhiều gió để dùng ô.','có gió'],
  ['fl-we-001','/fɒɡ/','The thick fog made it difficult to see the road.','Màn sương mù dày đặc khiến việc nhìn đường trở nên khó khăn.','sương mù'],
  ['fl-we-002','/ˈfɒɡ.i/','It is a cold and foggy morning.','Đó là một buổi sáng lạnh và đầy sương mù.','có sương mù'],
  ['fl-we-003','/stɔːm/','We stayed inside during the thunderstorm.','Chúng tôi ở trong nhà suốt lúc có bão tuyết.','cơn bão'],

  // WORK
  ['mv-wk-001','/ˈsɜː.kəs/','We saw acrobats and clowns at the circus.','Chúng tôi đã thấy những người nhào lộn và những chú hề ở rạp xiếc.','rạp xiếc'],
  ['mv-wk-002','/klaʊn/','The clown made everyone laugh with his funny tricks.','Chú hề làm mọi người cười bằng những trò đùa hài hước của mình.','chú hề'],
  ['mv-wk-003','/kʊk/','My dad is a great cook and makes delicious meals.','Bố tôi là một đầu bếp tuyệt vời và làm ra những bữa ăn ngon.','đầu bếp'],
  ['mv-wk-004','/ˈden.tɪst/','You should visit the dentist to check your teeth.','Bạn nên đến thăm nha sĩ để kiểm tra răng của mình.','nha sĩ'],
  ['mv-wk-005','/ˈdɒk.tər/','The doctor gave me some medicine for my cold.','Bác sĩ đã cho tôi một ít thuốc để trị cảm lạnh.','bác sĩ'],
  ['mv-wk-006','/ˈdraɪ.vər/','The taxi driver knows all the streets in the city.','Bác tài xế taxi biết tất cả các con đường trong thành phố.','tài xế'],
  ['mv-wk-007','/ˈfɑː.mər/','The farmer wakes up early to feed the animals.','Người nông dân thức dậy sớm để cho động vật ăn.','nông dân'],
  ['mv-wk-008','/ˈfɪlm ˌstɑːr/','She wants to become a famous film star in Hollywood.','Cô ấy muốn trở thành một ngôi sao điện ảnh nổi tiếng ở Hollywood.','ngôi sao điện ảnh'],
  ['mv-wk-009','/ˈhɒs.pɪ.təl/','The ambulance took the injured man to the hospital.','Xe cứu thương đã đưa người đàn ông bị thương đến bệnh viện.','bệnh viện'],
  ['mv-wk-010','/nɜːs/','The nurse checked my temperature and gave me a smile.','Cô y tá kiểm tra nhiệt độ của tôi và mỉm cười với tôi.','y tá'],
  ['mv-wk-011','/ˈpaɪə.rət/','The pirate searched for hidden treasure on the island.','Tên cướp biển đã tìm kiếm kho báu bị giấu trên hòn đảo.','cướp biển'],
  ['mv-wk-012','/ˈpɒp ˌstɑːr/','The pop star sang her new song at the concert.','Ngôi sao nhạc pop đã hát bài hát mới của mình tại buổi hòa nhạc.','ngôi sao nhạc pop'],
  ['mv-wk-013','/ˈtiː.tʃər/','Our math teacher is very kind and helpful.','Giáo viên toán của chúng tôi rất tốt bụng và hay giúp đỡ.','giáo viên'],
  ['mv-wk-014','/wɜːk/','My father goes to work by train every morning.','Bố tôi đi làm bằng xe lửa mỗi sáng.','công việc / làm việc'],
  ['fl-wk-001','/ˈæk.tər/','The actor won an award for his role in the movie.','Nam diễn viên đã giành được một giải thưởng cho vai diễn của mình trong bộ phim.','diễn viên'],
  ['fl-wk-002','/ˈeə.pɔːt/','We arrived at the airport two hours before our flight.','Chúng tôi đã đến sân bay hai giờ trước chuyến bay của mình.','sân bay'],
  ['fl-wk-003','/ˈæm.bjə.ləns/','The paramedics rushed to the accident in an ambulance.','Các nhân viên y tế đã lao đến vụ tai nạn trên một chiếc xe cứu thương.','xe cứu thương'],
  ['fl-wk-004','/ˈɑː.tɪst/','The artist painted a beautiful portrait of the queen.','Người họa sĩ đã vẽ một bức chân dung tuyệt đẹp của nữ hoàng.','họa sĩ'],
  ['fl-wk-005','/ˈæs.trə.nɔːt/','The astronaut travelled to the International Space Station.','Phi hành gia đã du hành đến Trạm Vũ trụ Quốc tế.','phi hành gia'],
  ['fl-wk-006','/ˈbɪz.nɪs/','He owns a successful restaurant business.','Anh ấy sở hữu một doanh nghiệp nhà hàng thành công.','kinh doanh / doanh nghiệp'],
  ['fl-wk-007','/ˈbɪz.nɪs.mæn/','The businessman travelled to London for an important meeting.','Nam doanh nhân đã đến London cho một cuộc họp quan trọng.','nam doanh nhân'],
  ['fl-wk-008','/ˈbɪz.nɪsˌwʊm.ən/','The businesswoman presented her new project to the team.','Nữ doanh nhân đã trình bày dự án mới của mình cho nhóm.','nữ doanh nhân'],
  ['fl-wk-009','/dɪˈzaɪ.nər/','She is a famous fashion designer who creates beautiful dresses.','Cô ấy là một nhà thiết kế thời trang nổi tiếng người tạo ra những chiếc váy đẹp.','nhà thiết kế'],
  ['fl-wk-010','/ˌen.dʒɪˈnɪər/','The engineer designed a new bridge for the city.','Kỹ sư đã thiết kế một cây cầu mới cho thành phố.','kỹ sư'],
  ['fl-wk-011','/ˈfæk.tər.i/','Many people in the town work at the car factory.','Nhiều người trong thị trấn làm việc tại nhà máy sản xuất ô tô.','nhà máy'],
  ['fl-wk-012','/ˈfaɪər ˌen.dʒɪn/','The loud siren of the fire engine woke everyone up.','Tiếng còi lớn của xe cứu hỏa đã đánh thức mọi người.','xe cứu hỏa'],
  ['fl-wk-013','/ˈfaɪəˌfaɪ.tər/','The brave fire fighter rescued a cat from the burning building.','Người lính cứu hỏa dũng cảm đã cứu một con mèo khỏi tòa nhà đang cháy.','lính cứu hỏa'],
  ['fl-wk-014','/dʒɒb/','Finding a good job can sometimes be difficult.','Việc tìm được một công việc tốt đôi khi có thể khó khăn.','công việc'],
  ['fl-wk-015','/ˈdʒɜː.nə.lɪst/','The journalist wrote an interesting article for the newspaper.','Nhà báo đã viết một bài báo thú vị cho tờ báo.','nhà báo'],
  ['fl-wk-016','/ˈmæn.ɪ.dʒər/','The shop manager organized a meeting with all the staff.','Người quản lý cửa hàng đã tổ chức một cuộc họp với toàn bộ nhân viên.','người quản lý'],
  ['fl-wk-017','/mɪˈkæn.ɪk/','The mechanic fixed the broken engine of our car.','Người thợ máy đã sửa xong động cơ bị hỏng của chiếc xe chúng tôi.','thợ máy'],
  ['fl-wk-018','/ˈmiː.tɪŋ/','We have an important team meeting this afternoon.','Chúng tôi có một cuộc họp nhóm quan trọng vào chiều nay.','cuộc họp'],
  ['fl-wk-019','/njuːz/','I watch the evening news to learn what is happening in the world.','Tôi xem tin tức buổi tối để biết những gì đang xảy ra trên thế giới.','tin tức'],
  ['fl-wk-020','/ˈnjuːzˌpeɪ.pər/','My grandfather reads the newspaper every morning.','Ông tôi đọc báo mỗi buổi sáng.','tờ báo'],
  ['fl-wk-021','/ˈɒf.ɪs/','She works in a large office building in the city centre.','Cô ấy làm việc trong một tòa nhà văn phòng lớn ở trung tâm thành phố.','văn phòng'],
  ['fl-wk-022','/fəˈtɒɡ.rə.fər/','The professional photographer took photos at the wedding.','Nhiếp ảnh gia chuyên nghiệp đã chụp những bức ảnh tại đám cưới.','nhiếp ảnh gia'],
  ['fl-wk-023','/ˈpaɪ.lət/','The pilot landed the airplane safely on the runway.','Phi công đã hạ cánh máy bay an toàn trên đường băng.','phi công'],
  ['fl-wk-024','/pəˈliːs ˌɒf.ɪ.sər/','The police officer helped the lost child find his parents.','Viên sĩ quan cảnh sát đã giúp đứa trẻ đi lạc tìm thấy cha mẹ mình.','sĩ quan cảnh sát'],
  ['fl-wk-025','/pəˈliːs ˌsteɪ.ʃən/','If you lose your wallet, you should report it to the police station.','Nếu bạn bị mất ví, bạn nên báo với đồn cảnh sát.','đồn cảnh sát'],
  ['fl-wk-026','/kwiːn/','The queen wore a beautiful crown made of gold and jewels.','Nữ hoàng đội một chiếc vương miện tuyệt đẹp làm bằng vàng và đồ trang sức.','nữ hoàng'],
  ['fl-wk-027','/ˈrɒk.ɪt/','The rocket was launched into space successfully.','Tên lửa đã được phóng vào không gian thành công.','tên lửa'],
  ['fl-wk-028','/ˈsɪŋ.ər/','She is a talented singer with a beautiful voice.','Cô ấy là một ca sĩ tài năng với giọng hát tuyệt vời.','ca sĩ'],
  ['fl-wk-029','/ˈtæk.si/','We took a taxi because we were late for the meeting.','Chúng tôi đã đi taxi vì chúng tôi bị trễ cuộc họp.','xe taxi'],
  ['fl-wk-030','/ˈweɪ.tər/','The waiter brought us the menu and took our order.','Người phục vụ nam mang cho chúng tôi thực đơn và nhận món chúng tôi gọi.','người phục vụ (nam)'],

  // WORLD
  ['st-wa-001','/biːtʃ/','We built a big sandcastle on the beach.','Chúng tôi đã xây một lâu đài cát lớn trên bãi biển.','bãi biển'],
  ['st-wa-002','/sænd/','The children are playing in the sand.','Bọn trẻ đang chơi trong cát.','cát'],
  ['st-wa-003','/siː/','I love swimming in the sea during summer.','Tôi thích bơi ở biển trong mùa hè.','biển'],
  ['st-wa-004','/ʃel/','I found a beautiful pink shell on the beach.','Tôi đã tìm thấy một vỏ sò màu hồng tuyệt đẹp trên bãi biển.','vỏ sò'],
  ['st-wa-005','/striːt/','Be careful when you cross the busy street.','Hãy cẩn thận khi bạn băng qua con đường đông đúc.','con đường / phố'],
  ['st-wa-006','/sʌn/','The sun provides heat and light for the Earth.','Mặt trời cung cấp nhiệt và ánh sáng cho Trái Đất.','mặt trời'],
  ['st-wa-007','/triː/','There is a big apple tree in our garden.','Có một cây táo lớn trong vườn nhà chúng tôi.','cái cây'],
  ['st-wa-008','/ˈwɔː.tər/','Please give me a glass of cold water.','Vui lòng cho tôi một ly nước lạnh.','nước'],
  ['mv-wa-001','/ˈbɪl.dɪŋ/','That tall building is a bank.','Tòa nhà cao đó là một ngân hàng.','tòa nhà'],
  ['mv-wa-002','/ˈsɪt.i/','London is a very big and busy city.','London là một thành phố rất lớn và nhộn nhịp.','thành phố'],
  ['mv-wa-003','/ˈkʌn.tri/','France is a beautiful country in Europe.','Pháp là một quốc gia xinh đẹp ở châu Âu.','quốc gia / vùng nông thôn'],
  ['mv-wa-004','/ˈkʌn.tri.saɪd/','We went for a walk in the quiet countryside.','Chúng tôi đã đi dạo trong vùng nông thôn yên tĩnh.','vùng nông thôn'],
  ['mv-wa-005','/fiːld/','The cows are eating grass in the field.','Những con bò đang ăn cỏ trên cánh đồng.','cánh đồng'],
  ['mv-wa-006','/ˈfɒr.ɪst/','We went camping in a large pine forest.','Chúng tôi đã đi cắm trại trong một khu rừng thông lớn.','khu rừng'],
  ['mv-wa-007','/ɡrɑːs/','Please do not walk on the grass.','Vui lòng không đi dạo trên cỏ.','cỏ'],
  ['mv-wa-008','/ɡraʊnd/','He dropped his book on the ground.','Cậu ấy đã làm rơi cuốn sách của mình xuống đất.','mặt đất'],
  ['mv-wa-009','/ˈaɪ.lənd/','They spent their holiday on a small tropical island.','Họ đã dành kỳ nghỉ của mình trên một hòn đảo nhiệt đới nhỏ.','hòn đảo'],
  ['mv-wa-010','/leɪk/','We rented a boat to go fishing on the lake.','Chúng tôi thuê một chiếc thuyền để đi câu cá trên hồ.','cái hồ'],
  ['mv-wa-011','/liːf/','A dry autumn leaf fell from the tree.','Một chiếc lá thu khô rụng từ trên cây xuống.','chiếc lá'],
  ['mv-wa-012','/muːn/','The full moon shines brightly at night.','Mặt trăng tròn tỏa sáng rực rỡ vào ban đêm.','mặt trăng'],
  ['mv-wa-013','/ˈmaʊn.tɪn/','We climbed to the top of the highest mountain.','Chúng tôi đã leo lên đỉnh của ngọn núi cao nhất.','ngọn núi'],
  ['mv-wa-014','/plɑːnt/','Don’t forget to water the tomato plant.','Đừng quên tưới nước cho cây cà chua.','cây cối / thực vật'],
  ['mv-wa-015','/ˈrɪv.ər/','The river flows through the middle of the city.','Con sông chảy qua giữa trung tâm thành phố.','dòng sông'],
  ['mv-wa-016','/rəʊd/','We drove down the long, straight road.','Chúng tôi đã lái xe xuống con đường dài và thẳng tắp.','con đường'],
  ['mv-wa-017','/rɒk/','He sat on a large rock to rest.','Anh ấy ngồi trên một tảng đá lớn để nghỉ ngơi.','hòn đá / tảng đá'],
  ['mv-wa-018','/skaɪ/','Look at the stars in the dark night sky.','Hãy nhìn những vì sao trên bầu trời đêm tối.','bầu trời'],
  ['mv-wa-019','/stɑːr/','I saw a shooting star in the sky last night.','Tôi đã thấy một ngôi sao băng trên bầu trời đêm qua.','ngôi sao'],
  ['mv-wa-020','/taʊn/','We live in a small, quiet town near the sea.','Chúng tôi sống ở một thị trấn nhỏ, yên tĩnh gần biển.','thị trấn'],
  ['mv-wa-021','/ˈvɪl.ɪdʒ/','My grandparents live in a traditional farming village.','Ông bà tôi sống ở một ngôi làng nông nghiệp truyền thống.','ngôi làng'],
  ['mv-wa-022','/ˈwɔː.tə.fɔːl/','We hiked to a beautiful waterfall in the forest.','Chúng tôi đã đi bộ đường dài đến một thác nước tuyệt đẹp trong rừng.','thác nước'],
  ['mv-wa-023','/weɪv/','The surfer rode a giant wave to the shore.','Người lướt sóng đã cưỡi một con sóng khổng lồ vào bờ.','con sóng'],
  ['mv-wa-024','/wɜːld/','There are many different countries in the world.','Có rất nhiều quốc gia khác nhau trên thế giới.','thế giới'],
  ['fl-wa-001','/eər/','I opened the window to let some fresh air in.','Tôi đã mở cửa sổ để cho một chút không khí trong lành lùa vào.','không khí'],
  ['fl-wa-002','/brɪdʒ/','We drove over the bridge to cross the river.','Chúng tôi đã lái xe qua cây cầu để vượt sông.','cây cầu'],
  ['fl-wa-003','/ˈkɑː.səl/','The king and queen live in an old stone castle.','Nhà vua và nữ hoàng sống trong một lâu đài đá cổ kính.','lâu đài'],
  ['fl-wa-004','/keɪv/','The explorers found ancient paintings inside the dark cave.','Các nhà thám hiểm đã tìm thấy những bức tranh cổ bên trong hang tối.','hang động'],
  ['fl-wa-005','/ˈdez.ət/','Camels are well-adapted to survive in the hot, dry desert.','Lạc đà rất thích nghi để sinh tồn trong sa mạc nóng và khô hạn.','sa mạc'],
  ['fl-wa-006','/ɜːθ/','The Earth revolves around the Sun.','Trái Đất quay xung quanh Mặt Trời.','Trái Đất'],
  ['fl-wa-007','/ˈen.trəns/','We will meet you at the main entrance of the museum.','Chúng tôi sẽ gặp bạn ở lối vào chính của bảo tàng.','lối vào'],
  ['fl-wa-008','/ɪnˈvaɪ.rən.mənt/','We must all work together to protect the environment.','Tất cả chúng ta phải cùng nhau hành động để bảo vệ môi trường.','môi trường'],
  ['fl-wa-009','/ˈek.sɪt/','In case of fire, use the nearest emergency exit.','Trong trường hợp hỏa hoạn, hãy sử dụng lối ra khẩn cấp gần nhất.','lối ra'],
  ['fl-wa-010','/faɪər/','We sat around the campfire to keep warm.','Chúng tôi ngồi quanh ngọn lửa trại để giữ ấm.','ngọn lửa'],
  ['fl-wa-011','/ˈfjuː.tʃər/','Scientists are trying to predict the future of our planet.','Các nhà khoa học đang cố gắng dự đoán tương lai của hành tinh chúng ta.','tương lai'],
  ['fl-wa-012','/hɪl/','The children ran to the top of the steep hill.','Bọn trẻ chạy lên đỉnh ngọn đồi dốc.','ngọn đồi'],
  ['fl-wa-013','/lænd/','After days at sea, the sailors were happy to see land.','Sau nhiều ngày lênh đênh trên biển, các thủy thủ đã rất vui mừng khi thấy đất liền.','đất liền'],
  ['fl-wa-014','/ˈəʊ.ʃən/','The Pacific is the largest ocean in the world.','Thái Bình Dương là đại dương lớn nhất trên thế giới.','đại dương'],
  ['fl-wa-015','/ˈplæn.ɪt/','Jupiter is the largest planet in our solar system.','Sao Mộc là hành tinh lớn nhất trong hệ mặt trời của chúng ta.','hành tinh'],
  ['fl-wa-016','/pɒnd/','We fed the ducks swimming in the small pond.','Chúng tôi đã cho những con vịt bơi trong cái ao nhỏ ăn.','cái ao'],
  ['fl-wa-017','/speɪs/','The astronaut travelled into outer space.','Phi hành gia đã du hành ra ngoài không gian.','không gian / vũ trụ'],
  ['fl-wa-018','/stəʊn/','The old wall was built completely out of solid stone.','Bức tường cũ được xây dựng hoàn toàn bằng đá tảng chắc chắn.','đá / tảng đá'],
  ['fl-wa-019','/striːm/','The clear mountain stream flowed into the river.','Con suối nhỏ trên núi trong vắt chảy vào dòng sông.','dòng suối'],
  ['fl-wa-020','/vjuː/','We had a beautiful view of the sea from our hotel window.','Chúng tôi có một tầm nhìn tuyệt đẹp ra biển từ cửa sổ khách sạn.','tầm nhìn / quang cảnh'],
  ['fl-wa-021','/wʊd/','The furniture in this room is made entirely of dark wood.','Nội thất trong căn phòng này được làm hoàn toàn bằng gỗ tối màu.','gỗ / khu rừng']
];

let sql = `-- 0022c: Fix ipa+examples+translations — weather, work, world (112 words)\n-- Generated: ${new Date().toISOString()}\n\n`;
for(const [id, ipa, en, vi, trans] of D) {
  sql += `UPDATE vocabulary_bank SET ipa='${ipa.replace(/'/g, "''")}', example_en='${en.replace(/'/g, "''")}', example_vi='${vi.replace(/'/g, "''")}', translation_vi='${trans.replace(/'/g, "''")}' WHERE id='${id}';\n`;
}
sql += `\n-- Total: ${D.length} rows\n`;

const out = path.join(__dirname, 'src/worker/migrations/0022c_fix_weather_work_world.sql');
fs.writeFileSync(out, sql);
console.log(`✅ ${out}\n📊 ${D.length} rows`);
