const fs=require('fs'),path=require('path');
const D=[
['st-pd-001','/bɪˈhaɪnd/','The cat is hiding behind the sofa.','Con mèo đang trốn sau chiếc sofa.'],
['st-pd-002','/bɪˈtwiːn/','The library is between the bank and the café.','Thư viện nằm giữa ngân hàng và quán cà phê.'],
['st-pd-003','/ˈbʊk.ʃɒp/','I bought a new novel at the bookshop yesterday.','Tôi mua một cuốn tiểu thuyết mới ở hiệu sách hôm qua.'],
['st-pd-004','/end/','Turn left at the end of the street.','Hãy rẽ trái ở cuối con phố.'],
['st-pd-005','/hɪə/','Come and sit here next to me.','Hãy đến ngồi đây cạnh tôi.'],
['st-pd-006','/ɪn/','The keys are in the bag on the table.','Chìa khóa ở trong túi trên bàn.'],
['st-pd-007','/ɪn frʌnt əv/','There is a big tree in front of the school.','Có một cây lớn ở trước cửa trường học.'],
['st-pd-008','/ɒn/','Your book is on the chair by the door.','Cuốn sách của bạn ở trên ghế gần cửa.'],
['st-pd-009','/pɑːk/','The children play football in the park after school.','Bọn trẻ chơi bóng đá trong công viên sau giờ học.'],
['st-pd-010','/ˈpleɪ.ɡraʊnd/','The children were running around the playground at break time.','Bọn trẻ chạy quanh sân chơi vào giờ giải lao.'],
['st-pd-011','/ʃɒp/','Mum went to the shop to buy milk and bread.','Mẹ đi cửa hàng để mua sữa và bánh mì.'],
['st-pd-012','/stɔː/','You can find everything you need at that big store.','Bạn có thể tìm thấy mọi thứ cần ở cửa hàng lớn đó.'],
['st-pd-013','/striːt/','We live on a quiet street near the park.','Chúng tôi sống trên một con phố yên tĩnh gần công viên.'],
['st-pd-014','/ðeə/','Your bag is over there, by the front door.','Túi của bạn ở đằng kia, gần cửa trước.'],
['st-pd-015','/ˈʌn.də/','The dog is sleeping under the kitchen table.','Con chó đang ngủ dưới gầm bàn bếp.'],
['st-pd-016','/zuː/','We saw elephants and lions at the zoo last Sunday.','Chúng tôi thấy voi và sư tử ở sở thú Chủ nhật vừa rồi.'],
['mv-pd-001','/əˈbʌv/','There is a lamp above the dining table.','Có một chiếc đèn phía trên bàn ăn.'],
['mv-pd-002','/bɪˈləʊ/','Their flat is on the floor below ours.','Căn hộ của họ ở tầng dưới tầng của chúng tôi.'],
['mv-pd-003','/ˈbɪl.dɪŋ/','The school is in a modern building near the park.','Trường học nằm trong một tòa nhà hiện đại gần công viên.'],
['mv-pd-004','/ˈbʌs ˌsteɪ.ʃən/','The bus station is a ten-minute walk from here.','Bến xe buýt cách đây mười phút đi bộ.'],
['mv-pd-005','/ˈbʌs stɒp/','We waited at the bus stop for twenty minutes.','Chúng tôi đợi ở trạm xe buýt hai mươi phút.'],
['mv-pd-006','/ˈkæf.eɪ/','Let us meet at the café on the corner at noon.','Hãy gặp nhau ở quán cà phê ở góc đường lúc trưa.'],
['mv-pd-007','/ˈkɑː pɑːk/','I could not find a free space in the car park.','Tôi không tìm được chỗ trống trong bãi đỗ xe.'],
['mv-pd-008','/ˈsen.tə/','The hotel is in the centre of the old city.','Khách sạn nằm ở trung tâm thành phố cổ.'],
['mv-pd-009','/ˈsɪn.ə.mə/','We are going to the cinema to see the new superhero film.','Chúng tôi đến rạp chiếu phim xem bộ phim siêu anh hùng mới.'],
['mv-pd-010','/ˈsɜː.kəl/','Stand in a circle and hold hands.','Đứng thành vòng tròn và nắm tay nhau.'],
['mv-pd-011','/ˈsɜː.kəs/','We saw clowns and acrobats perform at the circus.','Chúng tôi xem hề và các diễn viên nhào lộn biểu diễn ở rạp xiếc.'],
['mv-pd-012','/ˈsɪt.i ˌsen.tə/','They walked around the city centre doing their shopping.','Họ đi quanh trung tâm thành phố để mua sắm.'],
['mv-pd-013','/fɑːm/','They spent the weekend at a farm in the countryside.','Họ dành cuối tuần ở một trang trại dưới vùng quê.'],
['mv-pd-014','/ˈfʌn.feə/','The children went on lots of rides at the funfair.','Bọn trẻ trải nghiệm nhiều trò chơi ở hội chợ vui.'],
['mv-pd-015','/ˈhɒs.pɪ.təl/','She was taken to hospital after the accident.','Cô ấy được đưa đến bệnh viện sau vụ tai nạn.'],
['mv-pd-016','/ˈlaɪ.brər.i/','You can borrow books for free from the library.','Bạn có thể mượn sách miễn phí từ thư viện.'],
['mv-pd-017','/mæp/','We used a map to find our way around the old city.','Chúng tôi dùng bản đồ để tìm đường trong thành phố cổ.'],
['mv-pd-018','/ˈmɑː.kɪt/','She buys fresh fruit and vegetables at the market every morning.','Cô ấy mua hoa quả và rau tươi ở chợ mỗi buổi sáng.'],
['mv-pd-019','/nɪə/','The school is near the park, about five minutes on foot.','Trường học gần công viên, khoảng năm phút đi bộ.'],
['mv-pd-020','/ˈɒp.ə.zɪt/','The post office is directly opposite the bank.','Bưu điện nằm đối diện trực tiếp với ngân hàng.'],
['mv-pd-021','/pleɪs/','Paris is a wonderful place to visit in spring.','Paris là một địa điểm tuyệt vời để thăm quan vào mùa xuân.'],
['mv-pd-022','/ˈʃɒp.ɪŋ ˌsen.tə/','They spent the whole afternoon at the shopping centre.','Họ dành cả buổi chiều ở trung tâm mua sắm.'],
['mv-pd-023','/ˈspɔːts ˌsen.tə/','She goes to the sports centre to swim three times a week.','Cô ấy đến trung tâm thể thao để bơi ba lần mỗi tuần.'],
['mv-pd-024','/skweə/','There is a beautiful fountain in the main square.','Có một đài phun nước đẹp ở quảng trường chính.'],
['mv-pd-025','/ˈsteɪ.ʃən/','The train to the capital leaves from platform three.','Tàu đến thủ đô xuất phát từ sân ga số ba.'],
['mv-pd-026','/streɪt/','Go straight on until you reach the traffic lights.','Đi thẳng cho đến khi bạn đến đèn giao thông.'],
['mv-pd-027','/ˈsuː.pə.mɑː.kɪt/','She does her weekly shopping at the supermarket on Saturday.','Cô ấy đi mua sắm hàng tuần ở siêu thị vào thứ Bảy.'],
['mv-pd-028','/ˈswɪm.ɪŋ puːl/','The hotel has a heated outdoor swimming pool.','Khách sạn có một bể bơi ngoài trời được sưởi ấm.'],
['mv-pd-029','/ˈtaʊn ˌsen.tə/','The market is held every Saturday in the town centre.','Phiên chợ diễn ra mỗi thứ Bảy ở trung tâm thị trấn.'],
['fl-pd-001','/ˈeə.pɔːt/','We arrived at the airport two hours before the flight.','Chúng tôi đến sân bay hai tiếng trước chuyến bay.'],
['fl-pd-002','/bæŋk/','He went to the bank to withdraw some money.','Anh ấy đến ngân hàng để rút tiền.'],
['fl-pd-003','/brɪdʒ/','We walked over the bridge to reach the other side of the river.','Chúng tôi đi qua cây cầu để sang bờ kia của sông.'],
['fl-pd-004','/ˈkɑː.səl/','The castle was built more than five hundred years ago.','Lâu đài được xây dựng cách đây hơn năm trăm năm.'],
['fl-pd-005','/ˈkem.ɪst/','I got some medicine from the chemist for my sore throat.','Tôi mua thuốc ở hiệu thuốc để trị đau họng.'],
['fl-pd-006','/klʌb/','She joined the school drama club this term.','Cô ấy tham gia câu lạc bộ kịch của trường kỳ này.'],
['fl-pd-007','/ˈkɒl.ɪdʒ/','After school he wants to go to college to study engineering.','Sau khi tốt nghiệp anh ấy muốn vào cao đẳng học kỹ thuật.'],
['fl-pd-008','/ˈkɔː.nə/','Turn right at the corner of the street.','Hãy rẽ phải ở góc đường.'],
['fl-pd-009','/iːst/','The sun rises in the east every morning.','Mặt trời mọc ở phía đông mỗi buổi sáng.'],
['fl-pd-010','/ˈfæk.tər.i/','His father works in a car factory on the edge of town.','Bố của anh ấy làm việc ở nhà máy sản xuất ô tô ven thành phố.'],
['fl-pd-011','/ˈfaɪə ˌsteɪ.ʃən/','The fire station is on the main road out of town.','Trạm cứu hỏa nằm trên con đường chính ra khỏi thành phố.'],
['fl-pd-012','/frʌnt/','Please meet me at the front of the school at three o\'clock.','Hãy gặp tôi ở phía trước trường lúc ba giờ.'],
['fl-pd-013','/ɡet tuː/','How do you get to school every day?','Bạn đến trường bằng cách nào mỗi ngày?'],
['fl-pd-014','/həʊˈtel/','We stayed in a small hotel near the beach for a week.','Chúng tôi ở trong một khách sạn nhỏ gần bãi biển một tuần.'],
['fl-pd-015','/ˈkɪl.ə.miː.tə/','The village is three kilometres from the nearest town.','Ngôi làng cách thị trấn gần nhất ba kilômét.'],
['fl-pd-016','/left/','Turn left at the traffic lights and walk for two minutes.','Rẽ trái ở đèn giao thông và đi bộ hai phút.'],
['fl-pd-017','/ˈlʌn.dən/','London is the capital city of England and one of the largest cities in Europe.','London là thủ đô của Anh và một trong những thành phố lớn nhất châu Âu.'],
['fl-pd-018','/ˈmɪd.əl/','She stood in the middle of the room and looked around.','Cô ấy đứng ở giữa căn phòng và nhìn xung quanh.'],
['fl-pd-019','/mjuːˈzɪ.əm/','We visited a museum about ancient history during our school trip.','Chúng tôi tham quan bảo tàng về lịch sử cổ đại trong chuyến đi học.'],
['fl-pd-020','/nɔːθ/','Drive north for about fifty kilometres to reach the lake.','Lái xe về phía bắc khoảng năm mươi kilômét để đến hồ.'],
['fl-pd-021','/ˈəʊ.və/','The bridge goes over the river in the valley.','Cây cầu bắc qua con sông ở thung lũng.'],
['fl-pd-022','/pɑːθ/','Follow the path through the forest to reach the waterfall.','Đi theo con đường mòn qua khu rừng để đến thác nước.'],
['fl-pd-023','/pəˈliːs ˌsteɪ.ʃən/','She reported the theft at the local police station.','Cô ấy trình báo vụ trộm tại đồn cảnh sát địa phương.'],
['fl-pd-024','/ˈpəʊst ˌɒf.ɪs/','I need to go to the post office to send this parcel.','Tôi cần đến bưu điện để gửi kiện hàng này.'],
['fl-pd-025','/ˈres.tɒ.rɒnt/','We had dinner at a nice Italian restaurant in the city centre.','Chúng tôi ăn tối ở một nhà hàng Ý đẹp trong trung tâm thành phố.'],
['fl-pd-026','/raɪt/','Turn right after the traffic lights and the school is on your left.','Rẽ phải sau đèn giao thông và trường học ở bên trái bạn.'],
['fl-pd-027','/ˈskaɪ.skreɪ.pə/','The skyscraper in the centre of the city has one hundred floors.','Tòa nhà chọc trời ở trung tâm thành phố có một trăm tầng.'],
['fl-pd-028','/saʊθ/','They drove south towards the coast for the holiday.','Họ lái xe về phía nam hướng về bờ biển để nghỉ hè.'],
['fl-pd-029','/ˈsteɪ.di.əm/','Thousands of fans filled the stadium to watch the match.','Hàng nghìn người hâm mộ lấp đầy sân vận động để xem trận đấu.'],
['fl-pd-030','/streɪt ɒn/','Go straight on past the church and then turn left.','Đi thẳng qua nhà thờ rồi rẽ trái.'],
['fl-pd-031','/ˈθɪə.tə/','We saw an amazing play at the theatre last Saturday.','Chúng tôi xem một vở kịch tuyệt vời ở nhà hát thứ Bảy vừa rồi.'],
['fl-pd-032','/juːˈnɪ.və.sɪ.ti/','She worked very hard to get a place at university.','Cô ấy đã cố gắng rất nhiều để có được một chỗ ở trường đại học.'],
['fl-pd-033','/weɪ/','Could you tell me the way to the nearest bus stop?','Bạn có thể chỉ đường đến trạm xe buýt gần nhất không?'],
['fl-pd-034','/west/','The sun sets in the west every evening.','Mặt trời lặn ở phía tây mỗi buổi chiều.'],
];
let sql=`-- 0021b: Fix ipa+examples — places_directions (79 words)\n-- Generated: ${new Date().toISOString()}\n\n`;
for(const[id,ipa,en,vi]of D){
  sql+=`UPDATE vocabulary_bank SET ipa='${ipa.replace(/'/g,"''")}', example_en='${en.replace(/'/g,"''")}', example_vi='${vi.replace(/'/g,"''")}' WHERE id='${id}';\n`;
}
sql+=`\n-- Total: ${D.length} rows\n`;
const out=path.join(__dirname,'src/worker/migrations/0021b_fix_ipa_examples_places.sql');
fs.writeFileSync(out,sql);
console.log(`✅ ${out}\n📊 ${D.length} rows`);
