#!/usr/bin/env node
// generate_migration_0020.cjs
// Adds emoji for topics from 0018 (sports_leisure, time, toys, transport, weather, work, world)
// Run: node generate_migration_0020.cjs

const fs = require('fs');
const path = require('path');

const EMOJIS = [
  // === SPORTS_LEISURE ===
  ['fl-sl-001','backpack','🎒'],
  ['fl-sl-002','cartoon','📺'],
  ['fl-sl-003','channel','📡'],
  ['fl-sl-004','chess','♟️'],
  ['fl-sl-005','collect','🗃️'],
  ['fl-sl-006','concert','🎤'],
  ['fl-sl-007','diary','📔'],
  ['fl-sl-008','drum','🥁'],
  ['fl-sl-009','festival','🎉'],
  ['fl-sl-010','flashlight','🔦'],
  ['fl-sl-011','golf','⛳'],
  ['fl-sl-012','hotel','🏨'],
  ['fl-sl-013','instrument','🎸'],
  ['fl-sl-014','invitation','💌'],
  ['fl-sl-015','join','🤝'],
  ['fl-sl-016','magazine','📰'],
  ['fl-sl-017','match','⚽'],
  ['fl-sl-018','meet','🤝'],
  ['fl-sl-019','member','👥'],
  ['fl-sl-020','online','🌐'],
  ['fl-sl-021','pop music','🎵'],
  ['fl-sl-022','prize','🏆'],
  ['fl-sl-023','programme','📋'],
  ['fl-sl-024','puzzle','🧩'],
  ['fl-sl-025','pyramid','🔺'],
  ['fl-sl-026','quiz','❓'],
  ['fl-sl-027','race','🏃'],
  ['fl-sl-028','rock music','🎸'],
  ['fl-sl-029','rucksack','🎒'],
  ['fl-sl-030','score','🏅'],
  ['fl-sl-031','ski','⛷️'],
  ['fl-sl-032','sledge','🛷'],
  ['fl-sl-033','snowball','⛄'],
  ['fl-sl-034','snowboard','🏂'],
  ['fl-sl-035','snowboarding','🏂'],
  ['fl-sl-036','snowman','⛄'],
  ['fl-sl-037','stage','🎭'],
  ['fl-sl-038','suitcase','🧳'],
  ['fl-sl-039','swing','🎠'],
  ['fl-sl-040','team','👥'],
  ['fl-sl-041','tent','⛺'],
  ['fl-sl-042','torch','🔦'],
  ['fl-sl-043','tune','🎵'],
  ['fl-sl-044','tyre','🛞'],
  ['fl-sl-045','umbrella','☂️'],
  ['fl-sl-046','violin','🎻'],
  ['fl-sl-047','volleyball','🏐'],
  ['fl-sl-048','winner','🏆'],
  ['mv-sl-001','band','🎵'],
  ['mv-sl-002','CD','💿'],
  ['mv-sl-003','cinema','🎬'],
  ['mv-sl-004','comic','📖'],
  ['mv-sl-005','comic book','📚'],
  ['mv-sl-006','dance','💃'],
  ['mv-sl-007','DVD','📀'],
  ['mv-sl-008','email','📧'],
  ['mv-sl-009','film','🎬'],
  ['mv-sl-010','go shopping','🛍️'],
  ['mv-sl-011','goal','⚽'],
  ['mv-sl-012','holiday','🏖️'],
  ['mv-sl-013','hop','🐰'],
  ['mv-sl-014','ice skates','⛸️'],
  ['mv-sl-015','ice skating','⛸️'],
  ['mv-sl-016','kick','🦶'],
  ['mv-sl-017','movie','🎬'],
  ['mv-sl-018','net','🥅'],
  ['mv-sl-019','party','🎉'],
  ['mv-sl-020','player','🏅'],
  ['mv-sl-021','pool','🏊'],
  ['mv-sl-022','practice','💪'],
  ['mv-sl-023','practise','💪'],
  ['mv-sl-024','present','🎁'],
  ['mv-sl-025','ride','🚴'],
  ['mv-sl-026','roller skates','🛼'],
  ['mv-sl-027','roller skating','🛼'],
  ['mv-sl-028','sail','⛵'],
  ['mv-sl-029','score','🏅'],
  ['mv-sl-030','skate','⛸️'],
  ['mv-sl-031','skip','🤸'],
  ['mv-sl-032','sports centre','🏋️'],
  ['mv-sl-033','swim','🏊'],
  ['mv-sl-034','text','📱'],
  ['mv-sl-035','towel','🧺'],
  ['mv-sl-036','video','📹'],
  ['mv-sl-037','walk','🚶'],
  ['st-sl-001','badminton','🏸'],
  ['st-sl-002','ball','⚽'],
  ['st-sl-003','baseball','⚾'],
  ['st-sl-004','basketball','🏀'],
  ['st-sl-005','bat','🏏'],
  ['st-sl-006','beach','🏖️'],
  ['st-sl-007','bike','🚲'],
  ['st-sl-008','boat','⛵'],
  ['st-sl-009','book','📖'],
  ['st-sl-010','bounce','🏀'],
  ['st-sl-011','camera','📷'],
  ['st-sl-012','catch','🙌'],
  ['st-sl-013','doll','🪆'],
  ['st-sl-014','draw','✏️'],
  ['st-sl-015','drawing','🎨'],
  ['st-sl-016','drive','🚗'],
  ['st-sl-017','enjoy','😊'],
  ['st-sl-018','favourite','⭐'],
  ['st-sl-019','fishing','🎣'],
  ['st-sl-020','fly','✈️'],
  ['st-sl-021','football','⚽'],
  ['st-sl-022','game','🎮'],
  ['st-sl-023','guitar','🎸'],
  ['st-sl-024','hobby','🎯'],
  ['st-sl-025','hockey','🏒'],
  ['st-sl-026','jump','🤸'],
  ['st-sl-027','kick','🦶'],
  ['st-sl-028','kite','🪁'],
  ['st-sl-029','listen','👂'],
  ['st-sl-030','music','🎵'],
  ['st-sl-031','photo','📷'],
  ['st-sl-032','piano','🎹'],
  ['st-sl-033','picture','🖼️'],
  ['st-sl-034','play','🎮'],
  ['st-sl-035','radio','📻'],
  ['st-sl-036','read','📖'],
  ['st-sl-037','ride','🚴'],
  ['st-sl-038','run','🏃'],
  ['st-sl-039','sing','🎤'],
  ['st-sl-040','skateboard','🛹'],
  ['st-sl-041','skateboarding','🛹'],
  ['st-sl-042','soccer','⚽'],
  ['st-sl-043','song','🎵'],
  ['st-sl-044','sport','🏅'],
  ['st-sl-045','story','📖'],
  ['st-sl-046','swim','🏊'],
  ['st-sl-047','table tennis','🏓'],
  ['st-sl-048','take a photo','📸'],
  ['st-sl-049','television','📺'],
  ['st-sl-050','tennis','🎾'],
  ['st-sl-051','tennis racket','🎾'],
  ['st-sl-052','throw','🤾'],
  ['st-sl-053','toy','🧸'],
  ['st-sl-054','TV','📺'],
  ['st-sl-055','walk','🚶'],
  ['st-sl-056','watch','👀'],
  // === TIME ===
  ['fl-ti-001','a.m.','🌅'],
  ['fl-ti-002','after','⏩'],
  ['fl-ti-003','ago','⏪'],
  ['fl-ti-004','autumn','🍂'],
  ['fl-ti-005','before','⏮️'],
  ['fl-ti-006','calendar','📅'],
  ['fl-ti-007','century','📜'],
  ['fl-ti-008','date','📅'],
  ['fl-ti-009','early','🌅'],
  ['fl-ti-010','end','🏁'],
  ['fl-ti-011','fall','🍂'],
  ['fl-ti-012','future','🔮'],
  ['fl-ti-013','hour','🕐'],
  ['fl-ti-014','how long','⏱️'],
  ['fl-ti-015','late','🌙'],
  ['fl-ti-016','later','⏩'],
  ['fl-ti-017','midday','☀️'],
  ['fl-ti-018','midnight','🌙'],
  ['fl-ti-019','minute','⏱️'],
  ['fl-ti-020','month','📅'],
  ['fl-ti-021','p.m.','🌇'],
  ['fl-ti-022','past','⏪'],
  ['fl-ti-023','quarter','🕒'],
  ['fl-ti-024','spring','🌸'],
  ['fl-ti-025','summer','☀️'],
  ['fl-ti-026','time','🕐'],
  ['fl-ti-027','tomorrow','🌅'],
  ['fl-ti-028','tonight','🌙'],
  ['fl-ti-029','winter','❄️'],
  ['fl-ti-030','January','❄️'],
  ['fl-ti-031','February','💝'],
  ['fl-ti-032','March','🌷'],
  ['fl-ti-033','April','🌧️'],
  ['fl-ti-034','May','🌸'],
  ['fl-ti-035','June','☀️'],
  ['fl-ti-036','July','🌻'],
  ['fl-ti-037','August','🏖️'],
  ['fl-ti-038','September','🍂'],
  ['fl-ti-039','October','🎃'],
  ['fl-ti-040','November','🍁'],
  ['fl-ti-041','December','🎄'],
  ['mv-ti-001','after','⏩'],
  ['mv-ti-002','always','♾️'],
  ['mv-ti-003','before','⏮️'],
  ['mv-ti-004','every','🔄'],
  ['mv-ti-005','never','🚫'],
  ['mv-ti-006','o\'clock','🕐'],
  ['mv-ti-007','sometimes','🔄'],
  ['mv-ti-008','week','📅'],
  ['mv-ti-009','weekend','🎉'],
  ['mv-ti-010','yesterday','⏪'],
  ['mv-ti-011','Monday','📅'],
  ['mv-ti-012','Tuesday','📅'],
  ['mv-ti-013','Wednesday','📅'],
  ['mv-ti-014','Thursday','📅'],
  ['mv-ti-015','Friday','🎉'],
  ['mv-ti-016','Saturday','🏖️'],
  ['mv-ti-017','Sunday','⛪'],
  ['st-ti-001','afternoon','🌤️'],
  ['st-ti-002','birthday','🎂'],
  ['st-ti-003','clock','🕐'],
  ['st-ti-004','day','☀️'],
  ['st-ti-005','evening','🌆'],
  ['st-ti-006','in','⏱️'],
  ['st-ti-007','morning','🌅'],
  ['st-ti-008','night','🌙'],
  ['st-ti-009','today','📅'],
  ['st-ti-010','watch','⌚'],
  ['st-ti-011','year','📅'],
  // === TOYS ===
  ['mv-to-001','model','🤖'],
  ['st-to-001','alien','👽'],
  ['st-to-002','ball','⚽'],
  ['st-to-003','balloon','🎈'],
  ['st-to-004','baseball','⚾'],
  ['st-to-005','basketball','🏀'],
  ['st-to-006','bike','🚲'],
  ['st-to-007','board game','🎲'],
  ['st-to-008','boat','⛵'],
  ['st-to-009','car','🚗'],
  ['st-to-010','doll','🪆'],
  ['st-to-011','football','⚽'],
  ['st-to-012','game','🎮'],
  ['st-to-013','helicopter','🚁'],
  ['st-to-014','lorry','🚛'],
  ['st-to-015','monster','👹'],
  ['st-to-016','motorbike','🏍️'],
  ['st-to-017','plane','✈️'],
  ['st-to-018','robot','🤖'],
  ['st-to-019','soccer','⚽'],
  ['st-to-020','teddy','🧸'],
  ['st-to-021','toy','🧸'],
  ['st-to-022','train','🚂'],
  ['st-to-023','truck','🚚'],
  // === TRANSPORT ===
  ['fl-tr-013','taxi','🚕'],
  ['fl-tr-014','tour','🗺️'],
  ['fl-tr-015','traffic','🚦'],
  ['fl-tr-016','wheel','🛞'],
  ['mv-tr-001','bus station','🚌'],
  ['mv-tr-002','bus stop','🚏'],
  ['mv-tr-003','drive','🚗'],
  ['mv-tr-004','driver','👨‍✈️'],
  ['mv-tr-005','ride','🚴'],
  ['mv-tr-006','station','🚉'],
  ['mv-tr-007','ticket','🎫'],
  ['mv-tr-008','tractor','🚜'],
  ['mv-tr-009','trip','✈️'],
  ['st-tr-001','bike','🚲'],
  ['st-tr-002','boat','⛵'],
  ['st-tr-003','bus','🚌'],
  ['st-tr-004','car','🚗'],
  ['st-tr-005','drive','🚗'],
  ['st-tr-006','fly','✈️'],
  ['st-tr-007','go','🚶'],
  ['st-tr-008','helicopter','🚁'],
  ['st-tr-009','lorry','🚛'],
  ['st-tr-010','plane','✈️'],
  ['st-tr-011','ride','🚴'],
  ['st-tr-012','run','🏃'],
  ['st-tr-013','ship','🚢'],
  ['st-tr-014','swim','🏊'],
  ['st-tr-015','truck','🚚'],
  // === WEATHER ===
  ['fl-we-001','fog','🌫️'],
  ['fl-we-002','foggy','🌫️'],
  ['fl-we-003','storm','⛈️'],
  ['mv-we-001','cloud','☁️'],
  ['mv-we-002','cloudy','🌥️'],
  ['mv-we-003','ice','🧊'],
  ['mv-we-004','rain','🌧️'],
  ['mv-we-005','rainbow','🌈'],
  ['mv-we-006','sky','🌤️'],
  ['mv-we-007','snow','❄️'],
  ['mv-we-008','sunny','☀️'],
  ['mv-we-009','weather','🌤️'],
  ['mv-we-010','wind','💨'],
  ['mv-we-011','windy','💨'],
  ['st-we-001','sun','☀️'],
  // === WORK ===
  ['fl-wk-001','actor','🎭'],
  ['fl-wk-002','airport','✈️'],
  ['fl-wk-003','ambulance','🚑'],
  ['fl-wk-004','artist','🎨'],
  ['fl-wk-005','astronaut','🧑‍🚀'],
  ['fl-wk-006','business','💼'],
  ['fl-wk-007','businessman','👨‍💼'],
  ['fl-wk-008','businesswoman','👩‍💼'],
  ['fl-wk-009','designer','🎨'],
  ['fl-wk-010','engineer','👷'],
  ['fl-wk-011','factory','🏭'],
  ['fl-wk-012','fire engine','🚒'],
  ['fl-wk-013','fire fighter','🧑‍🚒'],
  ['fl-wk-014','job','💼'],
  ['fl-wk-015','journalist','📰'],
  ['fl-wk-016','manager','👔'],
  ['fl-wk-017','mechanic','🔧'],
  ['fl-wk-018','meeting','🤝'],
  ['fl-wk-019','news','📰'],
  ['fl-wk-020','newspaper','📰'],
  ['fl-wk-021','office','🏢'],
  ['fl-wk-022','photographer','📷'],
  ['fl-wk-023','pilot','👨‍✈️'],
  ['fl-wk-024','police officer','👮'],
  ['fl-wk-025','police station','🚔'],
  ['fl-wk-026','queen','👑'],
  ['fl-wk-027','rocket','🚀'],
  ['fl-wk-028','singer','🎤'],
  ['fl-wk-029','taxi','🚕'],
  ['fl-wk-030','waiter','🍽️'],
  ['mv-wk-001','circus','🎪'],
  ['mv-wk-002','clown','🤡'],
  ['mv-wk-003','cook','👨‍🍳'],
  ['mv-wk-004','dentist','🦷'],
  ['mv-wk-005','doctor','👨‍⚕️'],
  ['mv-wk-006','driver','🚗'],
  ['mv-wk-007','farmer','👨‍🌾'],
  ['mv-wk-008','film star','🌟'],
  ['mv-wk-009','hospital','🏥'],
  ['mv-wk-010','nurse','👩‍⚕️'],
  ['mv-wk-011','pirate','🏴‍☠️'],
  ['mv-wk-012','pop star','🌟'],
  ['mv-wk-013','teacher','👩‍🏫'],
  ['mv-wk-014','work','💼'],
  // === WORLD ===
  ['fl-wa-001','air','💨'],
  ['fl-wa-002','bridge','🌉'],
  ['fl-wa-003','castle','🏰'],
  ['fl-wa-004','cave','🦇'],
  ['fl-wa-005','desert','🏜️'],
  ['fl-wa-006','Earth','🌍'],
  ['fl-wa-007','entrance','🚪'],
  ['fl-wa-008','environment','🌿'],
  ['fl-wa-009','exit','🚪'],
  ['fl-wa-010','fire','🔥'],
  ['fl-wa-011','future','🔮'],
  ['fl-wa-012','hill','⛰️'],
  ['fl-wa-013','land','🌾'],
  ['fl-wa-014','ocean','🌊'],
  ['fl-wa-015','planet','🪐'],
  ['fl-wa-016','pond','🐸'],
  ['fl-wa-017','space','🚀'],
  ['fl-wa-018','stone','🪨'],
  ['fl-wa-019','stream','🏞️'],
  ['fl-wa-020','view','🏔️'],
  ['fl-wa-021','wood','🌲'],
  ['mv-wa-001','building','🏢'],
  ['mv-wa-002','city','🏙️'],
  ['mv-wa-003','country','🌍'],
  ['mv-wa-004','countryside','🌾'],
  ['mv-wa-005','field','🌾'],
  ['mv-wa-006','forest','🌲'],
  ['mv-wa-007','grass','🌿'],
  ['mv-wa-008','ground','🟫'],
  ['mv-wa-009','island','🏝️'],
  ['mv-wa-010','lake','🏞️'],
  ['mv-wa-011','leaf','🍃'],
  ['mv-wa-012','moon','🌙'],
  ['mv-wa-013','mountain','⛰️'],
  ['mv-wa-014','plant','🌱'],
  ['mv-wa-015','river','🏞️'],
  ['mv-wa-016','road','🛣️'],
  ['mv-wa-017','rock','🪨'],
  ['mv-wa-018','sky','🌤️'],
  ['mv-wa-019','star','⭐'],
  ['mv-wa-020','town','🏘️'],
  ['mv-wa-021','village','🏡'],
  ['mv-wa-022','waterfall','💧'],
  ['mv-wa-023','wave','🌊'],
  ['mv-wa-024','world','🌍'],
  ['st-wa-001','beach','🏖️'],
  ['st-wa-002','sand','🏜️'],
  ['st-wa-003','sea','🌊'],
  ['st-wa-004','shell','🐚'],
  ['st-wa-005','street','🛣️'],
  ['st-wa-006','sun','☀️'],
  ['st-wa-007','tree','🌳'],
  ['st-wa-008','water','💧'],
];

let sql = `-- 0020: Add emoji for topics from 0018 (sports_leisure, time, toys, transport, weather, work, world)
-- Total: ${EMOJIS.length} words
-- Generated: ${new Date().toISOString()}
-- Safe: UPDATE only, touches only emoji column

`;

for (const [id, , emoji] of EMOJIS) {
  sql += `UPDATE vocabulary_bank SET emoji = '${emoji}' WHERE id = '${id}';\n`;
}

sql += `\n-- Verify: SELECT COUNT(*) FROM vocabulary_bank WHERE (emoji IS NULL OR emoji = '');\n`;

const outPath = path.join(__dirname, 'src/worker/migrations/0020_add_emoji_0018_topics.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log(`✅ Generated: ${outPath}`);
console.log(`📊 Total UPDATE statements: ${EMOJIS.length}`);
