-- 0021a: Fix ipa + example_en + example_vi — home (83) + materials (9)
-- Generated: 2026-05-07T23:44:30.484Z
-- Safe: UPDATE only, touches only ipa, example_en, example_vi columns

UPDATE vocabulary_bank SET ipa = '/əˈpɑːt.mənt/', example_en = 'We live in a small apartment on the third floor.', example_vi = 'Chúng tôi sống trong một căn hộ nhỏ ở tầng ba.' WHERE id = 'st-ho-001';
UPDATE vocabulary_bank SET ipa = '/ˈɑːm.tʃeə/', example_en = 'My dad always sits in the armchair after dinner.', example_vi = 'Bố tôi luôn ngồi trên ghế bành sau bữa tối.' WHERE id = 'st-ho-002';
UPDATE vocabulary_bank SET ipa = '/bɑːθ/', example_en = 'The children love to play in the bath.', example_vi = 'Lũ trẻ thích chơi trong bồn tắm.' WHERE id = 'st-ho-003';
UPDATE vocabulary_bank SET ipa = '/ˈbɑːθ.ruːm/', example_en = 'There are two bathrooms in our new house.', example_vi = 'Nhà mới của chúng tôi có hai phòng tắm.' WHERE id = 'st-ho-004';
UPDATE vocabulary_bank SET ipa = '/bed/', example_en = 'She went to bed at nine o''clock last night.', example_vi = 'Cô ấy đi ngủ lúc chín giờ tối qua.' WHERE id = 'st-ho-005';
UPDATE vocabulary_bank SET ipa = '/ˈbed.ruːm/', example_en = 'My bedroom has a big window facing the garden.', example_vi = 'Phòng ngủ của tôi có một cửa sổ lớn nhìn ra vườn.' WHERE id = 'st-ho-006';
UPDATE vocabulary_bank SET ipa = '/ˈbʊk.keɪs/', example_en = 'The bookcase in the living room is full of novels.', example_vi = 'Tủ sách trong phòng khách chứa đầy tiểu thuyết.' WHERE id = 'st-ho-007';
UPDATE vocabulary_bank SET ipa = '/bɒks/', example_en = 'We put all the old toys in a cardboard box.', example_vi = 'Chúng tôi để tất cả đồ chơi cũ vào một chiếc hộp bìa cứng.' WHERE id = 'st-ho-008';
UPDATE vocabulary_bank SET ipa = '/ˈkæm.ər.ə/', example_en = 'She took a photo of us with her new camera.', example_vi = 'Cô ấy chụp ảnh chúng tôi bằng chiếc máy ảnh mới của mình.' WHERE id = 'st-ho-009';
UPDATE vocabulary_bank SET ipa = '/tʃeə/', example_en = 'Please sit on the chair next to the window.', example_vi = 'Hãy ngồi vào chiếc ghế gần cửa sổ.' WHERE id = 'st-ho-010';
UPDATE vocabulary_bank SET ipa = '/klɒk/', example_en = 'The clock on the wall says half past seven.', example_vi = 'Đồng hồ trên tường chỉ bảy giờ rưỡi.' WHERE id = 'st-ho-011';
UPDATE vocabulary_bank SET ipa = '/kəmˈpjuː.tə/', example_en = 'My sister uses the computer to do her homework.', example_vi = 'Chị tôi dùng máy tính để làm bài tập về nhà.' WHERE id = 'st-ho-012';
UPDATE vocabulary_bank SET ipa = '/ˈkʌb.əd/', example_en = 'The plates are in the cupboard above the sink.', example_vi = 'Những chiếc đĩa ở trong tủ phía trên bồn rửa.' WHERE id = 'st-ho-013';
UPDATE vocabulary_bank SET ipa = '/desk/', example_en = 'She does her homework at the desk in her room.', example_vi = 'Cô ấy làm bài tập tại bàn học trong phòng mình.' WHERE id = 'st-ho-014';
UPDATE vocabulary_bank SET ipa = '/ˈdaɪ.nɪŋ ruːm/', example_en = 'Our family eats dinner together in the dining room.', example_vi = 'Gia đình tôi ăn tối cùng nhau trong phòng ăn.' WHERE id = 'st-ho-015';
UPDATE vocabulary_bank SET ipa = '/dɒl/', example_en = 'My little sister has a favourite doll with red hair.', example_vi = 'Em gái tôi có một búp bê yêu thích với mái tóc đỏ.' WHERE id = 'st-ho-016';
UPDATE vocabulary_bank SET ipa = '/dɔː/', example_en = 'Please close the door quietly when you leave.', example_vi = 'Hãy đóng cửa nhẹ nhàng khi bạn ra ngoài.' WHERE id = 'st-ho-017';
UPDATE vocabulary_bank SET ipa = '/flæt/', example_en = 'They rent a small flat near the city centre.', example_vi = 'Họ thuê một căn hộ nhỏ gần trung tâm thành phố.' WHERE id = 'st-ho-018';
UPDATE vocabulary_bank SET ipa = '/ˈflaʊ.ə/', example_en = 'She put a yellow flower in a vase on the table.', example_vi = 'Cô ấy cắm một bông hoa vàng vào lọ trên bàn.' WHERE id = 'st-ho-019';
UPDATE vocabulary_bank SET ipa = '/ˈɡɑː.dən/', example_en = 'We grow tomatoes and herbs in our garden.', example_vi = 'Chúng tôi trồng cà chua và thảo mộc trong vườn.' WHERE id = 'st-ho-020';
UPDATE vocabulary_bank SET ipa = '/hɔːl/', example_en = 'Leave your shoes in the hall when you come in.', example_vi = 'Để giày ở sảnh khi bạn bước vào nhà.' WHERE id = 'st-ho-021';
UPDATE vocabulary_bank SET ipa = '/həʊm/', example_en = 'After a long holiday, it felt great to be home.', example_vi = 'Sau kỳ nghỉ dài, được về nhà thật tuyệt.' WHERE id = 'st-ho-022';
UPDATE vocabulary_bank SET ipa = '/haʊs/', example_en = 'Their house has a big garden at the back.', example_vi = 'Ngôi nhà của họ có một khu vườn lớn phía sau.' WHERE id = 'st-ho-023';
UPDATE vocabulary_bank SET ipa = '/ˈkɪtʃ.ɪn/', example_en = 'Mum is cooking soup in the kitchen right now.', example_vi = 'Mẹ đang nấu súp trong bếp lúc này.' WHERE id = 'st-ho-024';
UPDATE vocabulary_bank SET ipa = '/læmp/', example_en = 'Turn on the lamp — it is getting dark outside.', example_vi = 'Bật đèn lên — trời đang tối dần rồi.' WHERE id = 'st-ho-025';
UPDATE vocabulary_bank SET ipa = '/ˈlɪv.ɪŋ ruːm/', example_en = 'The whole family watches TV in the living room.', example_vi = 'Cả gia đình xem ti vi trong phòng khách.' WHERE id = 'st-ho-026';
UPDATE vocabulary_bank SET ipa = '/mæt/', example_en = 'Wipe your feet on the mat before coming inside.', example_vi = 'Hãy lau chân trên tấm thảm trước khi vào nhà.' WHERE id = 'st-ho-027';
UPDATE vocabulary_bank SET ipa = '/ˈmɪr.ə/', example_en = 'She looked at herself in the bathroom mirror.', example_vi = 'Cô ấy nhìn vào gương trong phòng tắm.' WHERE id = 'st-ho-028';
UPDATE vocabulary_bank SET ipa = '/fəʊn/', example_en = 'Can I use your phone to call my mum?', example_vi = 'Tôi có thể dùng điện thoại của bạn gọi cho mẹ tôi không?' WHERE id = 'st-ho-029';
UPDATE vocabulary_bank SET ipa = '/ˈpɪk.tʃə/', example_en = 'There is a picture of our family on the living room wall.', example_vi = 'Có một bức ảnh gia đình trên tường phòng khách.' WHERE id = 'st-ho-030';
UPDATE vocabulary_bank SET ipa = '/ˈreɪ.di.əʊ/', example_en = 'Dad listens to the radio while he drives to work.', example_vi = 'Bố nghe đài khi lái xe đi làm.' WHERE id = 'st-ho-031';
UPDATE vocabulary_bank SET ipa = '/ruːm/', example_en = 'Every room in the house has a window.', example_vi = 'Mỗi căn phòng trong nhà đều có cửa sổ.' WHERE id = 'st-ho-032';
UPDATE vocabulary_bank SET ipa = '/rʌɡ/', example_en = 'The cat is sleeping on the rug in front of the fireplace.', example_vi = 'Con mèo đang ngủ trên tấm thảm trước lò sưởi.' WHERE id = 'st-ho-033';
UPDATE vocabulary_bank SET ipa = '/sliːp/', example_en = 'Children need to sleep for at least nine hours a night.', example_vi = 'Trẻ em cần ngủ ít nhất chín tiếng mỗi đêm.' WHERE id = 'st-ho-034';
UPDATE vocabulary_bank SET ipa = '/ˈsəʊ.fə/', example_en = 'We all sat on the sofa to watch the film together.', example_vi = 'Chúng tôi cùng ngồi trên sofa để xem phim.' WHERE id = 'st-ho-035';
UPDATE vocabulary_bank SET ipa = '/ˈteɪ.bəl/', example_en = 'Please set the table — dinner is nearly ready.', example_vi = 'Hãy bày bàn ra — bữa tối gần xong rồi.' WHERE id = 'st-ho-036';
UPDATE vocabulary_bank SET ipa = '/ˈtel.ɪ.vɪʒ.ən/', example_en = 'They watch television every evening after dinner.', example_vi = 'Họ xem ti vi mỗi buổi tối sau bữa ăn.' WHERE id = 'st-ho-037';
UPDATE vocabulary_bank SET ipa = '/tɔɪ/', example_en = 'The children put their toys away before going to bed.', example_vi = 'Bọn trẻ dọn đồ chơi trước khi đi ngủ.' WHERE id = 'st-ho-038';
UPDATE vocabulary_bank SET ipa = '/triː/', example_en = 'There is a tall apple tree in our garden.', example_vi = 'Có một cây táo cao trong vườn nhà tôi.' WHERE id = 'st-ho-039';
UPDATE vocabulary_bank SET ipa = '/ˌtiːˈviː/', example_en = 'We have a large TV mounted on the living room wall.', example_vi = 'Chúng tôi có một chiếc ti vi lớn gắn trên tường phòng khách.' WHERE id = 'st-ho-040';
UPDATE vocabulary_bank SET ipa = '/wɔːl/', example_en = 'She painted the bedroom wall a pale blue colour.', example_vi = 'Cô ấy sơn bức tường phòng ngủ màu xanh nhạt.' WHERE id = 'st-ho-041';
UPDATE vocabulary_bank SET ipa = '/wɒtʃ/', example_en = 'My grandfather gave me his old silver watch.', example_vi = 'Ông nội tặng cho tôi chiếc đồng hồ bạc cũ của ông.' WHERE id = 'st-ho-042';
UPDATE vocabulary_bank SET ipa = '/ˈwɪn.dəʊ/', example_en = 'Open the window — it is very hot in here.', example_vi = 'Mở cửa sổ ra — trong này rất nóng.' WHERE id = 'st-ho-043';
UPDATE vocabulary_bank SET ipa = '/ˈæd.res/', example_en = 'Write your name and address clearly on the envelope.', example_vi = 'Hãy viết tên và địa chỉ của bạn rõ ràng lên phong bì.' WHERE id = 'mv-ho-001';
UPDATE vocabulary_bank SET ipa = '/ˈbæl.kə.ni/', example_en = 'We have breakfast on the balcony when it is sunny.', example_vi = 'Chúng tôi ăn sáng trên ban công khi trời nắng.' WHERE id = 'mv-ho-002';
UPDATE vocabulary_bank SET ipa = '/ˈbeɪs.mənt/', example_en = 'We store old furniture in the basement.', example_vi = 'Chúng tôi cất đồ nội thất cũ ở tầng hầm.' WHERE id = 'mv-ho-003';
UPDATE vocabulary_bank SET ipa = '/ˈblæŋ.kɪt/', example_en = 'She pulled the warm blanket over her shoulders.', example_vi = 'Cô ấy kéo chiếc chăn ấm lên vai.' WHERE id = 'mv-ho-004';
UPDATE vocabulary_bank SET ipa = '/ˌdaʊnˈsteəz/', example_en = 'Dad is downstairs making breakfast for everyone.', example_vi = 'Bố đang ở tầng dưới chuẩn bị bữa sáng cho mọi người.' WHERE id = 'mv-ho-005';
UPDATE vocabulary_bank SET ipa = '/driːm/', example_en = 'Last night I had a strange dream about flying over the sea.', example_vi = 'Tối qua tôi có một giấc mơ kỳ lạ về việc bay trên biển.' WHERE id = 'mv-ho-006';
UPDATE vocabulary_bank SET ipa = '/ˈel.ɪ.veɪ.tə/', example_en = 'We took the elevator to the fifteenth floor.', example_vi = 'Chúng tôi đi thang máy lên tầng mười lăm.' WHERE id = 'mv-ho-007';
UPDATE vocabulary_bank SET ipa = '/flɔː/', example_en = 'Their flat is on the fourth floor of the building.', example_vi = 'Căn hộ của họ ở tầng bốn của tòa nhà.' WHERE id = 'mv-ho-008';
UPDATE vocabulary_bank SET ipa = '/ˈɪn.tə.net/', example_en = 'We use the internet to do research for school projects.', example_vi = 'Chúng tôi dùng internet để nghiên cứu cho các dự án ở trường.' WHERE id = 'mv-ho-009';
UPDATE vocabulary_bank SET ipa = '/lɪft/', example_en = 'The lift in our building is broken, so we use the stairs.', example_vi = 'Thang máy trong tòa nhà hỏng nên chúng tôi dùng cầu thang.' WHERE id = 'mv-ho-010';
UPDATE vocabulary_bank SET ipa = '/ˈmes.ɪdʒ/', example_en = 'She sent me a message to say she would be late.', example_vi = 'Cô ấy nhắn tin cho tôi nói rằng cô ấy sẽ đến muộn.' WHERE id = 'mv-ho-011';
UPDATE vocabulary_bank SET ipa = '/ruːf/', example_en = 'A bird is sitting on the roof of the house.', example_vi = 'Một con chim đang ngồi trên mái nhà.' WHERE id = 'mv-ho-012';
UPDATE vocabulary_bank SET ipa = '/siːt/', example_en = 'Is this seat taken? Can I sit here?', example_vi = 'Chỗ này có ai ngồi chưa? Tôi có thể ngồi đây không?' WHERE id = 'mv-ho-013';
UPDATE vocabulary_bank SET ipa = '/ˈʃaʊ.ə/', example_en = 'He has a cold shower every morning to wake himself up.', example_vi = 'Anh ấy tắm nước lạnh mỗi sáng để tỉnh ngủ.' WHERE id = 'mv-ho-014';
UPDATE vocabulary_bank SET ipa = '/steəz/', example_en = 'She walked up the stairs to the second floor.', example_vi = 'Cô ấy leo cầu thang lên tầng hai.' WHERE id = 'mv-ho-015';
UPDATE vocabulary_bank SET ipa = '/ˈtuːθ.brʌʃ/', example_en = 'You should replace your toothbrush every three months.', example_vi = 'Bạn nên thay bàn chải đánh răng mỗi ba tháng.' WHERE id = 'mv-ho-016';
UPDATE vocabulary_bank SET ipa = '/ˈtuːθ.peɪst/', example_en = 'Squeeze a little toothpaste onto your brush before cleaning.', example_vi = 'Vắt một ít kem đánh răng lên bàn chải trước khi đánh.' WHERE id = 'mv-ho-017';
UPDATE vocabulary_bank SET ipa = '/ˈtaʊ.əl/', example_en = 'Dry your hands on the towel next to the sink.', example_vi = 'Lau tay bằng chiếc khăn bên cạnh bồn rửa.' WHERE id = 'mv-ho-018';
UPDATE vocabulary_bank SET ipa = '/ˌʌpˈsteəz/', example_en = 'My bedroom is upstairs, next to the bathroom.', example_vi = 'Phòng ngủ của tôi ở tầng trên, bên cạnh phòng tắm.' WHERE id = 'mv-ho-019';
UPDATE vocabulary_bank SET ipa = '/wɒʃ/', example_en = 'Wash the vegetables carefully before cooking them.', example_vi = 'Hãy rửa rau kỹ trước khi nấu.' WHERE id = 'mv-ho-020';
UPDATE vocabulary_bank SET ipa = '/brʌʃ/', example_en = 'Use this brush to scrub the floor clean.', example_vi = 'Dùng chiếc bàn chải này để kỳ cọ sàn nhà sạch sẽ.' WHERE id = 'fl-ho-001';
UPDATE vocabulary_bank SET ipa = '/kəʊm/', example_en = 'Run a comb through your hair before you go to school.', example_vi = 'Hãy chải tóc trước khi đến trường.' WHERE id = 'fl-ho-002';
UPDATE vocabulary_bank SET ipa = '/ˈkʊk.ə/', example_en = 'The cooker has four gas rings on top.', example_vi = 'Bếp nấu ăn có bốn vòng đốt ga ở trên.' WHERE id = 'fl-ho-003';
UPDATE vocabulary_bank SET ipa = '/ˈkʊʃ.ən/', example_en = 'She placed a soft cushion behind her back for support.', example_vi = 'Cô ấy đặt một chiếc gối mềm sau lưng để tựa.' WHERE id = 'fl-ho-004';
UPDATE vocabulary_bank SET ipa = '/ˈdaɪ.ər.i/', example_en = 'She writes in her diary every night before going to sleep.', example_vi = 'Cô ấy viết nhật ký mỗi tối trước khi ngủ.' WHERE id = 'fl-ho-005';
UPDATE vocabulary_bank SET ipa = '/ˈen.trəns/', example_en = 'Please wait for me at the entrance to the building.', example_vi = 'Hãy đợi tôi ở lối vào tòa nhà.' WHERE id = 'fl-ho-006';
UPDATE vocabulary_bank SET ipa = '/ˈen.və.ləʊp/', example_en = 'She put the letter in an envelope and took it to the post office.', example_vi = 'Cô ấy bỏ thư vào phong bì và mang đến bưu điện.' WHERE id = 'fl-ho-007';
UPDATE vocabulary_bank SET ipa = '/frɪdʒ/', example_en = 'There is some cold milk and juice in the fridge.', example_vi = 'Có một ít sữa lạnh và nước ép trong tủ lạnh.' WHERE id = 'fl-ho-008';
UPDATE vocabulary_bank SET ipa = '/ɡeɪt/', example_en = 'Please close the garden gate after you come in.', example_vi = 'Hãy đóng cổng vườn lại sau khi bạn vào.' WHERE id = 'fl-ho-009';
UPDATE vocabulary_bank SET ipa = '/kiː/', example_en = 'I lost my house key and had to wait outside.', example_vi = 'Tôi làm mất chìa khóa nhà và phải đợi bên ngoài.' WHERE id = 'fl-ho-010';
UPDATE vocabulary_bank SET ipa = '/ˈlet.ə/', example_en = 'She received a long letter from her friend in Australia.', example_vi = 'Cô ấy nhận được một bức thư dài từ người bạn ở Úc.' WHERE id = 'fl-ho-011';
UPDATE vocabulary_bank SET ipa = '/ˈʌv.ən/', example_en = 'Put the pizza in the oven for twenty-five minutes.', example_vi = 'Cho bánh pizza vào lò nướng trong hai mươi lăm phút.' WHERE id = 'fl-ho-012';
UPDATE vocabulary_bank SET ipa = '/skriːn/', example_en = 'The screen on his laptop is cracked.', example_vi = 'Màn hình máy tính xách tay của anh ấy bị vỡ.' WHERE id = 'fl-ho-013';
UPDATE vocabulary_bank SET ipa = '/ʃæmˈpuː/', example_en = 'Use this shampoo to wash your hair twice a week.', example_vi = 'Dùng dầu gội này để gội đầu hai lần mỗi tuần.' WHERE id = 'fl-ho-014';
UPDATE vocabulary_bank SET ipa = '/ʃelf/', example_en = 'The books are on the shelf above the computer desk.', example_vi = 'Những cuốn sách ở trên kệ phía trên bàn máy tính.' WHERE id = 'fl-ho-015';
UPDATE vocabulary_bank SET ipa = '/səʊp/', example_en = 'Wash your hands with soap and water for twenty seconds.', example_vi = 'Rửa tay bằng xà phòng và nước trong hai mươi giây.' WHERE id = 'fl-ho-016';
UPDATE vocabulary_bank SET ipa = '/stæmp/', example_en = 'You need to put a stamp on the envelope before posting it.', example_vi = 'Bạn cần dán tem thư lên phong bì trước khi gửi.' WHERE id = 'fl-ho-017';
UPDATE vocabulary_bank SET ipa = '/step/', example_en = 'Mind the step at the front door — it is slippery when wet.', example_vi = 'Chú ý bậc thềm ở cửa trước — trơn khi ướt đấy.' WHERE id = 'fl-ho-018';
UPDATE vocabulary_bank SET ipa = '/swɪŋ/', example_en = 'The children played happily on the swing in the park.', example_vi = 'Bọn trẻ vui vẻ chơi xích đu trong công viên.' WHERE id = 'fl-ho-019';
UPDATE vocabulary_bank SET ipa = '/ˈtel.ɪ.fəʊn/', example_en = 'The telephone rang while she was cooking in the kitchen.', example_vi = 'Điện thoại đổ chuông trong khi cô ấy đang nấu ăn trong bếp.' WHERE id = 'fl-ho-020';
UPDATE vocabulary_bank SET ipa = '/ˈpeɪ.pə/', example_en = 'Write your answers on a piece of paper.', example_vi = 'Hãy viết câu trả lời lên một tờ giấy.' WHERE id = 'st-ma-001';
UPDATE vocabulary_bank SET ipa = '/kɑːd/', example_en = 'She made a birthday card for her best friend.', example_vi = 'Cô ấy làm một tấm thiệp sinh nhật cho người bạn thân.' WHERE id = 'fl-ma-001';
UPDATE vocabulary_bank SET ipa = '/ɡlɑːs/', example_en = 'Be careful — that vase is made of glass and can break.', example_vi = 'Hãy cẩn thận — chiếc bình đó làm bằng thủy tinh và có thể vỡ.' WHERE id = 'fl-ma-002';
UPDATE vocabulary_bank SET ipa = '/ɡəʊld/', example_en = 'She wears a gold ring on her left hand.', example_vi = 'Cô ấy đeo một chiếc nhẫn vàng ở tay trái.' WHERE id = 'fl-ma-003';
UPDATE vocabulary_bank SET ipa = '/ˈmet.əl/', example_en = 'The bridge is built from steel and other types of metal.', example_vi = 'Cây cầu được xây dựng từ thép và các loại kim loại khác.' WHERE id = 'fl-ma-004';
UPDATE vocabulary_bank SET ipa = '/ˈplæs.tɪk/', example_en = 'We should use less plastic to protect the environment.', example_vi = 'Chúng ta nên dùng ít nhựa hơn để bảo vệ môi trường.' WHERE id = 'fl-ma-005';
UPDATE vocabulary_bank SET ipa = '/ˈsɪl.və/', example_en = 'Her grandmother gave her a beautiful silver necklace.', example_vi = 'Bà của cô ấy tặng cho cô một chiếc vòng cổ bạc đẹp.' WHERE id = 'fl-ma-006';
UPDATE vocabulary_bank SET ipa = '/wʊd/', example_en = 'This table is made from solid dark wood.', example_vi = 'Chiếc bàn này được làm từ gỗ tối màu chắc chắn.' WHERE id = 'fl-ma-007';
UPDATE vocabulary_bank SET ipa = '/wʊl/', example_en = 'This warm scarf is knitted from soft wool.', example_vi = 'Chiếc khăn quàng ấm này được đan từ len mềm.' WHERE id = 'fl-ma-008';

-- Total: 92 rows
