-- 0021c: Fix ipa+examples — school (95 words)
-- Generated: 2026-05-07T23:58:45.252Z

UPDATE vocabulary_bank SET ipa='/ˈæl.fə.bet/', example_en='The teacher wrote the alphabet on the board.', example_vi='Giáo viên viết bảng chữ cái lên bảng.' WHERE id='st-sc-001';
UPDATE vocabulary_bank SET ipa='/ˈɑːn.sə/', example_en='Write your answer in the box below the question.', example_vi='Viết câu trả lời của bạn vào ô bên dưới câu hỏi.' WHERE id='st-sc-002';
UPDATE vocabulary_bank SET ipa='/ɑːsk/', example_en='She asked the teacher a question about the homework.', example_vi='Cô ấy hỏi giáo viên một câu hỏi về bài tập về nhà.' WHERE id='st-sc-003';
UPDATE vocabulary_bank SET ipa='/bɔːd/', example_en='The teacher wrote the new words on the board.', example_vi='Giáo viên viết những từ mới lên bảng.' WHERE id='st-sc-004';
UPDATE vocabulary_bank SET ipa='/bʊk/', example_en='Read pages ten to fifteen in your textbook tonight.', example_vi='Đọc trang mười đến mười lăm trong sách giáo khoa tối nay.' WHERE id='st-sc-005';
UPDATE vocabulary_bank SET ipa='/ˈbʊk.keɪs/', example_en='Put the dictionaries back on the bookcase after you use them.', example_vi='Đặt lại từ điển vào tủ sách sau khi dùng xong.' WHERE id='st-sc-006';
UPDATE vocabulary_bank SET ipa='/klɑːs/', example_en='Our class has twenty-four students this year.', example_vi='Lớp học của chúng tôi có hai mươi bốn học sinh năm nay.' WHERE id='st-sc-007';
UPDATE vocabulary_bank SET ipa='/ˈklɑːs.ruːm/', example_en='The classroom has large windows and lots of natural light.', example_vi='Phòng học có những cửa sổ lớn và nhiều ánh sáng tự nhiên.' WHERE id='st-sc-008';
UPDATE vocabulary_bank SET ipa='/kləʊz/', example_en='Close your books and listen carefully to the teacher.', example_vi='Đóng sách lại và lắng nghe giáo viên cẩn thận.' WHERE id='st-sc-009';
UPDATE vocabulary_bank SET ipa='/ˈkʌl.ə/', example_en='What colour is your favourite pen?', example_vi='Màu bút yêu thích của bạn là gì?' WHERE id='st-sc-010';
UPDATE vocabulary_bank SET ipa='/kəmˈpjuː.tə/', example_en='We use the school computers to do research online.', example_vi='Chúng tôi dùng máy tính của trường để nghiên cứu trực tuyến.' WHERE id='st-sc-011';
UPDATE vocabulary_bank SET ipa='/kəˈrekt/', example_en='All of your answers are correct — well done!', example_vi='Tất cả câu trả lời của bạn đều đúng — giỏi lắm!' WHERE id='st-sc-012';
UPDATE vocabulary_bank SET ipa='/ˈkreɪ.ɒn/', example_en='She drew a rainbow using coloured crayons.', example_vi='Cô ấy vẽ một cầu vồng bằng bút màu sáp.' WHERE id='st-sc-013';
UPDATE vocabulary_bank SET ipa='/krɒs/', example_en='Put a cross next to the wrong answer.', example_vi='Đặt dấu chéo bên cạnh câu trả lời sai.' WHERE id='st-sc-014';
UPDATE vocabulary_bank SET ipa='/ˈkʌb.əd/', example_en='The art supplies are kept in the cupboard at the back of the room.', example_vi='Dụng cụ mỹ thuật được giữ trong tủ ở phía sau phòng.' WHERE id='st-sc-015';
UPDATE vocabulary_bank SET ipa='/desk/', example_en='Sit down at your desk and open your exercise books.', example_vi='Hãy ngồi xuống bàn học và mở vở bài tập ra.' WHERE id='st-sc-016';
UPDATE vocabulary_bank SET ipa='/dɔː/', example_en='Could someone open the door? It is very hot in here.', example_vi='Có ai mở cửa ra không? Trong này rất nóng.' WHERE id='st-sc-017';
UPDATE vocabulary_bank SET ipa='/drɔː/', example_en='Draw a picture of your favourite animal in the space below.', example_vi='Hãy vẽ một bức tranh về con vật yêu thích của bạn vào chỗ trống bên dưới.' WHERE id='st-sc-018';
UPDATE vocabulary_bank SET ipa='/ˈɪŋ.ɡlɪʃ/', example_en='We have English class every morning from eight to nine.', example_vi='Chúng tôi có lớp tiếng Anh mỗi sáng từ tám đến chín giờ.' WHERE id='st-sc-019';
UPDATE vocabulary_bank SET ipa='/ɪˈreɪ.zə/', example_en='Use an eraser to rub out the mistake.', example_vi='Dùng cục tẩy để xóa lỗi sai.' WHERE id='st-sc-020';
UPDATE vocabulary_bank SET ipa='/ɪɡˈzɑːm.pəl/', example_en='Look at the example before you do the exercise.', example_vi='Nhìn vào ví dụ trước khi bạn làm bài tập.' WHERE id='st-sc-021';
UPDATE vocabulary_bank SET ipa='/faɪnd/', example_en='Can you find the word on page thirty-two?', example_vi='Bạn có thể tìm thấy từ đó ở trang ba mươi hai không?' WHERE id='st-sc-022';
UPDATE vocabulary_bank SET ipa='/flɔː/', example_en='The teacher asked us to sit on the floor in a circle.', example_vi='Giáo viên yêu cầu chúng tôi ngồi trên sàn thành một vòng tròn.' WHERE id='st-sc-023';
UPDATE vocabulary_bank SET ipa='/ˈkiː.bɔːd/', example_en='She types very fast on the computer keyboard.', example_vi='Cô ấy gõ phím rất nhanh trên bàn phím máy tính.' WHERE id='st-sc-024';
UPDATE vocabulary_bank SET ipa='/lɜːn/', example_en='We learn ten new vocabulary words every week.', example_vi='Chúng tôi học mười từ vựng mới mỗi tuần.' WHERE id='st-sc-025';
UPDATE vocabulary_bank SET ipa='/ˈles.ən/', example_en='We have a science lesson every Thursday afternoon.', example_vi='Chúng tôi có tiết học khoa học mỗi chiều thứ Năm.' WHERE id='st-sc-026';
UPDATE vocabulary_bank SET ipa='/ˈlet.ə/', example_en='The word starts with the letter G.', example_vi='Từ đó bắt đầu bằng chữ cái G.' WHERE id='st-sc-027';
UPDATE vocabulary_bank SET ipa='/laɪn/', example_en='Draw a straight line under each sentence.', example_vi='Vẽ một đường thẳng dưới mỗi câu.' WHERE id='st-sc-028';
UPDATE vocabulary_bank SET ipa='/ˈlɪs.ən/', example_en='Listen carefully and then repeat what you hear.', example_vi='Hãy lắng nghe cẩn thận rồi nhắc lại những gì bạn nghe thấy.' WHERE id='st-sc-029';
UPDATE vocabulary_bank SET ipa='/lʊk/', example_en='Look at the picture and describe what you can see.', example_vi='Hãy nhìn vào bức tranh và mô tả những gì bạn thấy.' WHERE id='st-sc-030';
UPDATE vocabulary_bank SET ipa='/maʊs/', example_en='Move the mouse to the right and click on the icon.', example_vi='Di chuyển chuột sang phải và nhấp vào biểu tượng.' WHERE id='st-sc-031';
UPDATE vocabulary_bank SET ipa='/ˈmjuː.zɪk/', example_en='We have music lessons on Wednesday mornings.', example_vi='Chúng tôi có tiết học âm nhạc vào sáng thứ Tư.' WHERE id='st-sc-032';
UPDATE vocabulary_bank SET ipa='/ˈnʌm.bə/', example_en='Write the correct number in each box.', example_vi='Viết số đúng vào mỗi ô.' WHERE id='st-sc-033';
UPDATE vocabulary_bank SET ipa='/ˈəʊ.pən/', example_en='Open your workbooks to page forty-five.', example_vi='Mở vở bài tập ra trang bốn mươi lăm.' WHERE id='st-sc-034';
UPDATE vocabulary_bank SET ipa='/peɪdʒ/', example_en='Turn to page twelve and read the first paragraph.', example_vi='Lật đến trang mười hai và đọc đoạn văn đầu tiên.' WHERE id='st-sc-035';
UPDATE vocabulary_bank SET ipa='/ˈpeɪnt.ɪŋ/', example_en='There is a beautiful painting of the seaside on the classroom wall.', example_vi='Có một bức tranh sơn đẹp về bãi biển trên tường phòng học.' WHERE id='st-sc-036';
UPDATE vocabulary_bank SET ipa='/ˈpeɪ.pə/', example_en='Tear out a piece of paper and write your name at the top.', example_vi='Xé một tờ giấy ra và viết tên bạn ở trên cùng.' WHERE id='st-sc-037';
UPDATE vocabulary_bank SET ipa='/pɑːt/', example_en='Read the first part of the story for homework.', example_vi='Đọc phần đầu của câu chuyện làm bài tập về nhà.' WHERE id='st-sc-038';
UPDATE vocabulary_bank SET ipa='/pen/', example_en='Please write in pen, not pencil, for the test.', example_vi='Hãy viết bằng bút bi, không dùng bút chì, trong bài kiểm tra.' WHERE id='st-sc-039';
UPDATE vocabulary_bank SET ipa='/ˈpen.səl/', example_en='She sharpened her pencil before starting the drawing.', example_vi='Cô ấy gọt bút chì trước khi bắt đầu vẽ.' WHERE id='st-sc-040';
UPDATE vocabulary_bank SET ipa='/ˈpɪk.tʃə/', example_en='Look at the picture and answer the questions below.', example_vi='Hãy nhìn vào bức tranh và trả lời các câu hỏi bên dưới.' WHERE id='st-sc-041';
UPDATE vocabulary_bank SET ipa='/ˈpleɪ.ɡraʊnd/', example_en='The children run around the playground during their break.', example_vi='Bọn trẻ chạy vòng quanh sân chơi trong giờ giải lao.' WHERE id='st-sc-042';
UPDATE vocabulary_bank SET ipa='/ˈpəʊ.stə/', example_en='They made a poster about endangered animals for the science fair.', example_vi='Họ làm một tờ áp phích về các loài động vật có nguy cơ tuyệt chủng cho hội chợ khoa học.' WHERE id='st-sc-043';
UPDATE vocabulary_bank SET ipa='/ˈkwes.tʃən/', example_en='Ask the teacher if you do not understand the question.', example_vi='Hỏi giáo viên nếu bạn không hiểu câu hỏi.' WHERE id='st-sc-044';
UPDATE vocabulary_bank SET ipa='/riːd/', example_en='Read the passage carefully before answering the questions.', example_vi='Đọc đoạn văn cẩn thận trước khi trả lời câu hỏi.' WHERE id='st-sc-045';
UPDATE vocabulary_bank SET ipa='/raɪt/', example_en='Tick the right answer and cross out the wrong ones.', example_vi='Đánh dấu câu trả lời đúng và gạch bỏ những câu sai.' WHERE id='st-sc-046';
UPDATE vocabulary_bank SET ipa='/ˈrʌb.ə/', example_en='He used a rubber to erase the pencil marks.', example_vi='Anh ấy dùng cục tẩy để xóa các nét bút chì.' WHERE id='st-sc-047';
UPDATE vocabulary_bank SET ipa='/ˈruː.lə/', example_en='Use a ruler to draw a straight line.', example_vi='Dùng thước kẻ để vẽ một đường thẳng.' WHERE id='st-sc-048';
UPDATE vocabulary_bank SET ipa='/skuːl/', example_en='School starts at half past eight every morning.', example_vi='Trường bắt đầu lúc tám giờ rưỡi mỗi sáng.' WHERE id='st-sc-049';
UPDATE vocabulary_bank SET ipa='/ˈsen.təns/', example_en='Write a sentence using each of the new words.', example_vi='Hãy viết một câu sử dụng mỗi từ mới.' WHERE id='st-sc-050';
UPDATE vocabulary_bank SET ipa='/sɪt/', example_en='Sit down quietly and wait for the lesson to begin.', example_vi='Ngồi xuống yên lặng và chờ tiết học bắt đầu.' WHERE id='st-sc-051';
UPDATE vocabulary_bank SET ipa='/spel/', example_en='Can you spell your surname for me, please?', example_vi='Bạn có thể đánh vần họ của bạn cho tôi không?' WHERE id='st-sc-052';
UPDATE vocabulary_bank SET ipa='/stænd/', example_en='Please stand up when the headteacher enters the room.', example_vi='Hãy đứng dậy khi hiệu trưởng bước vào phòng.' WHERE id='st-sc-053';
UPDATE vocabulary_bank SET ipa='/ˈstɔː.ri/', example_en='The teacher told us a funny story to start the lesson.', example_vi='Giáo viên kể cho chúng tôi một câu chuyện vui để bắt đầu tiết học.' WHERE id='st-sc-054';
UPDATE vocabulary_bank SET ipa='/ˈtiː.tʃə/', example_en='Our maths teacher explains everything very clearly.', example_vi='Giáo viên toán của chúng tôi giải thích mọi thứ rất rõ ràng.' WHERE id='st-sc-055';
UPDATE vocabulary_bank SET ipa='/tel/', example_en='Tell me what happened at school today.', example_vi='Kể cho tôi nghe chuyện gì đã xảy ra ở trường hôm nay.' WHERE id='st-sc-056';
UPDATE vocabulary_bank SET ipa='/tɪk/', example_en='Put a tick next to the correct answer.', example_vi='Đặt dấu tích bên cạnh câu trả lời đúng.' WHERE id='st-sc-057';
UPDATE vocabulary_bank SET ipa='/ˌʌn.dəˈstænd/', example_en='Do you understand the instructions for this exercise?', example_vi='Bạn có hiểu hướng dẫn cho bài tập này không?' WHERE id='st-sc-058';
UPDATE vocabulary_bank SET ipa='/wɔːl/', example_en='There are maps and posters on every wall of the classroom.', example_vi='Có bản đồ và áp phích trên mọi bức tường của phòng học.' WHERE id='st-sc-059';
UPDATE vocabulary_bank SET ipa='/ˈwɪn.dəʊ/', example_en='She sat by the window and looked out at the garden.', example_vi='Cô ấy ngồi bên cửa sổ và nhìn ra khu vườn.' WHERE id='st-sc-060';
UPDATE vocabulary_bank SET ipa='/wɜːd/', example_en='Look up the meaning of this word in your dictionary.', example_vi='Tra nghĩa của từ này trong từ điển của bạn.' WHERE id='st-sc-061';
UPDATE vocabulary_bank SET ipa='/raɪt/', example_en='Write your name and the date at the top of the page.', example_vi='Viết tên và ngày tháng lên đầu trang giấy.' WHERE id='st-sc-062';
UPDATE vocabulary_bank SET ipa='/breɪk/', example_en='We play outside during the morning break.', example_vi='Chúng tôi chơi ngoài trời trong giờ giải lao buổi sáng.' WHERE id='mv-sc-001';
UPDATE vocabulary_bank SET ipa='/ˈhəʊm.wɜːk/', example_en='She finished all her homework before dinner.', example_vi='Cô ấy hoàn thành toàn bộ bài tập về nhà trước bữa tối.' WHERE id='mv-sc-002';
UPDATE vocabulary_bank SET ipa='/mɪˈsteɪk/', example_en='Everyone makes mistakes when they are learning something new.', example_vi='Ai cũng mắc lỗi khi đang học điều gì đó mới.' WHERE id='mv-sc-003';
UPDATE vocabulary_bank SET ipa='/tiːtʃ/', example_en='She wants to teach English to young children when she grows up.', example_vi='Cô ấy muốn dạy tiếng Anh cho trẻ nhỏ khi lớn lên.' WHERE id='mv-sc-004';
UPDATE vocabulary_bank SET ipa='/tekst/', example_en='Read the text on page eighteen and answer the questions.', example_vi='Đọc văn bản ở trang mười tám và trả lời các câu hỏi.' WHERE id='mv-sc-005';
UPDATE vocabulary_bank SET ipa='/ˈweb.saɪt/', example_en='Check the school website for information about the trip.', example_vi='Kiểm tra trang web của trường để biết thông tin về chuyến đi.' WHERE id='mv-sc-006';
UPDATE vocabulary_bank SET ipa='/ɑːt/', example_en='She is very good at art and loves painting landscapes.', example_vi='Cô ấy rất giỏi mỹ thuật và thích vẽ phong cảnh.' WHERE id='fl-sc-001';
UPDATE vocabulary_bank SET ipa='/ˈbæk.pæk/', example_en='He packed his backpack the night before the school trip.', example_vi='Anh ấy đóng gói ba lô vào tối hôm trước chuyến đi học.' WHERE id='fl-sc-002';
UPDATE vocabulary_bank SET ipa='/bɪn/', example_en='Throw your rubbish in the bin, not on the floor.', example_vi='Hãy bỏ rác vào thùng rác, không bỏ xuống sàn.' WHERE id='fl-sc-003';
UPDATE vocabulary_bank SET ipa='/klʌb/', example_en='She is the president of the school debating club.', example_vi='Cô ấy là chủ tịch câu lạc bộ tranh luận của trường.' WHERE id='fl-sc-004';
UPDATE vocabulary_bank SET ipa='/ˈkɒl.ɪdʒ/', example_en='He is studying business at a college in the city.', example_vi='Anh ấy đang học kinh doanh tại một trường cao đẳng trong thành phố.' WHERE id='fl-sc-005';
UPDATE vocabulary_bank SET ipa='/ˌkɒm.pɪˈtɪʃ.ən/', example_en='She won first place in the national spelling competition.', example_vi='Cô ấy giành giải nhất trong cuộc thi đánh vần toàn quốc.' WHERE id='fl-sc-006';
UPDATE vocabulary_bank SET ipa='/ˈdɪk.ʃən.ər.i/', example_en='Use your dictionary to check the spelling of difficult words.', example_vi='Dùng từ điển để kiểm tra chính tả của những từ khó.' WHERE id='fl-sc-007';
UPDATE vocabulary_bank SET ipa='/flæɡ/', example_en='Each country has its own national flag with different colours.', example_vi='Mỗi quốc gia có lá cờ riêng với màu sắc khác nhau.' WHERE id='fl-sc-008';
UPDATE vocabulary_bank SET ipa='/dʒiˈɒɡ.rə.fi/', example_en='We are studying the geography of South-East Asia this term.', example_vi='Chúng tôi đang học địa lý của Đông Nam Á kỳ này.' WHERE id='fl-sc-009';
UPDATE vocabulary_bank SET ipa='/ɡluː/', example_en='Use glue to stick the pictures onto your poster.', example_vi='Dùng keo để dán tranh lên áp phích của bạn.' WHERE id='fl-sc-010';
UPDATE vocabulary_bank SET ipa='/ɡruːp/', example_en='Work in groups of four to complete the project.', example_vi='Làm việc theo nhóm bốn người để hoàn thành dự án.' WHERE id='fl-sc-011';
UPDATE vocabulary_bank SET ipa='/dʒɪm/', example_en='We have gym class every Tuesday and do gymnastics.', example_vi='Chúng tôi có tiết thể dục mỗi thứ Ba và tập thể dục dụng cụ.' WHERE id='fl-sc-012';
UPDATE vocabulary_bank SET ipa='/ˈhɪs.tər.i/', example_en='In history class we are learning about the Second World War.', example_vi='Trong lớp lịch sử chúng tôi đang học về Chiến tranh Thế giới thứ Hai.' WHERE id='fl-sc-013';
UPDATE vocabulary_bank SET ipa='/ˈlæŋ.ɡwɪdʒ/', example_en='She speaks three languages fluently: French, Spanish and English.', example_vi='Cô ấy nói thành thạo ba ngôn ngữ: Pháp, Tây Ban Nha và tiếng Anh.' WHERE id='fl-sc-014';
UPDATE vocabulary_bank SET ipa='/mæθs/', example_en='Maths is my favourite subject because I love solving problems.', example_vi='Toán là môn học yêu thích của tôi vì tôi thích giải các bài toán.' WHERE id='fl-sc-015';
UPDATE vocabulary_bank SET ipa='/ˈɒn.laɪn/', example_en='The school offers many online lessons for students at home.', example_vi='Trường cung cấp nhiều bài học trực tuyến cho học sinh ở nhà.' WHERE id='fl-sc-016';
UPDATE vocabulary_bank SET ipa='/ˈprɒdʒ.ekt/', example_en='Our science project is about renewable energy sources.', example_vi='Dự án khoa học của chúng tôi nói về các nguồn năng lượng tái tạo.' WHERE id='fl-sc-017';
UPDATE vocabulary_bank SET ipa='/ˈrʌk.sæk/', example_en='She carried all her school books in her rucksack.', example_vi='Cô ấy mang tất cả sách vở trong ba lô đến trường.' WHERE id='fl-sc-018';
UPDATE vocabulary_bank SET ipa='/ˈsaɪ.əns/', example_en='In science we are doing experiments about light and colour.', example_vi='Trong tiết khoa học chúng tôi đang làm thí nghiệm về ánh sáng và màu sắc.' WHERE id='fl-sc-019';
UPDATE vocabulary_bank SET ipa='/ˈsɪz.əz/', example_en='Be careful when you use scissors — they are very sharp.', example_vi='Hãy cẩn thận khi dùng kéo — chúng rất sắc.' WHERE id='fl-sc-020';
UPDATE vocabulary_bank SET ipa='/skriːn/', example_en='The teacher showed a video on the large screen at the front.', example_vi='Giáo viên chiếu một đoạn video trên màn hình lớn ở phía trước.' WHERE id='fl-sc-021';
UPDATE vocabulary_bank SET ipa='/ʃelf/', example_en='Return all reference books to the shelf when you finish.', example_vi='Hãy trả lại tất cả sách tham khảo vào kệ khi bạn xong.' WHERE id='fl-sc-022';
UPDATE vocabulary_bank SET ipa='/ˈstjuː.dənt/', example_en='Every student in the class passed the end-of-year exam.', example_vi='Mỗi học sinh trong lớp đều vượt qua kỳ thi cuối năm.' WHERE id='fl-sc-023';
UPDATE vocabulary_bank SET ipa='/ˈstʌd.i/', example_en='She needs to study hard to prepare for the entrance exam.', example_vi='Cô ấy cần học chăm chỉ để chuẩn bị cho kỳ thi đầu vào.' WHERE id='fl-sc-024';
UPDATE vocabulary_bank SET ipa='/ˈsʌb.dʒɪkt/', example_en='Which subject do you enjoy most: art or music?', example_vi='Bạn thích môn học nào nhất: mỹ thuật hay âm nhạc?' WHERE id='fl-sc-025';
UPDATE vocabulary_bank SET ipa='/ˈtaɪm.teɪ.bəl/', example_en='Check the timetable to see when your next lesson is.', example_vi='Kiểm tra thời khóa biểu để xem tiết học tiếp theo của bạn khi nào.' WHERE id='fl-sc-026';
UPDATE vocabulary_bank SET ipa='/ˌjuː.nɪˈvɜː.sɪ.ti/', example_en='She got a scholarship to study medicine at university.', example_vi='Cô ấy nhận được học bổng để học y khoa tại trường đại học.' WHERE id='fl-sc-027';

-- Total: 95 rows
