-- 0021b: Fix ipa+examples — places_directions (79 words)
-- Generated: 2026-05-07T23:56:36.907Z

UPDATE vocabulary_bank SET ipa='/bɪˈhaɪnd/', example_en='The cat is hiding behind the sofa.', example_vi='Con mèo đang trốn sau chiếc sofa.' WHERE id='st-pd-001';
UPDATE vocabulary_bank SET ipa='/bɪˈtwiːn/', example_en='The library is between the bank and the café.', example_vi='Thư viện nằm giữa ngân hàng và quán cà phê.' WHERE id='st-pd-002';
UPDATE vocabulary_bank SET ipa='/ˈbʊk.ʃɒp/', example_en='I bought a new novel at the bookshop yesterday.', example_vi='Tôi mua một cuốn tiểu thuyết mới ở hiệu sách hôm qua.' WHERE id='st-pd-003';
UPDATE vocabulary_bank SET ipa='/end/', example_en='Turn left at the end of the street.', example_vi='Hãy rẽ trái ở cuối con phố.' WHERE id='st-pd-004';
UPDATE vocabulary_bank SET ipa='/hɪə/', example_en='Come and sit here next to me.', example_vi='Hãy đến ngồi đây cạnh tôi.' WHERE id='st-pd-005';
UPDATE vocabulary_bank SET ipa='/ɪn/', example_en='The keys are in the bag on the table.', example_vi='Chìa khóa ở trong túi trên bàn.' WHERE id='st-pd-006';
UPDATE vocabulary_bank SET ipa='/ɪn frʌnt əv/', example_en='There is a big tree in front of the school.', example_vi='Có một cây lớn ở trước cửa trường học.' WHERE id='st-pd-007';
UPDATE vocabulary_bank SET ipa='/ɒn/', example_en='Your book is on the chair by the door.', example_vi='Cuốn sách của bạn ở trên ghế gần cửa.' WHERE id='st-pd-008';
UPDATE vocabulary_bank SET ipa='/pɑːk/', example_en='The children play football in the park after school.', example_vi='Bọn trẻ chơi bóng đá trong công viên sau giờ học.' WHERE id='st-pd-009';
UPDATE vocabulary_bank SET ipa='/ˈpleɪ.ɡraʊnd/', example_en='The children were running around the playground at break time.', example_vi='Bọn trẻ chạy quanh sân chơi vào giờ giải lao.' WHERE id='st-pd-010';
UPDATE vocabulary_bank SET ipa='/ʃɒp/', example_en='Mum went to the shop to buy milk and bread.', example_vi='Mẹ đi cửa hàng để mua sữa và bánh mì.' WHERE id='st-pd-011';
UPDATE vocabulary_bank SET ipa='/stɔː/', example_en='You can find everything you need at that big store.', example_vi='Bạn có thể tìm thấy mọi thứ cần ở cửa hàng lớn đó.' WHERE id='st-pd-012';
UPDATE vocabulary_bank SET ipa='/striːt/', example_en='We live on a quiet street near the park.', example_vi='Chúng tôi sống trên một con phố yên tĩnh gần công viên.' WHERE id='st-pd-013';
UPDATE vocabulary_bank SET ipa='/ðeə/', example_en='Your bag is over there, by the front door.', example_vi='Túi của bạn ở đằng kia, gần cửa trước.' WHERE id='st-pd-014';
UPDATE vocabulary_bank SET ipa='/ˈʌn.də/', example_en='The dog is sleeping under the kitchen table.', example_vi='Con chó đang ngủ dưới gầm bàn bếp.' WHERE id='st-pd-015';
UPDATE vocabulary_bank SET ipa='/zuː/', example_en='We saw elephants and lions at the zoo last Sunday.', example_vi='Chúng tôi thấy voi và sư tử ở sở thú Chủ nhật vừa rồi.' WHERE id='st-pd-016';
UPDATE vocabulary_bank SET ipa='/əˈbʌv/', example_en='There is a lamp above the dining table.', example_vi='Có một chiếc đèn phía trên bàn ăn.' WHERE id='mv-pd-001';
UPDATE vocabulary_bank SET ipa='/bɪˈləʊ/', example_en='Their flat is on the floor below ours.', example_vi='Căn hộ của họ ở tầng dưới tầng của chúng tôi.' WHERE id='mv-pd-002';
UPDATE vocabulary_bank SET ipa='/ˈbɪl.dɪŋ/', example_en='The school is in a modern building near the park.', example_vi='Trường học nằm trong một tòa nhà hiện đại gần công viên.' WHERE id='mv-pd-003';
UPDATE vocabulary_bank SET ipa='/ˈbʌs ˌsteɪ.ʃən/', example_en='The bus station is a ten-minute walk from here.', example_vi='Bến xe buýt cách đây mười phút đi bộ.' WHERE id='mv-pd-004';
UPDATE vocabulary_bank SET ipa='/ˈbʌs stɒp/', example_en='We waited at the bus stop for twenty minutes.', example_vi='Chúng tôi đợi ở trạm xe buýt hai mươi phút.' WHERE id='mv-pd-005';
UPDATE vocabulary_bank SET ipa='/ˈkæf.eɪ/', example_en='Let us meet at the café on the corner at noon.', example_vi='Hãy gặp nhau ở quán cà phê ở góc đường lúc trưa.' WHERE id='mv-pd-006';
UPDATE vocabulary_bank SET ipa='/ˈkɑː pɑːk/', example_en='I could not find a free space in the car park.', example_vi='Tôi không tìm được chỗ trống trong bãi đỗ xe.' WHERE id='mv-pd-007';
UPDATE vocabulary_bank SET ipa='/ˈsen.tə/', example_en='The hotel is in the centre of the old city.', example_vi='Khách sạn nằm ở trung tâm thành phố cổ.' WHERE id='mv-pd-008';
UPDATE vocabulary_bank SET ipa='/ˈsɪn.ə.mə/', example_en='We are going to the cinema to see the new superhero film.', example_vi='Chúng tôi đến rạp chiếu phim xem bộ phim siêu anh hùng mới.' WHERE id='mv-pd-009';
UPDATE vocabulary_bank SET ipa='/ˈsɜː.kəl/', example_en='Stand in a circle and hold hands.', example_vi='Đứng thành vòng tròn và nắm tay nhau.' WHERE id='mv-pd-010';
UPDATE vocabulary_bank SET ipa='/ˈsɜː.kəs/', example_en='We saw clowns and acrobats perform at the circus.', example_vi='Chúng tôi xem hề và các diễn viên nhào lộn biểu diễn ở rạp xiếc.' WHERE id='mv-pd-011';
UPDATE vocabulary_bank SET ipa='/ˈsɪt.i ˌsen.tə/', example_en='They walked around the city centre doing their shopping.', example_vi='Họ đi quanh trung tâm thành phố để mua sắm.' WHERE id='mv-pd-012';
UPDATE vocabulary_bank SET ipa='/fɑːm/', example_en='They spent the weekend at a farm in the countryside.', example_vi='Họ dành cuối tuần ở một trang trại dưới vùng quê.' WHERE id='mv-pd-013';
UPDATE vocabulary_bank SET ipa='/ˈfʌn.feə/', example_en='The children went on lots of rides at the funfair.', example_vi='Bọn trẻ trải nghiệm nhiều trò chơi ở hội chợ vui.' WHERE id='mv-pd-014';
UPDATE vocabulary_bank SET ipa='/ˈhɒs.pɪ.təl/', example_en='She was taken to hospital after the accident.', example_vi='Cô ấy được đưa đến bệnh viện sau vụ tai nạn.' WHERE id='mv-pd-015';
UPDATE vocabulary_bank SET ipa='/ˈlaɪ.brər.i/', example_en='You can borrow books for free from the library.', example_vi='Bạn có thể mượn sách miễn phí từ thư viện.' WHERE id='mv-pd-016';
UPDATE vocabulary_bank SET ipa='/mæp/', example_en='We used a map to find our way around the old city.', example_vi='Chúng tôi dùng bản đồ để tìm đường trong thành phố cổ.' WHERE id='mv-pd-017';
UPDATE vocabulary_bank SET ipa='/ˈmɑː.kɪt/', example_en='She buys fresh fruit and vegetables at the market every morning.', example_vi='Cô ấy mua hoa quả và rau tươi ở chợ mỗi buổi sáng.' WHERE id='mv-pd-018';
UPDATE vocabulary_bank SET ipa='/nɪə/', example_en='The school is near the park, about five minutes on foot.', example_vi='Trường học gần công viên, khoảng năm phút đi bộ.' WHERE id='mv-pd-019';
UPDATE vocabulary_bank SET ipa='/ˈɒp.ə.zɪt/', example_en='The post office is directly opposite the bank.', example_vi='Bưu điện nằm đối diện trực tiếp với ngân hàng.' WHERE id='mv-pd-020';
UPDATE vocabulary_bank SET ipa='/pleɪs/', example_en='Paris is a wonderful place to visit in spring.', example_vi='Paris là một địa điểm tuyệt vời để thăm quan vào mùa xuân.' WHERE id='mv-pd-021';
UPDATE vocabulary_bank SET ipa='/ˈʃɒp.ɪŋ ˌsen.tə/', example_en='They spent the whole afternoon at the shopping centre.', example_vi='Họ dành cả buổi chiều ở trung tâm mua sắm.' WHERE id='mv-pd-022';
UPDATE vocabulary_bank SET ipa='/ˈspɔːts ˌsen.tə/', example_en='She goes to the sports centre to swim three times a week.', example_vi='Cô ấy đến trung tâm thể thao để bơi ba lần mỗi tuần.' WHERE id='mv-pd-023';
UPDATE vocabulary_bank SET ipa='/skweə/', example_en='There is a beautiful fountain in the main square.', example_vi='Có một đài phun nước đẹp ở quảng trường chính.' WHERE id='mv-pd-024';
UPDATE vocabulary_bank SET ipa='/ˈsteɪ.ʃən/', example_en='The train to the capital leaves from platform three.', example_vi='Tàu đến thủ đô xuất phát từ sân ga số ba.' WHERE id='mv-pd-025';
UPDATE vocabulary_bank SET ipa='/streɪt/', example_en='Go straight on until you reach the traffic lights.', example_vi='Đi thẳng cho đến khi bạn đến đèn giao thông.' WHERE id='mv-pd-026';
UPDATE vocabulary_bank SET ipa='/ˈsuː.pə.mɑː.kɪt/', example_en='She does her weekly shopping at the supermarket on Saturday.', example_vi='Cô ấy đi mua sắm hàng tuần ở siêu thị vào thứ Bảy.' WHERE id='mv-pd-027';
UPDATE vocabulary_bank SET ipa='/ˈswɪm.ɪŋ puːl/', example_en='The hotel has a heated outdoor swimming pool.', example_vi='Khách sạn có một bể bơi ngoài trời được sưởi ấm.' WHERE id='mv-pd-028';
UPDATE vocabulary_bank SET ipa='/ˈtaʊn ˌsen.tə/', example_en='The market is held every Saturday in the town centre.', example_vi='Phiên chợ diễn ra mỗi thứ Bảy ở trung tâm thị trấn.' WHERE id='mv-pd-029';
UPDATE vocabulary_bank SET ipa='/ˈeə.pɔːt/', example_en='We arrived at the airport two hours before the flight.', example_vi='Chúng tôi đến sân bay hai tiếng trước chuyến bay.' WHERE id='fl-pd-001';
UPDATE vocabulary_bank SET ipa='/bæŋk/', example_en='He went to the bank to withdraw some money.', example_vi='Anh ấy đến ngân hàng để rút tiền.' WHERE id='fl-pd-002';
UPDATE vocabulary_bank SET ipa='/brɪdʒ/', example_en='We walked over the bridge to reach the other side of the river.', example_vi='Chúng tôi đi qua cây cầu để sang bờ kia của sông.' WHERE id='fl-pd-003';
UPDATE vocabulary_bank SET ipa='/ˈkɑː.səl/', example_en='The castle was built more than five hundred years ago.', example_vi='Lâu đài được xây dựng cách đây hơn năm trăm năm.' WHERE id='fl-pd-004';
UPDATE vocabulary_bank SET ipa='/ˈkem.ɪst/', example_en='I got some medicine from the chemist for my sore throat.', example_vi='Tôi mua thuốc ở hiệu thuốc để trị đau họng.' WHERE id='fl-pd-005';
UPDATE vocabulary_bank SET ipa='/klʌb/', example_en='She joined the school drama club this term.', example_vi='Cô ấy tham gia câu lạc bộ kịch của trường kỳ này.' WHERE id='fl-pd-006';
UPDATE vocabulary_bank SET ipa='/ˈkɒl.ɪdʒ/', example_en='After school he wants to go to college to study engineering.', example_vi='Sau khi tốt nghiệp anh ấy muốn vào cao đẳng học kỹ thuật.' WHERE id='fl-pd-007';
UPDATE vocabulary_bank SET ipa='/ˈkɔː.nə/', example_en='Turn right at the corner of the street.', example_vi='Hãy rẽ phải ở góc đường.' WHERE id='fl-pd-008';
UPDATE vocabulary_bank SET ipa='/iːst/', example_en='The sun rises in the east every morning.', example_vi='Mặt trời mọc ở phía đông mỗi buổi sáng.' WHERE id='fl-pd-009';
UPDATE vocabulary_bank SET ipa='/ˈfæk.tər.i/', example_en='His father works in a car factory on the edge of town.', example_vi='Bố của anh ấy làm việc ở nhà máy sản xuất ô tô ven thành phố.' WHERE id='fl-pd-010';
UPDATE vocabulary_bank SET ipa='/ˈfaɪə ˌsteɪ.ʃən/', example_en='The fire station is on the main road out of town.', example_vi='Trạm cứu hỏa nằm trên con đường chính ra khỏi thành phố.' WHERE id='fl-pd-011';
UPDATE vocabulary_bank SET ipa='/frʌnt/', example_en='Please meet me at the front of the school at three o''clock.', example_vi='Hãy gặp tôi ở phía trước trường lúc ba giờ.' WHERE id='fl-pd-012';
UPDATE vocabulary_bank SET ipa='/ɡet tuː/', example_en='How do you get to school every day?', example_vi='Bạn đến trường bằng cách nào mỗi ngày?' WHERE id='fl-pd-013';
UPDATE vocabulary_bank SET ipa='/həʊˈtel/', example_en='We stayed in a small hotel near the beach for a week.', example_vi='Chúng tôi ở trong một khách sạn nhỏ gần bãi biển một tuần.' WHERE id='fl-pd-014';
UPDATE vocabulary_bank SET ipa='/ˈkɪl.ə.miː.tə/', example_en='The village is three kilometres from the nearest town.', example_vi='Ngôi làng cách thị trấn gần nhất ba kilômét.' WHERE id='fl-pd-015';
UPDATE vocabulary_bank SET ipa='/left/', example_en='Turn left at the traffic lights and walk for two minutes.', example_vi='Rẽ trái ở đèn giao thông và đi bộ hai phút.' WHERE id='fl-pd-016';
UPDATE vocabulary_bank SET ipa='/ˈlʌn.dən/', example_en='London is the capital city of England and one of the largest cities in Europe.', example_vi='London là thủ đô của Anh và một trong những thành phố lớn nhất châu Âu.' WHERE id='fl-pd-017';
UPDATE vocabulary_bank SET ipa='/ˈmɪd.əl/', example_en='She stood in the middle of the room and looked around.', example_vi='Cô ấy đứng ở giữa căn phòng và nhìn xung quanh.' WHERE id='fl-pd-018';
UPDATE vocabulary_bank SET ipa='/mjuːˈzɪ.əm/', example_en='We visited a museum about ancient history during our school trip.', example_vi='Chúng tôi tham quan bảo tàng về lịch sử cổ đại trong chuyến đi học.' WHERE id='fl-pd-019';
UPDATE vocabulary_bank SET ipa='/nɔːθ/', example_en='Drive north for about fifty kilometres to reach the lake.', example_vi='Lái xe về phía bắc khoảng năm mươi kilômét để đến hồ.' WHERE id='fl-pd-020';
UPDATE vocabulary_bank SET ipa='/ˈəʊ.və/', example_en='The bridge goes over the river in the valley.', example_vi='Cây cầu bắc qua con sông ở thung lũng.' WHERE id='fl-pd-021';
UPDATE vocabulary_bank SET ipa='/pɑːθ/', example_en='Follow the path through the forest to reach the waterfall.', example_vi='Đi theo con đường mòn qua khu rừng để đến thác nước.' WHERE id='fl-pd-022';
UPDATE vocabulary_bank SET ipa='/pəˈliːs ˌsteɪ.ʃən/', example_en='She reported the theft at the local police station.', example_vi='Cô ấy trình báo vụ trộm tại đồn cảnh sát địa phương.' WHERE id='fl-pd-023';
UPDATE vocabulary_bank SET ipa='/ˈpəʊst ˌɒf.ɪs/', example_en='I need to go to the post office to send this parcel.', example_vi='Tôi cần đến bưu điện để gửi kiện hàng này.' WHERE id='fl-pd-024';
UPDATE vocabulary_bank SET ipa='/ˈres.tɒ.rɒnt/', example_en='We had dinner at a nice Italian restaurant in the city centre.', example_vi='Chúng tôi ăn tối ở một nhà hàng Ý đẹp trong trung tâm thành phố.' WHERE id='fl-pd-025';
UPDATE vocabulary_bank SET ipa='/raɪt/', example_en='Turn right after the traffic lights and the school is on your left.', example_vi='Rẽ phải sau đèn giao thông và trường học ở bên trái bạn.' WHERE id='fl-pd-026';
UPDATE vocabulary_bank SET ipa='/ˈskaɪ.skreɪ.pə/', example_en='The skyscraper in the centre of the city has one hundred floors.', example_vi='Tòa nhà chọc trời ở trung tâm thành phố có một trăm tầng.' WHERE id='fl-pd-027';
UPDATE vocabulary_bank SET ipa='/saʊθ/', example_en='They drove south towards the coast for the holiday.', example_vi='Họ lái xe về phía nam hướng về bờ biển để nghỉ hè.' WHERE id='fl-pd-028';
UPDATE vocabulary_bank SET ipa='/ˈsteɪ.di.əm/', example_en='Thousands of fans filled the stadium to watch the match.', example_vi='Hàng nghìn người hâm mộ lấp đầy sân vận động để xem trận đấu.' WHERE id='fl-pd-029';
UPDATE vocabulary_bank SET ipa='/streɪt ɒn/', example_en='Go straight on past the church and then turn left.', example_vi='Đi thẳng qua nhà thờ rồi rẽ trái.' WHERE id='fl-pd-030';
UPDATE vocabulary_bank SET ipa='/ˈθɪə.tə/', example_en='We saw an amazing play at the theatre last Saturday.', example_vi='Chúng tôi xem một vở kịch tuyệt vời ở nhà hát thứ Bảy vừa rồi.' WHERE id='fl-pd-031';
UPDATE vocabulary_bank SET ipa='/juːˈnɪ.və.sɪ.ti/', example_en='She worked very hard to get a place at university.', example_vi='Cô ấy đã cố gắng rất nhiều để có được một chỗ ở trường đại học.' WHERE id='fl-pd-032';
UPDATE vocabulary_bank SET ipa='/weɪ/', example_en='Could you tell me the way to the nearest bus stop?', example_vi='Bạn có thể chỉ đường đến trạm xe buýt gần nhất không?' WHERE id='fl-pd-033';
UPDATE vocabulary_bank SET ipa='/west/', example_en='The sun sets in the west every evening.', example_vi='Mặt trời lặn ở phía tây mỗi buổi chiều.' WHERE id='fl-pd-034';

-- Total: 79 rows
