-- 0022b: Fix ipa+examples+translations — time, toys, transport (133 words)
-- Generated: 2026-05-08T02:36:58.604Z

UPDATE vocabulary_bank SET ipa='/ˌæf.tɚˈnuːn/', example_en='I usually play with my friends in the afternoon.', example_vi='Tôi thường chơi với bạn bè vào buổi chiều.', translation_vi='buổi chiều' WHERE id='st-ti-001';
UPDATE vocabulary_bank SET ipa='/ˈbɜːθ.deɪ/', example_en='When is your birthday?', example_vi='Sinh nhật của bạn khi nào?', translation_vi='sinh nhật' WHERE id='st-ti-002';
UPDATE vocabulary_bank SET ipa='/klɒk/', example_en='Look at the clock, it is time for bed.', example_vi='Nhìn đồng hồ kìa, đến giờ đi ngủ rồi.', translation_vi='đồng hồ (treo tường)' WHERE id='st-ti-003';
UPDATE vocabulary_bank SET ipa='/deɪ/', example_en='There are seven days in a week.', example_vi='Có bảy ngày trong một tuần.', translation_vi='ngày' WHERE id='st-ti-004';
UPDATE vocabulary_bank SET ipa='/ˈiːv.nɪŋ/', example_en='We have dinner together every evening.', example_vi='Chúng tôi ăn tối cùng nhau mỗi buổi tối.', translation_vi='buổi tối' WHERE id='st-ti-005';
UPDATE vocabulary_bank SET ipa='/ɪn/', example_en='My birthday is in June.', example_vi='Sinh nhật của tôi vào tháng Sáu.', translation_vi='vào (tháng/năm)' WHERE id='st-ti-006';
UPDATE vocabulary_bank SET ipa='/ˈmɔː.nɪŋ/', example_en='I wake up early in the morning.', example_vi='Tôi thức dậy sớm vào buổi sáng.', translation_vi='buổi sáng' WHERE id='st-ti-007';
UPDATE vocabulary_bank SET ipa='/naɪt/', example_en='The stars are very bright at night.', example_vi='Những vì sao rất sáng vào ban đêm.', translation_vi='ban đêm' WHERE id='st-ti-008';
UPDATE vocabulary_bank SET ipa='/təˈdeɪ/', example_en='Today is a beautiful sunny day.', example_vi='Hôm nay là một ngày nắng đẹp.', translation_vi='hôm nay' WHERE id='st-ti-009';
UPDATE vocabulary_bank SET ipa='/wɒtʃ/', example_en='My grandfather gave me a new watch.', example_vi='Ông tôi đã tặng tôi một chiếc đồng hồ đeo tay mới.', translation_vi='đồng hồ đeo tay' WHERE id='st-ti-010';
UPDATE vocabulary_bank SET ipa='/jɪər/', example_en='There are twelve months in a year.', example_vi='Có mười hai tháng trong một năm.', translation_vi='năm' WHERE id='st-ti-011';
UPDATE vocabulary_bank SET ipa='/ˈɑːf.tər/', example_en='We will go to the park after school.', example_vi='Chúng ta sẽ đến công viên sau giờ học.', translation_vi='sau khi' WHERE id='mv-ti-001';
UPDATE vocabulary_bank SET ipa='/ˈɔːl.weɪz/', example_en='He always brushes his teeth before bed.', example_vi='Anh ấy luôn đánh răng trước khi ngủ.', translation_vi='luôn luôn' WHERE id='mv-ti-002';
UPDATE vocabulary_bank SET ipa='/bɪˈfɔːr/', example_en='Wash your hands before you eat.', example_vi='Hãy rửa tay trước khi bạn ăn.', translation_vi='trước khi' WHERE id='mv-ti-003';
UPDATE vocabulary_bank SET ipa='/ˈev.ri/', example_en='I drink a glass of milk every day.', example_vi='Tôi uống một ly sữa mỗi ngày.', translation_vi='mỗi' WHERE id='mv-ti-004';
UPDATE vocabulary_bank SET ipa='/ˈnev.ər/', example_en='I never eat too much candy.', example_vi='Tôi không bao giờ ăn quá nhiều kẹo.', translation_vi='không bao giờ' WHERE id='mv-ti-005';
UPDATE vocabulary_bank SET ipa='/əˈklɒk/', example_en='Our class starts at eight o’clock.', example_vi='Lớp học của chúng tôi bắt đầu lúc tám giờ đúng.', translation_vi='giờ đúng' WHERE id='mv-ti-006';
UPDATE vocabulary_bank SET ipa='/ˈsʌm.taɪmz/', example_en='Sometimes we go out for dinner on Fridays.', example_vi='Thỉnh thoảng chúng tôi ra ngoài ăn tối vào thứ Sáu.', translation_vi='thỉnh thoảng' WHERE id='mv-ti-007';
UPDATE vocabulary_bank SET ipa='/wiːk/', example_en='I am going on holiday next week.', example_vi='Tôi sẽ đi nghỉ vào tuần tới.', translation_vi='tuần' WHERE id='mv-ti-008';
UPDATE vocabulary_bank SET ipa='/ˌwiːkˈend/', example_en='We often visit our grandparents at the weekend.', example_vi='Chúng tôi thường đến thăm ông bà vào cuối tuần.', translation_vi='cuối tuần' WHERE id='mv-ti-009';
UPDATE vocabulary_bank SET ipa='/ˈjes.tə.deɪ/', example_en='It rained a lot yesterday.', example_vi='Trời đã mưa rất nhiều vào hôm qua.', translation_vi='hôm qua' WHERE id='mv-ti-010';
UPDATE vocabulary_bank SET ipa='/ˈmʌn.deɪ/', example_en='Monday is the first day of the school week.', example_vi='Thứ Hai là ngày đầu tiên của tuần học.', translation_vi='thứ Hai' WHERE id='mv-ti-011';
UPDATE vocabulary_bank SET ipa='/ˈtjuːz.deɪ/', example_en='We have a math test on Tuesday.', example_vi='Chúng tôi có bài kiểm tra toán vào thứ Ba.', translation_vi='thứ Ba' WHERE id='mv-ti-012';
UPDATE vocabulary_bank SET ipa='/ˈwenz.deɪ/', example_en='Wednesday is the middle of the week.', example_vi='Thứ Tư là ngày giữa tuần.', translation_vi='thứ Tư' WHERE id='mv-ti-013';
UPDATE vocabulary_bank SET ipa='/ˈθɜːz.deɪ/', example_en='I go to swimming lessons every Thursday.', example_vi='Tôi đi học bơi mỗi thứ Năm.', translation_vi='thứ Năm' WHERE id='mv-ti-014';
UPDATE vocabulary_bank SET ipa='/ˈfraɪ.deɪ/', example_en='Friday is my favourite day of the week.', example_vi='Thứ Sáu là ngày tôi yêu thích nhất trong tuần.', translation_vi='thứ Sáu' WHERE id='mv-ti-015';
UPDATE vocabulary_bank SET ipa='/ˈsæt.ə.deɪ/', example_en='We usually go shopping on Saturday.', example_vi='Chúng tôi thường đi mua sắm vào thứ Bảy.', translation_vi='thứ Bảy' WHERE id='mv-ti-016';
UPDATE vocabulary_bank SET ipa='/ˈsʌn.deɪ/', example_en='Sunday is a day for rest and family.', example_vi='Chủ nhật là ngày để nghỉ ngơi và dành cho gia đình.', translation_vi='Chủ nhật' WHERE id='mv-ti-017';
UPDATE vocabulary_bank SET ipa='/ˌeɪˈem/', example_en='The train leaves at 9 a.m.', example_vi='Chuyến tàu khởi hành lúc 9 giờ sáng.', translation_vi='sáng (trước buổi trưa)' WHERE id='fl-ti-001';
UPDATE vocabulary_bank SET ipa='/ˈɑːf.tər/', example_en='We went to the cafe after the movie finished.', example_vi='Chúng tôi đã đi đến quán cà phê sau khi bộ phim kết thúc.', translation_vi='sau khi' WHERE id='fl-ti-002';
UPDATE vocabulary_bank SET ipa='/əˈɡəʊ/', example_en='We moved to this house two years ago.', example_vi='Chúng tôi đã chuyển đến ngôi nhà này hai năm trước.', translation_vi='trước đây / cách đây' WHERE id='fl-ti-003';
UPDATE vocabulary_bank SET ipa='/ˈɔː.təm/', example_en='The leaves change colour and fall off the trees in autumn.', example_vi='Lá cây đổi màu và rụng vào mùa thu.', translation_vi='mùa thu (Anh)' WHERE id='fl-ti-004';
UPDATE vocabulary_bank SET ipa='/bɪˈfɔːr/', example_en='Please complete your work before Friday.', example_vi='Vui lòng hoàn thành công việc của bạn trước thứ Sáu.', translation_vi='trước / trước khi' WHERE id='fl-ti-005';
UPDATE vocabulary_bank SET ipa='/ˈkæl.ən.dər/', example_en='I marked my friend’s birthday on the calendar.', example_vi='Tôi đã đánh dấu ngày sinh nhật bạn mình trên lịch.', translation_vi='lịch' WHERE id='fl-ti-006';
UPDATE vocabulary_bank SET ipa='/ˈsen.tʃər.i/', example_en='We are living in the 21st century.', example_vi='Chúng ta đang sống ở thế kỷ 21.', translation_vi='thế kỷ' WHERE id='fl-ti-007';
UPDATE vocabulary_bank SET ipa='/deɪt/', example_en='What is the date today?', example_vi='Hôm nay là ngày mấy?', translation_vi='ngày tháng' WHERE id='fl-ti-008';
UPDATE vocabulary_bank SET ipa='/ˈɜː.li/', example_en='He likes to wake up early in the morning.', example_vi='Anh ấy thích thức dậy sớm vào buổi sáng.', translation_vi='sớm' WHERE id='fl-ti-009';
UPDATE vocabulary_bank SET ipa='/end/', example_en='We watched the movie until the very end.', example_vi='Chúng tôi đã xem bộ phim cho đến tận phút cuối cùng.', translation_vi='sự kết thúc / cuối' WHERE id='fl-ti-010';
UPDATE vocabulary_bank SET ipa='/fɔːl/', example_en='It is getting cooler because fall is here.', example_vi='Trời đang lạnh dần vì mùa thu đã đến.', translation_vi='mùa thu (Mỹ)' WHERE id='fl-ti-011';
UPDATE vocabulary_bank SET ipa='/ˈfjuː.tʃər/', example_en='I hope to become a doctor in the future.', example_vi='Tôi hy vọng sẽ trở thành bác sĩ trong tương lai.', translation_vi='tương lai' WHERE id='fl-ti-012';
UPDATE vocabulary_bank SET ipa='/aʊər/', example_en='The journey takes about one hour by car.', example_vi='Chuyến đi mất khoảng một giờ bằng ô tô.', translation_vi='giờ' WHERE id='fl-ti-013';
UPDATE vocabulary_bank SET ipa='/haʊ lɒŋ/', example_en='How long does it take to travel to London?', example_vi='Mất bao lâu để đi đến London?', translation_vi='bao lâu' WHERE id='fl-ti-014';
UPDATE vocabulary_bank SET ipa='/leɪt/', example_en='Hurry up or we will be late for school!', example_vi='Nhanh lên hoặc chúng ta sẽ bị muộn học!', translation_vi='muộn / trễ' WHERE id='fl-ti-015';
UPDATE vocabulary_bank SET ipa='/ˈleɪ.tər/', example_en='I cannot talk now, I will call you later.', example_vi='Bây giờ tôi không thể nói chuyện, tôi sẽ gọi cho bạn sau.', translation_vi='sau đó / muộn hơn' WHERE id='fl-ti-016';
UPDATE vocabulary_bank SET ipa='/ˌmɪdˈdeɪ/', example_en='We stopped working at midday to have lunch.', example_vi='Chúng tôi ngừng làm việc vào buổi trưa để ăn trưa.', translation_vi='giữa trưa' WHERE id='fl-ti-017';
UPDATE vocabulary_bank SET ipa='/ˈmɪd.naɪt/', example_en='The party finished long after midnight.', example_vi='Bữa tiệc kết thúc rất lâu sau nửa đêm.', translation_vi='nửa đêm' WHERE id='fl-ti-018';
UPDATE vocabulary_bank SET ipa='/ˈmɪn.ɪt/', example_en='Boil the egg for exactly three minutes.', example_vi='Luộc trứng chính xác trong ba phút.', translation_vi='phút' WHERE id='fl-ti-019';
UPDATE vocabulary_bank SET ipa='/mʌnθ/', example_en='July is my favourite month of the year.', example_vi='Tháng Bảy là tháng tôi yêu thích nhất trong năm.', translation_vi='tháng' WHERE id='fl-ti-020';
UPDATE vocabulary_bank SET ipa='/ˌpiːˈem/', example_en='Our meeting is at 3 p.m. this afternoon.', example_vi='Cuộc họp của chúng ta vào lúc 3 giờ chiều nay.', translation_vi='chiều (sau buổi trưa)' WHERE id='fl-ti-021';
UPDATE vocabulary_bank SET ipa='/pɑːst/', example_en='It is half past four.', example_vi='Bây giờ là bốn giờ rưỡi.', translation_vi='qua (giờ) / quá khứ' WHERE id='fl-ti-022';
UPDATE vocabulary_bank SET ipa='/ˈkwɔː.tər/', example_en='It is a quarter to nine, time to leave.', example_vi='Bây giờ là chín giờ kém mười lăm, đến lúc rời đi.', translation_vi='mười lăm phút / một phần tư' WHERE id='fl-ti-023';
UPDATE vocabulary_bank SET ipa='/sprɪŋ/', example_en='Lots of beautiful flowers bloom in spring.', example_vi='Nhiều bông hoa đẹp nở rộ vào mùa xuân.', translation_vi='mùa xuân' WHERE id='fl-ti-024';
UPDATE vocabulary_bank SET ipa='/ˈsʌm.ər/', example_en='We love going to the beach in summer.', example_vi='Chúng tôi thích đi biển vào mùa hè.', translation_vi='mùa hè' WHERE id='fl-ti-025';
UPDATE vocabulary_bank SET ipa='/taɪm/', example_en='Do you know what time the movie starts?', example_vi='Bạn có biết mấy giờ bộ phim bắt đầu không?', translation_vi='thời gian / giờ' WHERE id='fl-ti-026';
UPDATE vocabulary_bank SET ipa='/təˈmɒr.əʊ/', example_en='I will see you tomorrow morning at school.', example_vi='Tôi sẽ gặp bạn sáng mai ở trường.', translation_vi='ngày mai' WHERE id='fl-ti-027';
UPDATE vocabulary_bank SET ipa='/təˈnaɪt/', example_en='We are having a party tonight.', example_vi='Chúng tôi sẽ tổ chức một bữa tiệc tối nay.', translation_vi='tối nay' WHERE id='fl-ti-028';
UPDATE vocabulary_bank SET ipa='/ˈwɪn.tər/', example_en='It snows a lot in winter in some countries.', example_vi='Trời có rất nhiều tuyết vào mùa đông ở một số quốc gia.', translation_vi='mùa đông' WHERE id='fl-ti-029';
UPDATE vocabulary_bank SET ipa='/ˈdʒæn.ju.ə.ri/', example_en='January is the first month of the new year.', example_vi='Tháng Một là tháng đầu tiên của năm mới.', translation_vi='tháng Một' WHERE id='fl-ti-030';
UPDATE vocabulary_bank SET ipa='/ˈfeb.ru.ər.i/', example_en='February is the shortest month.', example_vi='Tháng Hai là tháng ngắn nhất.', translation_vi='tháng Hai' WHERE id='fl-ti-031';
UPDATE vocabulary_bank SET ipa='/mɑːtʃ/', example_en='The spring flowers start to grow in March.', example_vi='Hoa mùa xuân bắt đầu mọc vào tháng Ba.', translation_vi='tháng Ba' WHERE id='fl-ti-032';
UPDATE vocabulary_bank SET ipa='/ˈeɪ.prəl/', example_en='April showers bring May flowers.', example_vi='Những cơn mưa rào tháng Tư mang đến những bông hoa tháng Năm.', translation_vi='tháng Tư' WHERE id='fl-ti-033';
UPDATE vocabulary_bank SET ipa='/meɪ/', example_en='My birthday is in the month of May.', example_vi='Sinh nhật của tôi vào tháng Năm.', translation_vi='tháng Năm' WHERE id='fl-ti-034';
UPDATE vocabulary_bank SET ipa='/dʒuːn/', example_en='School usually ends in late June.', example_vi='Trường học thường kết thúc vào cuối tháng Sáu.', translation_vi='tháng Sáu' WHERE id='fl-ti-035';
UPDATE vocabulary_bank SET ipa='/dʒuˈlaɪ/', example_en='July is often very hot and sunny.', example_vi='Tháng Bảy thường rất nóng và nhiều nắng.', translation_vi='tháng Bảy' WHERE id='fl-ti-036';
UPDATE vocabulary_bank SET ipa='/ˈɔː.ɡəst/', example_en='We are going on holiday in August.', example_vi='Chúng tôi sẽ đi nghỉ vào tháng Tám.', translation_vi='tháng Tám' WHERE id='fl-ti-037';
UPDATE vocabulary_bank SET ipa='/sepˈtem.bər/', example_en='Students go back to school in September.', example_vi='Học sinh đi học lại vào tháng Chín.', translation_vi='tháng Chín' WHERE id='fl-ti-038';
UPDATE vocabulary_bank SET ipa='/ɒkˈtəʊ.bər/', example_en='Halloween is at the end of October.', example_vi='Halloween diễn ra vào cuối tháng Mười.', translation_vi='tháng Mười' WHERE id='fl-ti-039';
UPDATE vocabulary_bank SET ipa='/nəʊˈvem.bər/', example_en='It starts to get very cold in November.', example_vi='Trời bắt đầu rất lạnh vào tháng Mười Một.', translation_vi='tháng Mười Một' WHERE id='fl-ti-040';
UPDATE vocabulary_bank SET ipa='/dɪˈsem.bər/', example_en='We celebrate Christmas in December.', example_vi='Chúng tôi mừng Giáng sinh vào tháng Mười Hai.', translation_vi='tháng Mười Hai' WHERE id='fl-ti-041';
UPDATE vocabulary_bank SET ipa='/ˈeɪ.li.ən/', example_en='The toy alien has green skin and big eyes.', example_vi='Món đồ chơi người ngoài hành tinh có da xanh và mắt to.', translation_vi='người ngoài hành tinh' WHERE id='st-to-001';
UPDATE vocabulary_bank SET ipa='/bɔːl/', example_en='He threw the bouncy ball to his friend.', example_vi='Cậu bé ném quả bóng nảy cho bạn mình.', translation_vi='quả bóng' WHERE id='st-to-002';
UPDATE vocabulary_bank SET ipa='/bəˈluːn/', example_en='They decorated the room with red balloons.', example_vi='Họ đã trang trí căn phòng bằng những quả bóng bay màu đỏ.', translation_vi='bóng bay' WHERE id='st-to-003';
UPDATE vocabulary_bank SET ipa='/ˈbeɪs.bɔːl/', example_en='We play baseball in the park on weekends.', example_vi='Chúng tôi chơi bóng chày ở công viên vào cuối tuần.', translation_vi='bóng chày' WHERE id='st-to-004';
UPDATE vocabulary_bank SET ipa='/ˈbɑː.skɪt.bɔːl/', example_en='He got a new basketball for his birthday.', example_vi='Anh ấy được tặng một quả bóng rổ mới dịp sinh nhật.', translation_vi='bóng rổ' WHERE id='st-to-005';
UPDATE vocabulary_bank SET ipa='/baɪk/', example_en='She learned to ride a bike without training wheels.', example_vi='Cô bé đã học cách đi xe đạp không có bánh xe phụ.', translation_vi='xe đạp' WHERE id='st-to-006';
UPDATE vocabulary_bank SET ipa='/ˈbɔːd ˌɡeɪm/', example_en='We like to play a board game on rainy days.', example_vi='Chúng tôi thích chơi trò chơi bàn cờ vào những ngày mưa.', translation_vi='trò chơi bàn cờ (cờ bàn)' WHERE id='st-to-007';
UPDATE vocabulary_bank SET ipa='/bəʊt/', example_en='The boy put his toy boat in the water.', example_vi='Cậu bé đặt con thuyền đồ chơi của mình xuống nước.', translation_vi='con thuyền' WHERE id='st-to-008';
UPDATE vocabulary_bank SET ipa='/kɑːr/', example_en='He has a big collection of toy cars.', example_vi='Cậu bé có một bộ sưu tập xe ô tô đồ chơi lớn.', translation_vi='ô tô' WHERE id='st-to-009';
UPDATE vocabulary_bank SET ipa='/dɒl/', example_en='The little girl is dressing up her doll.', example_vi='Bé gái đang mặc đồ cho búp bê của mình.', translation_vi='búp bê' WHERE id='st-to-010';
UPDATE vocabulary_bank SET ipa='/ˈfʊt.bɔːl/', example_en='They kicked the football across the field.', example_vi='Họ đá quả bóng đá ngang qua cánh đồng.', translation_vi='quả bóng đá' WHERE id='st-to-011';
UPDATE vocabulary_bank SET ipa='/ɡeɪm/', example_en='This new computer game is very fun.', example_vi='Trò chơi máy tính mới này rất vui.', translation_vi='trò chơi' WHERE id='st-to-012';
UPDATE vocabulary_bank SET ipa='/ˈhel.ɪˌkɒp.tər/', example_en='The toy helicopter can fly up to the ceiling.', example_vi='Chiếc trực thăng đồ chơi có thể bay lên tận trần nhà.', translation_vi='trực thăng' WHERE id='st-to-013';
UPDATE vocabulary_bank SET ipa='/ˈlɒr.i/', example_en='He pushes the toy lorry along the floor.', example_vi='Cậu bé đẩy chiếc xe tải đồ chơi dọc theo sàn nhà.', translation_vi='xe tải' WHERE id='st-to-014';
UPDATE vocabulary_bank SET ipa='/ˈmɒn.stər/', example_en='The toy monster has three eyes and purple fur.', example_vi='Món đồ chơi quái vật có ba mắt và lông màu tím.', translation_vi='quái vật' WHERE id='st-to-015';
UPDATE vocabulary_bank SET ipa='/ˈməʊ.tə.baɪk/', example_en='My brother has a red toy motorbike.', example_vi='Em trai tôi có một chiếc xe máy đồ chơi màu đỏ.', translation_vi='xe máy' WHERE id='st-to-016';
UPDATE vocabulary_bank SET ipa='/pleɪn/', example_en='The toy plane zooms across the room.', example_vi='Chiếc máy bay đồ chơi phóng vèo vèo quanh phòng.', translation_vi='máy bay' WHERE id='st-to-017';
UPDATE vocabulary_bank SET ipa='/ˈrəʊ.bɒt/', example_en='The robot can walk and talk when you press a button.', example_vi='Người máy có thể đi và nói khi bạn nhấn nút.', translation_vi='người máy' WHERE id='st-to-018';
UPDATE vocabulary_bank SET ipa='/ˈsɒk.ər/', example_en='They play soccer with a soft ball indoors.', example_vi='Họ chơi bóng đá (Mỹ) với quả bóng mềm trong nhà.', translation_vi='bóng đá (Mỹ)' WHERE id='st-to-019';
UPDATE vocabulary_bank SET ipa='/ˈted.i/', example_en='She sleeps with her favourite teddy bear every night.', example_vi='Cô bé ngủ với gấu bông yêu thích của mình mỗi đêm.', translation_vi='gấu bông' WHERE id='st-to-020';
UPDATE vocabulary_bank SET ipa='/tɔɪ/', example_en='Please put away every toy when you finish playing.', example_vi='Vui lòng cất gọn mọi đồ chơi khi bạn chơi xong.', translation_vi='đồ chơi' WHERE id='st-to-021';
UPDATE vocabulary_bank SET ipa='/treɪn/', example_en='The wooden train goes around the track.', example_vi='Chiếc xe lửa bằng gỗ chạy quanh đường ray.', translation_vi='xe lửa' WHERE id='st-to-022';
UPDATE vocabulary_bank SET ipa='/trʌk/', example_en='The yellow toy truck carries sand in the sandbox.', example_vi='Chiếc xe tải đồ chơi màu vàng chở cát trong hộp cát.', translation_vi='xe tải (Mỹ)' WHERE id='st-to-023';
UPDATE vocabulary_bank SET ipa='/ˈmɒd.əl/', example_en='He built a small model of an airplane.', example_vi='Cậu bé đã ráp một mô hình nhỏ của một chiếc máy bay.', translation_vi='mô hình' WHERE id='mv-to-001';
UPDATE vocabulary_bank SET ipa='/baɪk/', example_en='He rides his bike to the park.', example_vi='Anh ấy đạp xe đến công viên.', translation_vi='xe đạp' WHERE id='st-tr-001';
UPDATE vocabulary_bank SET ipa='/bəʊt/', example_en='We took a small boat across the river.', example_vi='Chúng tôi đi một chiếc thuyền nhỏ qua sông.', translation_vi='con thuyền' WHERE id='st-tr-002';
UPDATE vocabulary_bank SET ipa='/bʌs/', example_en='I take the bus to school every morning.', example_vi='Tôi đi xe buýt đến trường mỗi sáng.', translation_vi='xe buýt' WHERE id='st-tr-003';
UPDATE vocabulary_bank SET ipa='/kɑːr/', example_en='My parents drive a blue car.', example_vi='Bố mẹ tôi lái một chiếc ô tô màu xanh.', translation_vi='ô tô' WHERE id='st-tr-004';
UPDATE vocabulary_bank SET ipa='/draɪv/', example_en='My mother will drive us to the supermarket.', example_vi='Mẹ sẽ lái xe chở chúng tôi đến siêu thị.', translation_vi='lái xe' WHERE id='st-tr-005';
UPDATE vocabulary_bank SET ipa='/flaɪ/', example_en='Birds can fly high in the sky.', example_vi='Những chú chim có thể bay cao trên bầu trời.', translation_vi='bay' WHERE id='st-tr-006';
UPDATE vocabulary_bank SET ipa='/ɡəʊ/', example_en='We will go to the zoo by bus tomorrow.', example_vi='Ngày mai chúng tôi sẽ đi đến sở thú bằng xe buýt.', translation_vi='đi' WHERE id='st-tr-007';
UPDATE vocabulary_bank SET ipa='/ˈhel.ɪˌkɒp.tər/', example_en='The helicopter landed safely on the roof.', example_vi='Chiếc trực thăng đã hạ cánh an toàn trên mái nhà.', translation_vi='trực thăng' WHERE id='st-tr-008';
UPDATE vocabulary_bank SET ipa='/ˈlɒr.i/', example_en='The lorry is carrying a lot of heavy boxes.', example_vi='Chiếc xe tải đang chở rất nhiều hộp nặng.', translation_vi='xe tải' WHERE id='st-tr-009';
UPDATE vocabulary_bank SET ipa='/pleɪn/', example_en='We will travel to London by plane.', example_vi='Chúng tôi sẽ bay đến London bằng máy bay.', translation_vi='máy bay' WHERE id='st-tr-010';
UPDATE vocabulary_bank SET ipa='/raɪd/', example_en='Can you ride a horse?', example_vi='Bạn có biết cưỡi ngựa không?', translation_vi='cưỡi / đi xe' WHERE id='st-tr-011';
UPDATE vocabulary_bank SET ipa='/rʌn/', example_en='The dog runs very fast.', example_vi='Con chó chạy rất nhanh.', translation_vi='chạy' WHERE id='st-tr-012';
UPDATE vocabulary_bank SET ipa='/ʃɪp/', example_en='The big ship is sailing across the ocean.', example_vi='Con tàu lớn đang băng qua đại dương.', translation_vi='tàu thủy' WHERE id='st-tr-013';
UPDATE vocabulary_bank SET ipa='/swɪm/', example_en='Fish swim in the water.', example_vi='Cá bơi trong nước.', translation_vi='bơi' WHERE id='st-tr-014';
UPDATE vocabulary_bank SET ipa='/trʌk/', example_en='A big truck is driving down the street.', example_vi='Một chiếc xe tải lớn đang chạy trên đường.', translation_vi='xe tải (Mỹ)' WHERE id='st-tr-015';
UPDATE vocabulary_bank SET ipa='/ˈbʌs ˌsteɪ.ʃən/', example_en='We waited for our bus at the main bus station.', example_vi='Chúng tôi đợi xe buýt của mình ở bến xe buýt trung tâm.', translation_vi='bến xe buýt lớn' WHERE id='mv-tr-001';
UPDATE vocabulary_bank SET ipa='/ˈbʌs ˌstɒp/', example_en='There is a bus stop right outside our house.', example_vi='Có một trạm xe buýt ngay bên ngoài nhà chúng tôi.', translation_vi='trạm xe buýt' WHERE id='mv-tr-002';
UPDATE vocabulary_bank SET ipa='/draɪv/', example_en='The long drive to the beach took three hours.', example_vi='Chuyến lái xe dài đến bãi biển mất ba giờ.', translation_vi='chuyến đi (bằng xe)' WHERE id='mv-tr-003';
UPDATE vocabulary_bank SET ipa='/ˈdraɪ.vər/', example_en='The bus driver is very friendly.', example_vi='Bác tài xế xe buýt rất thân thiện.', translation_vi='tài xế' WHERE id='mv-tr-004';
UPDATE vocabulary_bank SET ipa='/raɪd/', example_en='I enjoyed the roller coaster ride at the funfair.', example_vi='Tôi rất thích chuyến đi tàu lượn siêu tốc ở hội chợ.', translation_vi='chuyến đi' WHERE id='mv-tr-005';
UPDATE vocabulary_bank SET ipa='/ˈsteɪ.ʃən/', example_en='The train leaves the station at ten o’clock.', example_vi='Chuyến tàu rời nhà ga lúc mười giờ.', translation_vi='nhà ga' WHERE id='mv-tr-006';
UPDATE vocabulary_bank SET ipa='/ˈtɪk.ɪt/', example_en='You must buy a ticket before getting on the train.', example_vi='Bạn phải mua vé trước khi lên tàu.', translation_vi='vé' WHERE id='mv-tr-007';
UPDATE vocabulary_bank SET ipa='/ˈtræk.tər/', example_en='The farmer uses a tractor to pull heavy loads.', example_vi='Người nông dân dùng máy kéo để kéo vật nặng.', translation_vi='máy kéo' WHERE id='mv-tr-008';
UPDATE vocabulary_bank SET ipa='/trɪp/', example_en='Our family went on a trip to the mountains.', example_vi='Gia đình chúng tôi đã đi một chuyến đến vùng núi.', translation_vi='chuyến đi' WHERE id='mv-tr-009';
UPDATE vocabulary_bank SET ipa='/ˈæm.bjə.ləns/', example_en='The ambulance took the sick man to the hospital.', example_vi='Xe cứu thương đã đưa người đàn ông bệnh đến bệnh viện.', translation_vi='xe cứu thương' WHERE id='fl-tr-001';
UPDATE vocabulary_bank SET ipa='/ˈbaɪ.sɪ.kəl/', example_en='He rides his bicycle to work every day.', example_vi='Anh ấy đạp xe đến chỗ làm mỗi ngày.', translation_vi='xe đạp' WHERE id='fl-tr-002';
UPDATE vocabulary_bank SET ipa='/ˈfaɪər ˌen.dʒɪn/', example_en='The red fire engine rushed to the burning building.', example_vi='Chiếc xe cứu hỏa màu đỏ vội vã lao đến tòa nhà đang cháy.', translation_vi='xe cứu hỏa' WHERE id='fl-tr-003';
UPDATE vocabulary_bank SET ipa='/ˈdʒɜː.ni/', example_en='The long train journey was very tiring.', example_vi='Chuyến đi tàu dài rất mệt mỏi.', translation_vi='chuyến hành trình' WHERE id='fl-tr-004';
UPDATE vocabulary_bank SET ipa='/lɪft/', example_en='Let’s take the lift to the fifth floor.', example_vi='Chúng ta hãy đi thang máy lên tầng năm.', translation_vi='thang máy' WHERE id='fl-tr-005';
UPDATE vocabulary_bank SET ipa='/ˈməʊ.tə.weɪ/', example_en='We drove fast along the motorway to get there sooner.', example_vi='Chúng tôi lái xe nhanh trên đường cao tốc để đến đó sớm hơn.', translation_vi='đường cao tốc' WHERE id='fl-tr-006';
UPDATE vocabulary_bank SET ipa='/ˈpæs.ən.dʒər/', example_en='There were many passengers on the bus this morning.', example_vi='Có rất nhiều hành khách trên xe buýt sáng nay.', translation_vi='hành khách' WHERE id='fl-tr-007';
UPDATE vocabulary_bank SET ipa='/ˈplæt.fɔːm/', example_en='The train to London departs from platform three.', example_vi='Chuyến tàu đến London khởi hành từ sân ga số ba.', translation_vi='sân ga' WHERE id='fl-tr-008';
UPDATE vocabulary_bank SET ipa='/ˈreɪ.sɪŋ/', example_en='Car racing is a very fast and exciting sport.', example_vi='Đua xe ô tô là một môn thể thao rất nhanh và thú vị.', translation_vi='cuộc đua (xe)' WHERE id='fl-tr-009';
UPDATE vocabulary_bank SET ipa='/ˈreɪl.weɪ/', example_en='We walked along the path near the railway.', example_vi='Chúng tôi đi dạo dọc theo con đường nhỏ gần đường sắt.', translation_vi='đường sắt' WHERE id='fl-tr-010';
UPDATE vocabulary_bank SET ipa='/ˈrɒk.ɪt/', example_en='The rocket blasted off into space.', example_vi='Tên lửa đã phóng lên không gian.', translation_vi='tên lửa' WHERE id='fl-tr-011';
UPDATE vocabulary_bank SET ipa='/ˈspeɪs.ʃɪp/', example_en='The astronauts travelled to the moon in a spaceship.', example_vi='Các phi hành gia đã du hành đến mặt trăng trong một phi thuyền.', translation_vi='phi thuyền' WHERE id='fl-tr-012';
UPDATE vocabulary_bank SET ipa='/ˈtæk.si/', example_en='We took a taxi from the airport to the hotel.', example_vi='Chúng tôi đã đi taxi từ sân bay về khách sạn.', translation_vi='xe taxi' WHERE id='fl-tr-013';
UPDATE vocabulary_bank SET ipa='/tʊər/', example_en='We went on a guided tour of the famous castle.', example_vi='Chúng tôi đã tham gia một chuyến tham quan lâu đài nổi tiếng có hướng dẫn.', translation_vi='chuyến tham quan' WHERE id='fl-tr-014';
UPDATE vocabulary_bank SET ipa='/ˈtræf.ɪk/', example_en='There was a lot of traffic on the road this morning.', example_vi='Sáng nay có rất nhiều xe cộ lưu thông trên đường.', translation_vi='giao thông / xe cộ' WHERE id='fl-tr-015';
UPDATE vocabulary_bank SET ipa='/wiːl/', example_en='The car has four wheels.', example_vi='Chiếc ô tô có bốn bánh xe.', translation_vi='bánh xe' WHERE id='fl-tr-016';

-- Total: 133 rows
