import { writeFileSync, readdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { SUBJECTS } from "../src/react-app/data/subjects";

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, "..");
const OUT_FILE = join(ROOT, "scripts", "seed-quiz-catalog.sql");

// ── Build image_url map from JSON content files ─────────────────────────────
// subjects.ts lesson objects never have image_url → read directly from JSON
// This prevents REPLACE INTO from setting image_url = NULL on every seed run.
const imageUrlMap = new Map<string, string>();

function scanContentDir(dir: string): void {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      scanContentDir(fullPath);
    } else if (entry.name.endsWith(".json")) {
      try {
        const content = JSON.parse(readFileSync(fullPath, "utf8"));
        if (content.id && content.image_url) {
          imageUrlMap.set(content.id, content.image_url);
        }
      } catch { /* skip malformed JSON */ }
    }
  }
}

scanContentDir(join(ROOT, "content"));
console.log(`📸 Found ${imageUrlMap.size} image_urls from content JSON files.`);
// ─────────────────────────────────────────────────────────────────────────────

let sql = `-- Auto-generated from subjects.ts
-- Do not edit this file manually. Run scripts/generate-quiz-catalog-seed.ts to regenerate.

`;

function escapeSql(str: string | null | undefined): string {
  if (str === null || str === undefined) return "NULL";
  return `'${String(str).replace(/'/g, "''")}'`;
}

for (const subject of SUBJECTS) {
  const pathway = escapeSql(subject.pathway);
  const subject_slug = escapeSql(subject.id);
  const group_tag = escapeSql(subject.group);

  for (let i = 0; i < subject.lessons.length; i++) {
    const lesson = subject.lessons[i];
    
    const quiz_id = escapeSql(lesson.id);
    const slug = escapeSql(lesson.slug);
    const level = escapeSql(lesson.level || null);
    const title = escapeSql(lesson.title);
    const emoji = escapeSql(lesson.emoji || subject.emoji || "📖");
    const skill = escapeSql(lesson.skill);
    const part = lesson.part ?? 1;
    const difficulty = escapeSql(lesson.difficulty || "easy");
    const questions = lesson.questions ?? 5;
    const est_minutes = lesson.est_minutes ?? 5;
    
    const is_free = lesson.is_free ? 1 : 0;
    const is_published = 1; // Assuming all in subjects.ts are published
    const show_on_home = lesson.showOnHome !== false ? 1 : 0; // Default true in subjects.ts

    const grade_target = escapeSql(lesson.grade_target || null);
    const grade_min = lesson.grade_min ?? "NULL";
    const grade_max = lesson.grade_max ?? "NULL";
    const in_pool = lesson.in_pool ? 1 : 0;
    const recommended = lesson.recommended ? 1 : 0;
    const unlocks_game = escapeSql(lesson.unlocks_game || null);
    // Ưu tiên image_url từ JSON content file, sau đó mới từ subjects.ts (thường là null)
    const imageFromJson = imageUrlMap.get(lesson.id) ?? null;
    const image_url = escapeSql(imageFromJson || lesson.image_url || null);

    const sort_order = i;

    sql += `REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      ${quiz_id}, ${slug}, ${pathway}, ${subject_slug}, ${level}, ${group_tag},
      ${title}, ${emoji}, ${skill}, ${part}, ${difficulty}, ${questions}, ${est_minutes},
      ${is_free}, ${is_published}, ${show_on_home},
      ${grade_target}, ${grade_min}, ${grade_max}, ${in_pool}, ${recommended},
      ${unlocks_game}, ${sort_order}, ${image_url}
    );\n`;
  }
}

writeFileSync(OUT_FILE, sql);
console.log(`Generated ${OUT_FILE} successfully!`);
