-- Auto-generated from subjects.ts
-- Do not edit this file manually. Run scripts/generate-quiz-catalog-seed.ts to regenerate.

INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P1', 'math-thinking-grade3-l1-p1', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 1', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 0
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P2', 'math-thinking-grade3-l1-p2', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 2', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 1
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P3', 'math-thinking-grade3-l1-p3', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 3', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 2
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P4', 'math-thinking-grade3-l1-p4', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 4', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 3
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P5', 'math-thinking-grade3-l1-p5', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 5', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 4
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P6', 'math-thinking-grade3-l1-p6', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 6', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 5
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P7', 'math-thinking-grade3-l1-p7', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 7', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 6
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P8', 'math-thinking-grade3-l1-p8', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 8', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 7
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P9', 'math-thinking-grade3-l1-p9', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 9', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 8
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P10', 'math-thinking-grade3-l1-p10', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 10', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 9
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE3-P1', 'reading-easy-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 3-4', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 1,
      '3-4', 3, 4, 1, 1,
      NULL, 0
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE4-P1', 'reading-easy-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 4-5', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 1,
      NULL, 1
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE5-P1', 'reading-easy-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 5-6', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 1,
      NULL, 2
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE3-P1', 'reading-med-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 3-4', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 3
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE4-P1', 'reading-med-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 4-5', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 4
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE5-P1', 'reading-med-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 5-6', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 5
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE3-P1', 'reading-hard-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 3-4', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 6
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE4-P1', 'reading-hard-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 4-5', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 7
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE5-P1', 'reading-hard-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 5-6', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 8
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE3-P2', 'reading-easy-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 3-4 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 9
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE4-P2', 'reading-easy-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 4-5 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 10
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-EASY-GRADE5-P2', 'reading-easy-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 5-6 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 11
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE3-P2', 'reading-med-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 3-4 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 12
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE4-P2', 'reading-med-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 4-5 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 13
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-MED-GRADE5-P2', 'reading-med-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 5-6 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 14
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE3-P2', 'reading-hard-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 3-4 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 15
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE4-P2', 'reading-hard-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 4-5 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 16
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'READING-HARD-GRADE5-P2', 'reading-hard-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 5-6 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 17
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE3-P1', 'writing-hard-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 1', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 18
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE3-P2', 'writing-hard-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 19
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE3-P3', 'writing-hard-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 20
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE4-P1', 'writing-hard-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 1', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 21
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE4-P2', 'writing-hard-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 22
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE4-P3', 'writing-hard-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 23
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE5-P1', 'writing-hard-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6', '✏️', 'writing', 1, 'hard', 7, 12,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 24
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE5-P2', 'writing-hard-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 25
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-HARD-GRADE5-P3', 'writing-hard-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 26
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE4-P1', 'writing-med-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 1', '✏️', 'writing', 1, 'medium', 7, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 27
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE4-P2', 'writing-med-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 2', '✏️', 'writing', 1, 'medium', 7, 10,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 28
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE4-P3', 'writing-med-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 3', '✏️', 'writing', 1, 'medium', 7, 10,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 29
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE3-P1', 'writing-easy-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 30
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE3-P2', 'writing-easy-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 31
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE3-P3', 'writing-easy-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 32
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE4-P1', 'writing-easy-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 33
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE4-P2', 'writing-easy-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 34
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE4-P3', 'writing-easy-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 35
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE5-P1', 'writing-easy-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 36
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE5-P2', 'writing-easy-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 37
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-EASY-GRADE5-P3', 'writing-easy-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 38
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE3-P1', 'writing-med-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 1', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 39
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE3-P2', 'writing-med-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 2', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 40
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE3-P3', 'writing-med-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 3', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 41
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE5-P1', 'writing-med-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 1', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 42
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE5-P2', 'writing-med-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 43
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'WRITING-MED-GRADE5-P3', 'writing-med-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 44
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'RW001', 'rw001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Reading Part 4 — Matching', '📖', 'reading', 4, 'easy', 6, 5,
      1, 1, 1,
      NULL, NULL, NULL, 0, 0,
      'hangman', 0
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'L001', 'l001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Listening Part 1 — Chọn đáp án', '🎧', 'listening', 1, 'easy', 5, 5,
      1, 1, 1,
      NULL, NULL, NULL, 0, 0,
      NULL, 1
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'RW002', 'rw002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Reading Part 3 — Điền từ', '✍️', 'reading', 3, 'easy', 5, 5,
      1, 1, 1,
      NULL, NULL, NULL, 0, 0,
      'hangman', 2
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'L002', 'l002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Listening Part 4 — Nghe và nối', '🎵', 'listening', 4, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 3
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'L003', 'l003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Listening Part 2 — Điền thông tin', '📝', 'listening', 2, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 4
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-EASY-001', 'fw1-easy-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: General', '🚀', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 5
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-EASY-002', 'fw1-easy-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Food & Drinks', '🍔', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 6
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-EASY-003', 'fw1-easy-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Clothes & Weather', '🧣', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 7
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-EASY-004', 'fw1-easy-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Hobbies & Leisure', '🎸', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 8
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-MED-001', 'fw1-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: General', '📚', 'reading', 1, 'medium', 10, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 9
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-MED-002', 'fw1-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Sports & Health', '🏅', 'reading', 1, 'medium', 10, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 10
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-MED-003', 'fw1-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Travel & City', '🗺️', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 11
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-MED-004', 'fw1-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Technology', '💻', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 12
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-MED-005', 'fw1-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: Nature & Animals', '🦁', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 13
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-HARD-001', 'fw1-hard-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: Mixed Topics', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 14
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-HARD-002', 'fw1-hard-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Mixed Topics', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 15
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-HARD-003', 'fw1-hard-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Mixed Topics', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 16
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-HARD-004', 'fw1-hard-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Mixed Topics', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 17
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW1-HARD-005', 'fw1-hard-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: Mixed Topics', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 18
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-EASY-001', 'fw2-easy-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: A Visit to the Zoo', '🐵', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 19
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-EASY-002', 'fw2-easy-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Weekend Activities', '🚴', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 20
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-EASY-003', 'fw2-easy-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: A Cold Day', '🤒', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 21
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-EASY-004', 'fw2-easy-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Helping Dad in the Kitchen', '🍳', 'reading', 2, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 22
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-EASY-005', 'fw2-easy-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: A New Hobby', '🎲', 'reading', 2, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 23
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-MED-001', 'fw2-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: A Trip to the Museum', '🏛️', 'reading', 2, 'medium', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 24
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-MED-002', 'fw2-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: A Camping Trip', '⛺', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 25
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-MED-003', 'fw2-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: The Science Project', '🔭', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 26
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-MED-004', 'fw2-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: The Lost Suitcase', '🧳', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 27
    );
INSERT OR IGNORE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order
    ) VALUES (
      'FW2-MED-005', 'fw2-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: The New Music Club', '🎵', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 28
    );
