-- Auto-generated from subjects.ts
-- Do not edit this file manually. Run scripts/generate-quiz-catalog-seed.ts to regenerate.

REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P1', 'math-thinking-grade3-l1-p1', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 1', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 0, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P2', 'math-thinking-grade3-l1-p2', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 2', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 1, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P3', 'math-thinking-grade3-l1-p3', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 3', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 1,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 2, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P4', 'math-thinking-grade3-l1-p4', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 4', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 3, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P5', 'math-thinking-grade3-l1-p5', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 5', '🧮', 'math', 1, 'easy', 10, 12,
      1, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 4, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P6', 'math-thinking-grade3-l1-p6', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 6', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 5, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P7', 'math-thinking-grade3-l1-p7', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 7', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 6, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P8', 'math-thinking-grade3-l1-p8', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 8', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 7, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P9', 'math-thinking-grade3-l1-p9', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 9', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 8, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'MATH-THINKING-GRADE3-L1-P10', 'math-thinking-grade3-l1-p10', 'lop6', 'toan-tu-duy', 'Level 1', 'toan',
      'Toán Tư Duy — Level 1 — Bài 10', '🧮', 'math', 1, 'easy', 10, 12,
      0, 1, 0,
      '3-4', NULL, NULL, 0, 0,
      'hangman', 9, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE3-P1', 'reading-easy-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 3-4', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 1,
      '3-4', 3, 4, 1, 1,
      NULL, 0, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE4-P1', 'reading-easy-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 4-5', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 1,
      NULL, 1, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE5-P1', 'reading-easy-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 5-6', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 1,
      NULL, 2, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE3-P1', 'reading-med-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 3-4', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 3, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE4-P1', 'reading-med-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 4-5', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 4, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE5-P1', 'reading-med-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 5-6', '📚', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 5, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE3-P1', 'reading-hard-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 3-4', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 6, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE4-P1', 'reading-hard-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 4-5', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 7, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE5-P1', 'reading-hard-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 5-6', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 8, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE3-P2', 'reading-easy-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 3-4 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 9, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE4-P2', 'reading-easy-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 4-5 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 10, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-EASY-GRADE5-P2', 'reading-easy-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Easy — Grade 5-6 — Set 2', '📖', 'reading', 1, 'easy', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 11, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE3-P2', 'reading-med-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 3-4 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 12, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE4-P2', 'reading-med-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 4-5 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 13, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-MED-GRADE5-P2', 'reading-med-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Medium — Grade 5-6 — Set 2', '📗', 'reading', 1, 'medium', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 14, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE3-P2', 'reading-hard-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 3-4 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 15, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE4-P2', 'reading-hard-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 4-5 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 16, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'READING-HARD-GRADE5-P2', 'reading-hard-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Reading Comprehension — Hard — Grade 5-6 — Set 2', '🏆', 'reading', 1, 'hard', 8, 10,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 17, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE3-P1', 'writing-hard-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 1', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 18, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE3-P2', 'writing-hard-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 19, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE3-P3', 'writing-hard-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 3-4 — Bài 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 20, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE4-P1', 'writing-hard-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 1', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 21, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE4-P2', 'writing-hard-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 22, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE4-P3', 'writing-hard-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Khó — Lớp 4-5 — Bài 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 23, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE5-P1', 'writing-hard-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6', '✏️', 'writing', 1, 'hard', 7, 12,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 24, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE5-P2', 'writing-hard-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 25, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-HARD-GRADE5-P3', 'writing-hard-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Hard — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'hard', 7, 12,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 26, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE4-P1', 'writing-med-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 1', '✏️', 'writing', 1, 'medium', 7, 10,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 27, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE4-P2', 'writing-med-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 2', '✏️', 'writing', 1, 'medium', 7, 10,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 28, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE4-P3', 'writing-med-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 4-5 — Set 3', '✏️', 'writing', 1, 'medium', 7, 10,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 29, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE3-P1', 'writing-easy-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 30, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE3-P2', 'writing-easy-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 31, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE3-P3', 'writing-easy-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 3-4 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 32, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE4-P1', 'writing-easy-grade4-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 33, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE4-P2', 'writing-easy-grade4-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 34, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE4-P3', 'writing-easy-grade4-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 4-5 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '4-5', 4, 5, 1, 0,
      NULL, 35, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE5-P1', 'writing-easy-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 1', '✏️', 'writing', 1, 'easy', 7, 8,
      1, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 36, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE5-P2', 'writing-easy-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 37, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-EASY-GRADE5-P3', 'writing-easy-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Easy — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'easy', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 38, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE3-P1', 'writing-med-grade3-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 1', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 39, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE3-P2', 'writing-med-grade3-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 2', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 40, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE3-P3', 'writing-med-grade3-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 3-4 — Set 3', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '3-4', 3, 4, 1, 0,
      NULL, 41, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE5-P1', 'writing-med-grade5-p1', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 1', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 42, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE5-P2', 'writing-med-grade5-p2', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 2', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 43, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'WRITING-MED-GRADE5-P3', 'writing-med-grade5-p3', 'lop6', 'tieng-anh-l6', NULL, 'tieng-anh',
      'Writing — Medium — Grade 5-6 — Set 3', '✏️', 'writing', 1, 'medium', 7, 8,
      0, 1, 0,
      '5-6', 5, 6, 1, 0,
      NULL, 44, NULL
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-EASY-001', 'fw1-easy-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: Animals & Everyday Places', '🚀', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 0, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-EASY-01-things-around-us.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-EASY-002', 'fw1-easy-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Food & Drinks', '🍔', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 1, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-EASY-02-food-and-drink.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-EASY-003', 'fw1-easy-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Clothes & Weather', '🧣', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 2, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-EASY-03-clothes-and-weather.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-EASY-004', 'fw1-easy-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Hobbies & Leisure', '🎸', 'reading', 1, 'easy', 10, 6,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 3, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-EASY-04-hobbies-and-leisure.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-MED-001', 'fw1-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: Jobs, Travel & Places', '📚', 'reading', 1, 'medium', 10, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 4, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-MED-01-jobs-travel-and-places.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-MED-002', 'fw1-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Sports & Health', '🏅', 'reading', 1, 'medium', 10, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 5, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-MED-02-sports-and-health.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-MED-003', 'fw1-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Travel & City', '🗺️', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 6, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-MED-03-travel-and-transportation.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-MED-004', 'fw1-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Technology', '💻', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 7, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-MED-04-computing-and-technology.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-MED-005', 'fw1-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: Nature & Animals', '🦁', 'reading', 1, 'medium', 10, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 8, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-MED-05-nature-and-animals.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-HARD-001', 'fw1-hard-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: Education & Professions', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 9, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-HARD-01-education-and-professions.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-HARD-002', 'fw1-hard-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Science & Discovery', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 10, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-HARD-02-science-and-discovery.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-HARD-003', 'fw1-hard-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: Society & Culture', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 11, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-HARD-03-society-and-culture.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-HARD-004', 'fw1-hard-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: History & Society', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 12, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-HARD-04-history-and-society.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW1-HARD-005', 'fw1-hard-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: Technology & Modern World', '🔥', 'reading', 1, 'hard', 10, 10,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 13, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P1-HARD-05-technology-and-modern-world.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-EASY-001', 'fw2-easy-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: A Visit to the Zoo', '🐵', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 14, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P2-EASY-01-a-visit-to-the-zoo.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-EASY-002', 'fw2-easy-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Weekend Activities', '🚴', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 15, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P2-EASY-02-weekend-activities.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-EASY-003', 'fw2-easy-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: A Cold Day', '🤒', 'reading', 2, 'easy', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 16, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P2-EASY-03-a-cold-day.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-EASY-004', 'fw2-easy-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: Helping Dad in the Kitchen', '🍳', 'reading', 2, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 17, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P2-EASY-04-helping-dad-in-the-kitchen.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-EASY-005', 'fw2-easy-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: A New Hobby', '🎲', 'reading', 2, 'easy', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 18, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P2-EASY-05-a-new-hobby.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-MED-001', 'fw2-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: A Trip to the Museum', '🏛️', 'reading', 2, 'medium', 5, 5,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 19, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P2-MED-01-a-trip-to-the-museum.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-MED-002', 'fw2-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: A Camping Trip', '⛺', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 20, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P2-MED-02-a-camping-trip.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-MED-003', 'fw2-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: The Science Project', '🔭', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 21, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P2-MED-03-the-science-project.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-MED-004', 'fw2-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: The Lost Suitcase', '🧳', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 22, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P2-MED-04-the-lost-suitcase.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW2-MED-005', 'fw2-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: The New Music Club', '🎵', 'reading', 2, 'medium', 5, 5,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 23, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P2-MED-05-the-new-music-club.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-001', 'fw3-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: A Camping Adventure 🏕️', '🏕️', 'reading', 3, 'medium', 6, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 24, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P3-MED-01-a-camping-adventure.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-002', 'fw3-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: A Busy Day at the Farm 🚜', '🚜', 'reading', 3, 'medium', 6, 8,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 25, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P3-MED-02-busy-day-at-the-farm.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-003', 'fw3-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: A Day at the Sea 🌊', '🌊', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 26, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P3-MED-03-a-day-at-the-sea.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-004', 'fw3-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: The Space Museum 🚀', '🚀', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 27, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P3-MED-04-the-space-museum.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-005', 'fw3-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: A Visit to the Hospital 🏥', '🏥', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 28, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P3-MED-05-a-visit-to-the-hospital.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-006', 'fw3-med-006', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 6: The Big Football Match ⚽', '⚽', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 29, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-RW-P3-MED-06-the-big-football-match.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-007', 'fw3-med-007', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 7: The Cooking Competition 👨‍🍳', '👨‍🍳', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 30, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-MED-07-the-cooking-competition.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-008', 'fw3-med-008', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 8: A Trip to the Desert 🐪', '🐪', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 31, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-MED-08-a-trip-to-the-desert.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-009', 'fw3-med-009', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 9: The New Invention 🤖', '🤖', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 32, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-MED-09-the-new-invention.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-MED-010', 'fw3-med-010', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 10: A Rainy Day at the Zoo 🌧️', '🌧️', 'reading', 3, 'medium', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 33, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-MED-10-a-rainy-day-at-the-zoo.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-001', 'fw3-hard-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: The Secret of the Ancient Cave 🕳️', '🕳️', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 34, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-01-the-secret-of-the-ancient-cave.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-002', 'fw3-hard-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: Saving the Green Valley 🌳', '🌳', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 35, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-02-saving-the-green-valley.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-003', 'fw3-hard-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: The New Software 💻', '💻', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 36, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-03-the-new-software.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-004', 'fw3-hard-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: The Weather Station 🌤️', '🌤️', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 37, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-04-the-weather-station.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-005', 'fw3-hard-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: The Mysterious Signal 📡', '📡', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 38, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-05-the-mysterious-signal.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-006', 'fw3-hard-006', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 6: The Deep Sea Adventure 🌊', '🌊', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 39, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-06-the-deep-sea-adventure.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-007', 'fw3-hard-007', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 7: The Endangered Forest 🌲', '🌲', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 40, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-07-the-endangered-forest.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-008', 'fw3-hard-008', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 8: The Robot Competition 🤖', '🤖', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 41, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-08-the-robot-competition.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-009', 'fw3-hard-009', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 9: The Digital Discovery 🖥️', '🖥️', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 42, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-09-the-digital-discovery.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW3-HARD-010', 'fw3-hard-010', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 10: The Science Project 🔬', '🔬', 'reading', 3, 'hard', 6, 8,
      0, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 43, 'https://cdn.luyenthi.io.vn/Cambridge/FLYERS/FLYER-RW-P3-HARD-10-the-science-project.jpg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-001', 'fw4-med-001', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 1: Living in Space 🚀', '🚀', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 44, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-01-LIVING%20IN%20SPACE.jpeg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-002', 'fw4-med-002', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 2: The Amazing Giant Panda 🐼', '🐼', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 45, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-02-THE%20AMAZING%20GIANT%20PANDA.jpeg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-003', 'fw4-med-003', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 3: The World of Volcanoes 🌋', '🌋', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 46, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-03-the-world-of-volcanoes.jpeg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-004', 'fw4-med-004', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 4: The Story of Money 💰', '💰', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 47, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-04-the-story-of-money.jpeg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-005', 'fw4-med-005', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 5: The Ship of the Desert 🐪', '🐪', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 48, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-05-the-ship-of-the-desert.jpeg'
    );
REPLACE INTO quiz_catalog (
      quiz_id, slug, pathway, subject_slug, level, group_tag,
      title, emoji, skill, part, difficulty, questions, est_minutes,
      is_free, is_published, show_on_home,
      grade_target, grade_min, grade_max, in_pool, recommended,
      unlocks_game, sort_order, image_url
    ) VALUES (
      'FW4-MED-006', 'fw4-med-006', 'cambridge', 'flyers', 'Flyers', 'flyers',
      'Set 6: High in the Sky ✈️', '✈️', 'reading', 4, 'medium', 10, 10,
      1, 1, 0,
      NULL, NULL, NULL, 0, 0,
      NULL, 49, 'https://cdn.luyenthi.io.vn/Cambridge/FLYER-R%26W-P4-MED-06-high-in-the-sky.jpeg'
    );
